Repository openshift/assisted-test-infra, pull requests merged in 2020-07, with the labels that each got.

#14 Do not use chunked read for S3 downloads
  discovery-infra/bm_inventory_api.py
Labels: approved, lgtm, ok-to-test

#11 Support Route53 DNS env variables
  Makefile
  discovery-infra/update_bm_inventory_cm.py
  scripts/assisted_deployment.sh
  skipper.yaml
Labels: approved, lgtm, ok-to-test

#15 Changed 'IMAGE' env variable to 'ISO'
  .gitignore
  Makefile
  README.md
Labels: approved, lgtm

#6 README fixes
  README.md
Labels: lgtm, ok-to-test

#16 readme: updated OS params details
  README.md
Labels: approved, lgtm, ok-to-test

#17 start_discovery: handle managed-dns-domains
  Makefile
  discovery-infra/start_discovery.py
  discovery-infra/update_bm_inventory_cm.py
  scripts/assisted_deployment.sh
Labels: approved, lgtm, ok-to-test

#24 Check cluster state after install_cluster is called.
  discovery-infra/consts.py
  discovery-infra/install_cluster.py
Labels: approved, lgtm

#23 Fixing update pull secret on install cluster
  discovery-infra/install_cluster.py
Labels: approved, lgtm, ok-to-test

#25 Add --pull flag to always pull images on build
  Makefile
Labels: approved, lgtm

#22 validate DNS authority using dnspython
  discovery-infra/start_discovery.py
  requirements.txt
Labels: approved, lgtm, ok-to-test

#1 Add execution of containerized UI E2E tests
  Makefile
  scripts/test_ui.sh
Labels: approved, lgtm, ok-to-test

#27 start_discovery: remove dns auth validation
  discovery-infra/start_discovery.py
Labels: approved, lgtm, ok-to-test

#29 MGMT-1126: add installing in progress to cluster install validation
  discovery-infra/consts.py
  discovery-infra/install_cluster.py
Labels: approved, lgtm

#30 Igal/fix 2
  scripts/utils.sh
Labels: approved, lgtm

#26 update configmap: empty default for base domains
  Makefile
  discovery-infra/start_discovery.py
  discovery-infra/update_bm_inventory_cm.py
Labels: approved, lgtm, ok-to-test

#31 update_cm: added a comment about empty string handling
  discovery-infra/update_bm_inventory_cm.py
Labels: approved, lgtm

#33 Fixed worker IP address when using non default network CIDR
  discovery-infra/consts.py
  discovery-infra/start_discovery.py
Labels: approved, lgtm

#34 Fixing ip + str issue
  discovery-infra/start_discovery.py
Labels: approved, lgtm

#36 Older versions of podman doesn't support -v flag. Changing it to version
  scripts/install_environment.sh
Labels: approved, lgtm

#38 Fix linting
  discovery-infra/install_cluster.py
  discovery-infra/start_discovery.py
  scripts/test_ui.sh
Labels: approved, lgtm

#32 Increased node registration timeout
  discovery-infra/consts.py
Labels: approved, lgtm

#13 Add Install Guide
  GUIDE.md
  README.md
Labels: approved, kind/documentation, lgtm

#39 Add CONTROLLER_IMAGE environment variable
  README.md
  discovery-infra/update_bm_inventory_cm.py
  skipper.yaml
Labels: approved, lgtm

#37 set_dns: skip when base_dns_domains is set
  scripts/assisted_deployment.sh
Labels: approved, lgtm

#35 discovery: custom cluster name when domain specified
  discovery-infra/start_discovery.py
Labels: approved, lgtm, ok-to-test

#40 start_discovery: run black
  discovery-infra/start_discovery.py
Labels: approved, lgtm

#41 Fixing deploying from ISO
  skipper.yaml
Labels: approved, lgtm

#47 mage build: --pull if docker and --pull-always if podman
  Makefile
Labels: approved, lgtm

#46 Use Precommit GitHub Action
  .github/workflows/pre-commit.yml
Labels: approved, lgtm

#48 Make /etc/passwd writable to allow SSH from a pod
  Dockerfile.test-infra
Labels: approved, lgtm

#49 Adding the deployment of monitoring used on bm-inventory repo
  Makefile
  README.md
Labels: approved, lgtm

#50 Install firewalld
  Dockerfile.test-infra
  Makefile
  discovery-infra/start_discovery.py
  install_env_and_run_full_flow.sh
  scripts/install_environment.sh
Labels: approved, lgtm

#51 MGMT-1578 Adapt test-infra for pending-for-input state
  discovery-infra/consts.py
  discovery-infra/start_discovery.py
Labels: approved, lgtm, ok-to-test

#52 increase minikube memory
  scripts/run_minikube.sh
Labels: approved, lgtm

#4 Adding the ability to automatically Create, Mount, Boot the Discovery ISO on baremetal servers
  ansible-bm-install/.gitignore
  ansible-bm-install/README.adoc
  ansible-bm-install/ansible.cfg
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/FILES.json
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/MANIFEST.json
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/README.md
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/docs/README.adoc
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/galaxy.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/plugins/README.md
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/boot_iso/defaults/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/boot_iso/handlers/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/boot_iso/meta/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/boot_iso/tasks/boot_iso.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/boot_iso/tasks/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/boot_iso/tests/inventory
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/boot_iso/tests/test.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/boot_iso/vars/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/boot_iso_existing_os/defaults/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/boot_iso_existing_os/handlers/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/boot_iso_existing_os/meta/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/boot_iso_existing_os/tasks/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/boot_iso_existing_os/tests/inventory
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/boot_iso_existing_os/tests/test.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/boot_iso_existing_os/vars/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/create_iso/defaults/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/create_iso/handlers/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/create_iso/meta/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/create_iso/tasks/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/create_iso/tests/inventory
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/create_iso/tests/test.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/create_iso/vars/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/host_iso/defaults/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/host_iso/handlers/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/host_iso/library/podman_container.py
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/host_iso/meta/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/host_iso/tasks/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/host_iso/tests/inventory
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/host_iso/tests/test.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/host_iso/vars/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/setup_repository/defaults/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/setup_repository/handlers/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/setup_repository/meta/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/setup_repository/tasks/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/setup_repository/tests/inventory
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/setup_repository/tests/test.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/setup_repository/vars/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/validations/defaults/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/validations/handlers/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/validations/meta/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/validations/tasks/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/validations/tests/inventory
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/validations/tests/test.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/validations/vars/main.yml
  ansible-bm-install/inventory/hosts-with-existing-os.sample
  ansible-bm-install/inventory/hosts_with_os.sample
  ansible-bm-install/inventory/hosts_without_os.sample
  ansible-bm-install/playbook_assisted_installer_with_os.yml
  ansible-bm-install/playbook_assisted_installer_without_os.yml
  ansible-bm-install/requirements.yml
Labels: approved, lgtm

#53 Extended cluster installation timeout from 10 minutes to 30
  discovery-infra/consts.py
  discovery-infra/install_cluster.py
Labels: approved, lgtm

#55 MGMT-1182 test-infra should not reference the hw-info but the inventory data
  discovery-infra/bm_inventory_api.py
  discovery-infra/start_discovery.py
Labels: approved, lgtm, needs-ok-to-test

#54 Add troubleshooting section to the install guide
  GUIDE.md
Labels: approved, lgtm

#57 Igal/disk sizes
  GUIDE.md
  Makefile
  discovery-infra/start_discovery.py
  skipper.yaml
  terraform_files/main.tf
  terraform_files/variables-libvirt.tf
Labels: approved, lgtm

#56 Print exception details on delete nodes error
  discovery-infra/delete_nodes.py
Labels: approved, lgtm

#60 Support custom MTU for nodes libvirt network
  Makefile
  README.md
  discovery-infra/start_discovery.py
  skipper.yaml
  terraform_files/main.tf
  terraform_files/network/main.tf
  terraform_files/terraform.tfvars.json
  terraform_files/variables-libvirt.tf
Labels: approved, lgtm

#61 Allow customize images for inventory configmap
  discovery-infra/update_bm_inventory_cm.py
  skipper.yaml
Labels: approved, lgtm

#59 add ssh/kexec based boot into discovery flow
  scripts/kexec/README.md
  scripts/kexec/coreos-redeploy.sh
  scripts/kexec/install-cluster.sh
Labels: approved, lgtm, ok-to-test

#58 MGMT-1231 Accept custom namespace
  GUIDE.md
  Makefile
  discovery-infra/bm_inventory_api.py
  discovery-infra/delete_nodes.py
  discovery-infra/install_cluster.py
  discovery-infra/start_discovery.py
  discovery-infra/utils.py
  scripts/deploy_bm_inventory.sh
  scripts/deploy_ui.sh
  scripts/utils.sh
  skipper.yaml
Labels: approved, lgtm

#64 Update README with customized images OS params
  README.md
Labels: approved, lgtm

#65 Bugfix: Set DNS function strings condition
  Makefile
  scripts/assisted_deployment.sh
Labels: approved, lgtm

#67 MGMT-1231: deploy_ui.sh pull image before generating ui yaml
  scripts/deploy_ui.sh
Labels: lgtm

#69 Set minikube driver and not build on default
  scripts/run_minikube.sh
Labels: approved, lgtm

#68 Update OWNERS
  OWNERS
Labels: approved, lgtm
