Repository openshift/assisted-test-infra, pull requests merged in 2021-11, with the labels that each got.

#1202 NO-ISSUE - Fix junit log parser adding multiple success cases
  discovery-infra/junit_log_parser.py
Labels: size/M, approved, lgtm

#1205 Fix download kubeconfig-noingress
  discovery-infra/test_infra/assisted_service_api.py
Labels: approved, size/XS, lgtm

#1203 NO-ISSUE: disable VIP DHCP allocation when using OVNKubernetes
  discovery-infra/test_infra/utils/global_variables/global_variables.py
Labels: approved, size/XS, lgtm

#1208 NO-ISSUE: capture stdout and stderr on terraform failure
  discovery-infra/test_infra/tools/terraform_utils.py
Labels: approved, size/XS, lgtm

#1200 MGMT-7990 - Unite test-infra Cluster and InfraEnv objects under same base object
  discovery-infra/test_infra/consts/__init__.py
  discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/helper_classes/entity.py
  discovery-infra/test_infra/helper_classes/infra_env.py
  discovery-infra/tests/base_test.py
  discovery-infra/tests/test_e2e_install.py
Labels: size/L, approved, lgtm

#1199 MGMT-7983 - Fix e2e-metal-assisted-networking flaky test
  discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/helper_classes/config/base_config.py
  discovery-infra/test_infra/helper_classes/nodes.py
  discovery-infra/test_infra/utils/global_variables/global_variables.py
  discovery-infra/test_infra/utils/global_variables/triggerable.py
  discovery-infra/tests/test_e2e_install.py
Labels: size/L, approved, lgtm

#1201 Refactor terraform templates to use baremetal_host module
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/consts/consts.py
  discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
  discovery-infra/test_infra/tools/static_network.py
  discovery-infra/test_infra/utils/kubeapi_utils.py
  discovery-infra/test_infra/utils/utils.py
  terraform_files/baremetal/main.tf
  terraform_files/baremetal_host/consolemodel.xsl
  terraform_files/baremetal_host/main.tf
  terraform_files/baremetal_host/variables.tf
  terraform_files/baremetal_infra_env/main.tf
  terraform_files/none/main.tf
Labels: size/XL, approved, lgtm

#1210 NO-ISSUE: fix static IP mode after terraform refactoring
  discovery-infra/day2.py
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/tools/static_network.py
Labels: size/S, approved, lgtm

#1212 NO-ISSUE - Fix empty `entity_name` when `cluster_name` is already set
  discovery-infra/tests/config/global_configs.py
Labels: approved, size/XS, lgtm

#1211 NO-ISSUE - Set `wait_for_networking` as best effort
  discovery-infra/test_infra/helper_classes/nodes.py
Labels: size/S, approved, lgtm

#1209 NO-ISSUE - parse leader election logs to junit report
  discovery-infra/junit_log_parser.py
Labels: size/S, approved, lgtm

#1213 Adding a retry on tf init
  discovery-infra/test_infra/tools/terraform_utils.py
Labels: approved, size/XS, lgtm

#1214 MGMT-7977 - Move test-infra events from Cluster to separate object
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/helper_classes/events_handler.py
  discovery-infra/test_infra/helper_classes/nodes.py
  discovery-infra/test_infra/tools/terraform_utils.py
  discovery-infra/tests/base_test.py
Labels: size/L, approved, lgtm

#1225 No-ISSUE - Extend `wait_for_networking` timeout to 3 minutes
  discovery-infra/test_infra/helper_classes/nodes.py
Labels: approved, size/XS, lgtm

#1226 NO-ISSUE - Fix wrong level formats on junit_log_parser.py
  discovery-infra/junit_log_parser.py
Labels: approved, size/XS

#1227 MGMT-8176 - Show service events failures on PROW spyglass
  discovery-infra/test_infra/assisted_service_api.py
  requirements.txt
Labels: size/S, approved, lgtm

#1196 NO-ISSUE: Update minikube to 1.23.2 and pin OCP client to stable-4.8
  scripts/install_minikube.sh
Labels: approved, size/XS, lgtm

#1231 NO-ISSUE: fix installation of oc with the right artifact
  scripts/install_minikube.sh
Labels: approved, size/XS, lgtm

#1229 MGMT-8193 - Remove download_image logic from assisted_service_api.py and use infra_env.download_url to download it
  discovery-infra/test_infra/assisted_service_api.py
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/helper_classes/entity.py
  discovery-infra/test_infra/helper_classes/infra_env.py
  discovery-infra/test_infra/utils/utils.py
Labels: size/M, approved, lgtm

#1232 MGMT-7983 - Fix networking job
  discovery-infra/test_infra/helper_classes/cluster.py
Labels: approved, size/XS, lgtm

#1237 NO-ISSUE: remove all elasticsearch-related code
  Makefile
  discovery-infra/log_scrap.py
  discovery-infra/monitoring/__init__.py
  discovery-infra/monitoring/docker-compose.yml
  discovery-infra/monitoring/process.py
  requirements.txt
Labels: size/L, approved, lgtm

#1244 NO-ISSUE: Bump libgcrypt version
  scripts/install_environment.sh
Labels: approved, size/XS, lgtm

#1243 NO-ISSUE: remove jira from requirements.txt as it's not being used
  requirements.txt
Labels: approved, size/XS, lgtm

#1234 MGMT-8181: added day2 cloud flow to e2e tests
  Makefile
  discovery-infra/day2.py
  discovery-infra/deprecated_utils.py
  discovery-infra/test_infra/consts/env_defaults.py
  discovery-infra/tests/test_day2.py
Labels: size/M, approved, lgtm

#1245 NO-ISSUE: always upgrade libgcrypt package using regular sources
  scripts/install_environment.sh
Labels: approved, size/XS, lgtm

#1247 Fix for logs test on V1
  discovery-infra/test_infra/utils/logs_utils.py
Labels: ok-to-test, approved, size/XS, lgtm

#1248 NO-ISSUE: always upgrade libgcrypt package using regular sources
  scripts/install_environment.sh
Labels: approved, size/XS, lgtm

#1238 MGMT-8146: fix dual-stack installations
  discovery-infra/test_infra/consts/consts.py
  discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/helper_classes/config/cluster_config.py
  discovery-infra/test_infra/utils/global_variables/triggerable.py
Labels: size/M, approved, lgtm

#1252 remove yuval from approver list
  OWNERS
Labels: approved, size/XS, lgtm

#1255 Dockerfile for assisted-test-infra which uses Python 3.9
  Dockerfile.assisted-test-infra
  requirements-39.txt
Labels: size/M, approved, lgtm

#1258 Changing workdir to a different directory than /
  Dockerfile.assisted-test-infra
Labels: approved, size/XS, lgtm

#1259 Revert "NO-ISSUE: remove all elasticsearch-related code (#1237)"
  Makefile
  discovery-infra/log_scrap.py
  discovery-infra/monitoring/__init__.py
  discovery-infra/monitoring/docker-compose.yml
  discovery-infra/monitoring/process.py
  requirements.txt
Labels: size/L, approved, lgtm

#1260 MGMT-8366 - Download image using url on v1 branch
  discovery-infra/test_infra/assisted_service_api.py
  discovery-infra/test_infra/utils/utils.py
Labels: size/S, approved, lgtm

#1263 Always upgrade libgcrypt package using regular sources (#1248)
  scripts/install_environment.sh
Labels: size/XS

#1261 Allow overriding dockerfile path
  Makefile
  skipper.env
Labels: approved, size/XS, lgtm

#1262 MGMT-7351 - Move deployment scripts from assisted-service into test-infra scripts
  Makefile
  scripts/deploy_assisted_service.sh
  scripts/operator/README.md
  scripts/operator/common.sh
  scripts/operator/deploy.sh
  scripts/operator/destroy.sh
  scripts/operator/gather.sh
  scripts/operator/libvirt_disks.sh
  scripts/operator/mirror_utils.sh
  scripts/operator/set_ca_bundle.py
  scripts/operator/setup_assisted_operator.sh
  scripts/operator/setup_hive.sh
  scripts/operator/setup_lso.sh
  scripts/operator/upgrade/README.md
  scripts/operator/upgrade/after_upgrade.sh
  scripts/operator/upgrade/before_upgrade.sh
  scripts/operator/upgrade/upgrade.sh
  scripts/operator/utils.sh
  scripts/operator/ztp/add-remote-nodes-playbook.yaml
  scripts/operator/ztp/add_day2_remote_nodes.sh
  scripts/operator/ztp/agentClusterInstall.j2
  scripts/operator/ztp/assisted-installer-crds-playbook.yaml
  scripts/operator/ztp/baremetalHost.j2
  scripts/operator/ztp/clusterDeployment.j2
  scripts/operator/ztp/clusterImageSet.j2
  scripts/operator/ztp/deploy_spoke_cluster.sh
  scripts/operator/ztp/infraEnv.j2
Labels: size/XXL, approved, lgtm
