Repository openshift/assisted-test-infra, pull requests merged in 2021-09, with the labels that each got.

#1074 MGMT-7727 - Remove redundant cluster and entity config properties
  discovery-infra/test_infra/helper_classes/config/base_entity_config.py
  discovery-infra/test_infra/helper_classes/config/base_infra_env_config.py
  discovery-infra/test_infra/helper_classes/config/cluster_config.py
Labels: size/M, approved, lgtm

#1076 NO-ISSUE - Remove junk target in Makefile that was accidentally committed
  Makefile
Labels: approved, size/XS, lgtm

#1079 NO-ISSUE - Fix Proxy-Server teardown is always executing
  discovery-infra/tests/base_test.py
Labels: approved, size/XS, lgtm

#1080 NO-ISSUE - Fix Nat teardown is always executing
  discovery-infra/tests/base_test.py
Labels: size/S, approved, lgtm

#1081 NO-ISSUE - Fix base test prepare_nodes fixtures.
  discovery-infra/tests/base_test.py
Labels: size/M, approved, lgtm

#1075 MGMT-7731 - Rearrange entities operations
  discovery-infra/bootstrap_in_place.py
  discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
  discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/helper_classes/config/base_entity_config.py
  discovery-infra/test_infra/helper_classes/config/base_infra_env_config.py
  discovery-infra/test_infra/helper_classes/config/cluster_config.py
  discovery-infra/test_infra/helper_classes/infra_env.py
  discovery-infra/test_infra/utils/cluster_name.py
  discovery-infra/test_infra/utils/entity_name.py
  discovery-infra/test_infra/utils/infra_env_name.py
  discovery-infra/test_infra/utils/kubeapi_utils.py
  discovery-infra/tests/config/global_configs.py
Labels: size/L, approved, lgtm

#1082 NO-ISSUE - Fix PEP8 violations on assisted_service_api.py.
  discovery-infra/test_infra/assisted_service_api.py
Labels: size/M, approved, lgtm

#1085 Update OWNERS
  OWNERS
Labels: approved, size/XS, lgtm

#1077 Adding service restart method
  discovery-infra/test_infra/controllers/node_controllers/node.py
Labels: ok-to-test, approved, size/XS, lgtm

#1083 NO-ISSUE - Move `get_copy` to BaseConfig class instead of duplicate it on each configuration
  discovery-infra/test_infra/helper_classes/config/base_config.py
  discovery-infra/test_infra/helper_classes/config/controller_config.py
  discovery-infra/test_infra/helper_classes/config/vsphere_config.py
  discovery-infra/tests/config/global_configs.py
Labels: size/S, approved, lgtm

#1086 MGMT-7643: supporting versions newer than 4.8 on deploy
  scripts/deploy_assisted_service.sh
Labels: approved, size/XS, lgtm

#1088 Use kubeconfig path that always exists
  discovery-infra/resources/man_sosreport.sh
Labels: approved, size/XS, lgtm

#1073 Add infraenv delete and get methods
  discovery-infra/test_infra/assisted_service_api.py
Labels: approved, size/XS, lgtm

#1089 NO-ISSUE - Add log on load balancer successful connection.
  discovery-infra/test_infra/consts/consts.py
  discovery-infra/test_infra/controllers/load_balancer_controller.py
Labels: size/S, approved, lgtm

#1084 NO-ISSUE - Make _EnvVariablesUtils singleton.
  discovery-infra/test_infra/helper_classes/config/controller_config.py
  discovery-infra/test_infra/utils/global_variables/env_variables_defaults.py
  discovery-infra/test_infra/utils/global_variables/global_variables.py
  discovery-infra/tests/base_test.py
Labels: size/S, approved, lgtm

#1015 MGMT-7105 - create multiple clusters on vsphere (multiple AIs might h…
  discovery-infra/test_infra/controllers/node_controllers/vsphere_controller.py
  discovery-infra/test_infra/tools/terraform_utils.py
  terraform_files/vsphere-ci-machine/main.tf
  terraform_files/vsphere-ci-machine/terraform.tfvars.json
  terraform_files/vsphere-ci-machine/variables-vsphere.tf
  terraform_files/vsphere/main.tf
  terraform_files/vsphere/terraform.tfvars.json
  terraform_files/vsphere/variables-vsphere.tf
Labels: size/L, approved, lgtm

#1091 MGMT-7480: OS_IMAGES & RELEASE_IMAGES support
  README.md
  skipper.env
Labels: do-not-merge/hold, approved, size/XS, lgtm

#1092 NO-ISSUE: readme update
  README.md
Labels: approved, size/XS, lgtm

#1090 MGMT-6699 - Move utils libvirt functions to controller. Move unused utils functions to deprecated_utils.py.
  discovery-infra/bootstrap_in_place.py
  discovery-infra/day2.py
  discovery-infra/delete_nodes.py
  discovery-infra/deprecated_utils.py
  discovery-infra/install_cluster.py
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/consts/consts.py
  discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
  discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/helper_classes/infra_env.py
  discovery-infra/test_infra/utils/kubeapi_utils.py
  discovery-infra/test_infra/utils/utils.py
  discovery-infra/test_infra/utils/waiting.py
Labels: size/XL, approved, lgtm

#1100 NO-ISSUE - Fix missing extract_installer on bootstrap_in_place.py
  discovery-infra/bootstrap_in_place.py
Labels: approved, size/XS, lgtm

#1099 Fix static IPs config option and use a new name
  Makefile
  README.md
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/consts/env_defaults.py
  discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/helper_classes/nodes.py
  discovery-infra/test_infra/utils/global_variables/env_variables_defaults.py
  skipper.env
Labels: size/M, approved, lgtm

#1101 MGMT-7173: podman support
  Dockerfile.test-infra
  Makefile
  discovery-infra/test_infra/consts/consts.py
  discovery-infra/test_infra/utils/utils.py
  scripts/deploy_assisted_service.sh
  scripts/install_environment.sh
  scripts/test_ui.sh
  scripts/utils.sh
  skipper.yaml
Labels: size/M, approved, lgtm

#1104 Revert "MGMT-7173: podman support (#1101)"
  Dockerfile.test-infra
  Makefile
  discovery-infra/test_infra/consts/consts.py
  discovery-infra/test_infra/utils/utils.py
  scripts/deploy_assisted_service.sh
  scripts/install_environment.sh
  scripts/test_ui.sh
  scripts/utils.sh
  skipper.yaml
Labels: size/M, approved, lgtm

#1107 Fix dictionary update for _get_domain_ips_and_macs()
  discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
Labels: needs-ok-to-test, size/S, approved, lgtm

#1106 MGMT-7786: remove openshift_version in kube-api flow
  scripts/deploy_assisted_service.sh
Labels: size/S, approved, lgtm

#1103 Update dependabot.yml
  .github/dependabot.yml
Labels: approved, size/XS, lgtm

#1102 MGMT-7744: Add test_networking test
  Makefile
  discovery-infra/tests/conftest.py
  discovery-infra/tests/test_e2e_install.py
Labels: size/S, approved, lgtm

#1113 Ignore libvirt errors when trying to get domain ips and macs
  discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
Labels: size/S, approved, lgtm

#1067 MGMT-5274: Fix test_kube_api
  discovery-infra/install_cluster.py
  discovery-infra/test_infra/consts/consts.py
  discovery-infra/test_infra/helper_classes/kube_helpers/agent.py
  discovery-infra/test_infra/utils/global_variables/env_variables_defaults.py
  discovery-infra/tests/base_test.py
  discovery-infra/tests/test_kube_api.py
  scripts/deploy_assisted_service.sh
Labels: size/M, approved, lgtm

#1098 MGMT-7523 - Added initial kube-api late binding test
  discovery-infra/test_infra/assisted_service_api.py
  discovery-infra/test_infra/consts/consts.py
  discovery-infra/test_infra/controllers/node_controllers/node_controller.py
  discovery-infra/test_infra/helper_classes/kube_helpers/agent.py
  discovery-infra/test_infra/helper_classes/kube_helpers/infraenv.py
  discovery-infra/test_infra/utils/entity_name.py
  discovery-infra/test_infra/utils/utils.py
  discovery-infra/tests/base_test.py
  discovery-infra/tests/test_kube_api.py
  pyproject.toml
Labels: size/L, approved, lgtm

#1117 MGMT-7523: Add highly-available / single-node late binding kubeapi tests
  discovery-infra/test_infra/consts/consts.py
  discovery-infra/test_infra/controllers/node_controllers/node_controller.py
  discovery-infra/test_infra/helper_classes/kube_helpers/agent.py
  discovery-infra/test_infra/helper_classes/kube_helpers/agent_cluster_install.py
  discovery-infra/tests/test_kube_api.py
Labels: size/L, approved, lgtm

#1105 Use rpmfind.net/linux/centos/8 path to install libgcrypt
  scripts/install_environment.sh
Labels: approved, size/XS, lgtm

#1112 MGMT-6763: Add IPv4 config
  discovery-infra/test_infra/consts/env_defaults.py
  discovery-infra/test_infra/controllers/node_controllers/node_controller.py
  discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/helper_classes/config/base_entity_config.py
  discovery-infra/test_infra/helper_classes/config/controller_config.py
  discovery-infra/test_infra/helper_classes/nodes.py
  discovery-infra/test_infra/utils/global_variables/env_variables_defaults.py
  discovery-infra/test_infra/utils/global_variables/global_variables.py
  discovery-infra/tests/base_test.py
Labels: size/M, approved, lgtm

#1126 NO-ISSUE: Force load balancer container to use the host as DNS
  Makefile
Labels: approved, size/XS, lgtm

#1127 NO-ISSUE: Check IPS on static IPs mode
  discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/helper_classes/infra_env.py
  discovery-infra/test_infra/helper_classes/nodes.py
  discovery-infra/test_infra/utils/operators_utils.py
Labels: size/S, approved, lgtm
