Repository openshift/assisted-test-infra, pull requests merged in 2021-04, with the labels that each got.

#654 NO-ISSUE implement a 'kubectl apply' like interface
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/helper_classes/kube_helpers/base_resource.py
  discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py
  discovery-infra/test_infra/helper_classes/kube_helpers/secret.py
Labels: approved, lgtm

#657 NOISSUE: InstallEnv: proxy will be optional argument on creation
  discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py
  discovery-infra/test_infra/helper_classes/kube_helpers/global_vars.py
  discovery-infra/test_infra/helper_classes/kube_helpers/installenv.py
  discovery-infra/test_infra/helper_classes/kube_helpers/secret.py
Labels: approved, lgtm

#658 MGMT-4852 enable kube-api by default
  Makefile
Labels: approved, lgtm

#655 MGMT-3335 teardown iptables in nodes
  discovery-infra/test_infra/controllers/nat_controller.py
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/helper_classes/nodes.py
  discovery-infra/tests/base_test.py
Labels: approved, lgtm

#660 Install minikube and kubectl using arkade
  scripts/install_minikube.sh
Labels: approved, lgtm

#656 Add xtrace for run_minikube script
  scripts/run_minikube.sh
Labels: approved, lgtm

#661 NOISSUE: deploy_default_cluster_deployment with objects instead of dict
  discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py
Labels: approved, lgtm

#659 NOISSUE: Agent - wait for status
  discovery-infra/test_infra/helper_classes/kube_helpers/agent.py
Labels: approved, lgtm

#662 MGMT-4706 - add api to the assisted-service api to support mirror reg…
  discovery-infra/test_infra/assisted_service_api.py
Labels: approved, lgtm

#668 NO-ISSUE ignore .env file to enable customization
  .gitignore
Labels: approved, lgtm

#666 NOISSUE: KubeAPI: increased default timeouts
  discovery-infra/test_infra/helper_classes/kube_helpers/global_vars.py
Labels: approved, lgtm

#669 Adding method in ClusterDeployment to annotate install config
  discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py
Labels: approved, lgtm

#672 NOISSUE: ClusterDeployment: Updated annotate_install_config
  discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py
Labels: approved, lgtm

#617 MGMT-4535 - Create junit reporter package
  Makefile
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/tests/base_test.py
  discovery-infra/tests/test_install.py
  requirements.txt
Labels: approved, lgtm

#671 NO-ISSUE do not attemp to install from REST if kubeapi cluster is ready
  discovery-infra/install_cluster.py
Labels: approved, lgtm

#674 NO-ISSUE disable kube-api by default
  Makefile
Labels: approved, lgtm

#673 NO-ISSUE pull latest code on origin remote
  Makefile
  README.md
Labels: approved, lgtm

#675 NO-ISSUE update minikube version if stale
  scripts/install_minikube.sh
Labels: approved, lgtm

#677 Set minikube tunnel for the relevant profile
  scripts/run_minikube.sh
Labels: approved, lgtm

#679 Revert "NO-ISSUE pull latest code on origin remote"
  Makefile
  README.md
Labels: approved

#681 Fix sync branches for assisted-service
  Makefile
Labels: approved, lgtm

#680 NO-ISSUE setting ENABLE_KUBE_API default to false in jenkins file and deploy_service script
  Jenkinsfile
  scripts/deploy_assisted_service.sh
Labels: approved, lgtm

#667 MGMT-4870 Add nmstate via kube-api automation
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/helper_classes/kube_helpers/__init__.py
  discovery-infra/test_infra/helper_classes/kube_helpers/installenv.py
  discovery-infra/test_infra/helper_classes/kube_helpers/nmstate_config.py
Labels: approved, lgtm

#684 NOISSUE centralized kube api group and version vars
  discovery-infra/test_infra/helper_classes/kube_helpers/agent.py
  discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py
  discovery-infra/test_infra/helper_classes/kube_helpers/global_vars.py
  discovery-infra/test_infra/helper_classes/kube_helpers/installenv.py
  discovery-infra/test_infra/helper_classes/kube_helpers/nmstate_config.py
Labels: approved, lgtm

#682 Adding cluster methods for e2e
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/utils.py
Labels: approved, lgtm

#686 NO-ISSUE Fix minikube upgrades on older systems
  scripts/install_minikube.sh
Labels: approved, lgtm

#647 Remove minikube profile
  Jenkinsfile
  Jenkinsfile.test
  Makefile
  create_full_environment.sh
  discovery-infra/delete_nodes.py
  discovery-infra/install_cluster.py
  discovery-infra/ocp.py
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/utils.py
  discovery-infra/tests/conftest.py
  scripts/deploy_assisted_service.sh
  scripts/deploy_prometheus_ui.sh
  scripts/deploy_ui.sh
  scripts/download_logs.sh
  scripts/run_minikube.sh
  scripts/utils.sh
  skipper.env
Labels: approved, lgtm

#683 NOISSUE: raise error if ClusterDeployment status changed to error
  discovery-infra/test_infra/helper_classes/kube_helpers/__init__.py
  discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py
  discovery-infra/test_infra/helper_classes/kube_helpers/common.py
  discovery-infra/test_infra/helper_classes/kube_helpers/global_vars.py
Labels: approved, lgtm

#678 NOISSUE: remove any rest api call from kube api flow
  discovery-infra/install_cluster.py
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/kubeapi_utils.py
Labels: approved, lgtm

#690 Adding 1.5h timeout for OCS installation
  discovery-infra/test_infra/consts.py
  discovery-infra/test_infra/helper_classes/cluster.py
Labels: approved, lgtm

#692 NO-ISSUE do not use an explicit kubeconfig path
  discovery-infra/start_discovery.py
Labels: approved, lgtm

#696 NOISSUE: delete_nodes.py: delete kube api resources if KUBE_API=true
  Makefile
  discovery-infra/delete_nodes.py
  discovery-infra/test_infra/helper_classes/kube_helpers/__init__.py
  discovery-infra/test_infra/helper_classes/kube_helpers/common.py
  discovery-infra/test_infra/kubeapi_utils.py
Labels: approved, lgtm

#687 MGMT-4638 Rename `Group/Version` to `agent-install.openshift.io/v1beta1`
  discovery-infra/test_infra/helper_classes/kube_helpers/global_vars.py
Labels: approved, lgtm

#701 Catching must gather exception to avoid Runtime error
  discovery-infra/download_logs.py
Labels: approved, lgtm

#703 NO-ISSUE support remotely debug e2e testing via VSCODE
  Makefile
  requirements.txt
  skipper.env
Labels: approved, lgtm

#705 NO-ISSUE add michaellevy101 as approver
  OWNERS
Labels: approved, lgtm

#704 MGMT-4050 E2E tests for disk ID
  discovery-infra/test_infra/assisted_service_api.py
  discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
  discovery-infra/test_infra/controllers/node_controllers/node_controller.py
  discovery-infra/tests/base_test.py
Labels: approved, lgtm

#702 MGMT-4921 Rename InstallEnv --> InfraEnv
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/helper_classes/kube_helpers/__init__.py
  discovery-infra/test_infra/helper_classes/kube_helpers/infraenv.py
  discovery-infra/test_infra/kubeapi_utils.py
Labels: approved, lgtm

#708 Fix operator status when waiting for operator to finish
  discovery-infra/test_infra/helper_classes/cluster.py
Labels: approved, lgtm

#691 MGMT-4093 - If cluster exists, get its name and base DNS domain from …
  discovery-infra/day2.py
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/consts.py
  discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
  discovery-infra/tests/conftest.py
Labels: approved, lgtm

#700 MGMT-4577 kube_helpers: Added ClusterImageSet class
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/helper_classes/kube_helpers/__init__.py
  discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py
  discovery-infra/test_infra/helper_classes/kube_helpers/cluster_image_set.py
  discovery-infra/test_infra/utils.py
  scripts/deploy_assisted_service.sh
Labels: approved, lgtm

#711 NO-ISSUE - Add eliorerz as approver
  OWNERS
Labels: approved, lgtm

#712 NO-ISSUE fix cluster deployment when there is no state yet
  discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py
Labels: approved, lgtm

#707 MGMT-4792 Dynamically change vm resources based on enabled operators
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/consts.py
  discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
  discovery-infra/test_infra/utils.py
Labels: approved, lgtm

#688 MGMT-4918 Support configurations for test-infra pytest
  README.md
  discovery-infra/test_infra/helper_classes/nodes.py
  discovery-infra/test_infra/utils.py
  discovery-infra/tests/base_test.py
  discovery-infra/tests/conftest.py
  discovery-infra/tests/test_install.py
Labels: approved, lgtm

#713 MGMT-5269 fix ENABLE_KUBE_API check on deploy service
  scripts/deploy_assisted_service.sh
Labels: approved, lgtm

#706 MGMT-5189 - Add deprecation warning on pending deprecation scripts.
  discovery-infra/bootstrap_in_place.py
  discovery-infra/day2.py
  discovery-infra/delete_nodes.py
  discovery-infra/download_logs.py
  discovery-infra/install_cluster.py
  discovery-infra/log_scrap.py
  discovery-infra/oc_utils.py
  discovery-infra/ocp.py
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/__init__.py
  discovery-infra/update_assisted_service_cm.py
  discovery-infra/virsh_cleanup.py
Labels: approved, lgtm

#689 MGMT-4640 Using HW_VALIDATOR_REQUIREMENTS
  discovery-infra/update_assisted_service_cm.py
Labels: approved, lgtm

#716 revert openshift versions handling
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/helper_classes/kube_helpers/__init__.py
  discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py
  discovery-infra/test_infra/helper_classes/kube_helpers/cluster_image_set.py
  discovery-infra/test_infra/utils.py
  scripts/deploy_assisted_service.sh
Labels: approved, lgtm

#718 NO-ISSUE allow installation of non-sno cluster
  Makefile
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py
Labels: approved, lgtm

#715 NO-ISSUE - Fix empty OLM_OPERATORS var bug
  discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
  discovery-infra/test_infra/utils.py
  discovery-infra/tests/conftest.py
Labels: approved, lgtm

#698 NO-ISSUE Refactoring of execute_day_1 and kube-api flow
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py
Labels: approved, lgtm

#719 MGMT-4577 kube_helpers: Added ClusterImageSet class
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/helper_classes/kube_helpers/__init__.py
  discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py
  discovery-infra/test_infra/helper_classes/kube_helpers/cluster_image_set.py
  discovery-infra/test_infra/kubeapi_utils.py
  discovery-infra/test_infra/utils.py
  scripts/deploy_assisted_service.sh
Labels: approved, lgtm

#720 MGMT-5265 Add doc reference to DISABLED_HOST_VALIDATIONS environment variable
  README.md
Labels: approved, lgtm

#722 NO-ISSUE - Fix deprecation message on pytest execution
  discovery-infra/test_infra/__init__.py
Labels: approved, lgtm

#714 Mgmt 4050 Adding a new Disk object type and support per device boot order
  discovery-infra/test_infra/controllers/node_controllers/disk.py
  discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
  discovery-infra/test_infra/controllers/node_controllers/node.py
  discovery-infra/test_infra/controllers/node_controllers/node_controller.py
Labels: approved, lgtm

#726 Restore list_nodes
  discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
Labels: approved, lgtm

#727 refactor kube-api flow a bit to remove non-needed if branch
  discovery-infra/start_discovery.py
Labels: approved, lgtm

#717 MGMT-4482 Use local auth with kube-api by default
  Makefile
Labels: approved, lgtm

#728 MGMT-5340 - Delete QeVmController
  discovery-infra/test_infra/controllers/node_controllers/qe_vm_controler.py
  discovery-infra/tests/base_test.py
  discovery-infra/tests/conftest.py
Labels: approved, lgtm

#731 NO-ISSUE - Replace LibvirtController calls with cls inside LibvirtCon…
  discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
Labels: approved, lgtm

#729 Adding wait for cluster status
  discovery-infra/test_infra/helper_classes/cluster.py
Labels: approved, lgtm

#734 MGMT-5360 - remove support for mirror registry configuration from the…
  discovery-infra/test_infra/assisted_service_api.py
Labels: approved, lgtm

#724 MGMT-3879 Update ClusterDeployment conditions
  discovery-infra/install_cluster.py
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/helper_classes/kube_helpers/__init__.py
  discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py
  discovery-infra/test_infra/helper_classes/kube_helpers/global_vars.py
Labels: approved, lgtm

#735 NO-ISSUE - Move PROXY_USER and PROXY_USER_PASS to class scope
  discovery-infra/test_infra/controllers/proxy_controller/proxy_controller.py
Labels: approved, lgtm

#733 MGMT-5275 - Fix NodeController.list_nodes to return List[Node]
  discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
  discovery-infra/test_infra/controllers/node_controllers/node_controller.py
  discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
  discovery-infra/test_infra/helper_classes/nodes.py
Labels: approved, lgtm

#738 NO ISSUE: Allow to set CNV operator at cluster level.
  discovery-infra/test_infra/helper_classes/cluster.py
Labels: approved, lgtm, needs-ok-to-test

#740 MGMT-4577 kube_api: use 4.8 release image
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/utils.py
Labels: approved, lgtm

#649 NO-ISSUE fix typo of metadata file name
  discovery-infra/download_logs.py
Labels: approved, lgtm

#732 NO-ISSUE add feature_usage to elastic enrichment
  discovery-infra/monitoring/process.py
Labels: approved, lgtm

#742 Remove some unnecessary debug prints
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/assisted_service_api.py
  discovery-infra/test_infra/utils.py
Labels: approved, lgtm

#723 MGMT-4986 remove all environment variables from the interior test infra package
  discovery-infra/download_logs.py
  discovery-infra/install_cluster.py
  discovery-infra/test_infra/consts.py
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/helper_classes/config/__init__.py
  discovery-infra/test_infra/helper_classes/config/base_config.py
  discovery-infra/test_infra/helper_classes/config/cluster_config.py
  discovery-infra/test_infra/helper_classes/config/nodes_config.py
  discovery-infra/test_infra/helper_classes/nodes.py
  discovery-infra/tests/base_test.py
  discovery-infra/tests/config/__init__.py
  discovery-infra/tests/config/env_config.py
  discovery-infra/tests/config/global_configs.py
  discovery-infra/tests/conftest.py
  discovery-infra/tests/test_install.py
Labels: approved, lgtm

#745 Unpack enumerate for hosts_in_error
  discovery-infra/test_infra/utils.py
Labels: approved, lgtm

#739 NO ISSUE: Allow to retrieve requirements per host
  discovery-infra/test_infra/assisted_service_api.py
Labels: approved, lgtm, needs-ok-to-test

#743 MGMT-5411 - Refactor operator resource consts
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/consts/__init__.py
  discovery-infra/test_infra/consts/consts.py
  discovery-infra/test_infra/consts/olm_operators.py
  discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/utils.py
Labels: approved, lgtm

#741 NO-ISSUE add gamli75 to OWNERS
  OWNERS
Labels: approved, lgtm

#748 NO-ISSUE - Remove redundant ssh key on iptables fixture set_iptables_rules_for_nodes
  discovery-infra/tests/base_test.py
Labels: approved, lgtm

#730 MGMT-4792 LSO support
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/consts/olm_operators.py
  discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
Labels: approved, lgtm

#750 NO-ISSUE Increase max events passed to monitoring to max 5000
  discovery-infra/log_scrap.py
Labels: approved, lgtm

#749 MGMT-5381 gather sosreport from nodes
  discovery-infra/bootstrap_in_place.py
  discovery-infra/download_logs.py
  discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
  discovery-infra/test_infra/utils.py
Labels: approved, lgtm

#753 NO-ISSUE fix gathering sosreport on ibip flow
  discovery-infra/bootstrap_in_place.py
  discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
Labels: approved, lgtm
