Repository openshift/assisted-test-infra, pull requests merged in 2021-07, with the labels that each got.

#931 NO-ISSUE - Fix SNO lack of ram and cpu
  discovery-infra/test_infra/consts/resources.py
  discovery-infra/test_infra/utils/global_variables/global_variables.py
Labels: approved, lgtm

#932 MGMT-7124: Update API VIP in pytest flow when using vip DHCP
  discovery-infra/test_infra/helper_classes/cluster.py
Labels: approved, lgtm

#930 NO-ISSUE - Remove duplicate allocation of proxy server url
  discovery-infra/test_infra/controllers/proxy_controller/proxy_controller.py
  discovery-infra/tests/base_test.py
Labels: approved, lgtm

#933 Fix path for nginx config files
  Makefile
  scripts/install_environment.sh
Labels: approved, lgtm

#935 NO-ISSUE - Add log on prepare_for_installation
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/helper_classes/nodes.py
Labels: approved, lgtm

#934 NO-ISSUE: Check agent's RequirementsMet condition
  discovery-infra/test_infra/consts/consts.py
  discovery-infra/test_infra/helper_classes/kube_helpers/agent.py
Labels: approved, lgtm

#936 Delete iso as part of node teardown
  discovery-infra/tests/base_test.py
Labels: approved, lgtm

#943 MGMT-7151 - Fix logs to use SensitiveFormatter on cluster.
  discovery-infra/logger.py
  discovery-infra/test_infra/helper_classes/cluster.py
Labels: approved, lgtm

#908 MGMT-7060 - Move cluster name to cluster config scope
  discovery-infra/bootstrap_in_place.py
  discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/helper_classes/config/base_config.py
  discovery-infra/test_infra/helper_classes/config/nodes_config.py
  discovery-infra/test_infra/utils/cluster_name.py
  discovery-infra/test_infra/utils/global_variables/env_variables_utils.py
  discovery-infra/tests/base_test.py
  discovery-infra/tests/config/__init__.py
  discovery-infra/tests/config/global_configs.py
  discovery-infra/tests/test_e2e_install.py
  discovery-infra/tests/test_kube_api.py
Labels: approved, lgtm

#941 NO-ISSUE - Fix proxy to support ipv4 addresses
  discovery-infra/test_infra/controllers/proxy_controller/proxy_controller.py
  discovery-infra/tests/base_test.py
Labels: approved, lgtm

#942 MGMT-7155: ignore SCPException when sosreport gathering fails
  discovery-infra/download_logs.py
Labels: approved, lgtm

#944 MGMT-7156: Set DNS configuration for single node pytest flow
  discovery-infra/test_infra/helper_classes/cluster.py
Labels: approved, lgtm

#912 MGMT-7071 - Fix PEP8 violations on utils
  discovery-infra/test_infra/utils/__init__.py
  discovery-infra/test_infra/utils/global_variables/__init__.py
  discovery-infra/test_infra/utils/global_variables/env_variables_utils.py
  discovery-infra/test_infra/utils/global_variables/global_variables.py
  discovery-infra/test_infra/utils/kubeapi_utils.py
  discovery-infra/test_infra/utils/logs_utils.py
  discovery-infra/test_infra/utils/operators_utils.py
  discovery-infra/test_infra/utils/utils.py
Labels: approved, lgtm, size/L

#946 NO-ISSUE: Fix DNS setting for IPv6 flow
  discovery-infra/test_infra/helper_classes/cluster.py
Labels: approved, lgtm, size/XS

#947 NO-ISSUE: add colors for critical level event
  discovery-infra/events.html
Labels: approved, lgtm, size/XS

#910 NO-ISSUE: Support oVirt on ansible collections
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/boot_iso/tasks/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/boot_iso/tasks/ovirt.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/clean/defaults/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/clean/meta/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/clean/tasks/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/clean/tasks/ovirt.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/host_iso/tasks/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/host_iso/tasks/ovirt.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/validations/tasks/main.yml
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/validations/tasks/ovirt.yml
  ansible-bm-install/inventory/hosts_without_os.sample
  ansible-bm-install/requirements.yml
Labels: approved, lgtm, ok-to-test

#948 MGMT-7202: Collect custom manifests yaml when downloading cluster logs
  discovery-infra/download_logs.py
Labels: approved, lgtm, size/XS

#955 NO-ISSUE: Organize README parameters table
  README.md
Labels: approved, lgtm, size/L

#954 MGMT-6664: Merge PR commit for assisted-service and assisted-installer
  Makefile
  skipper.env
Labels: approved, lgtm, size/S

#945 Support SNO in update_oc_config
  discovery-infra/tests/base_test.py
Labels: approved, lgtm, size/XS

#957 Update dependabot.yml to support docker as well
  .github/dependabot.yml
Labels: approved, lgtm, size/XS

#958 Adding vsphere terraform
  Dockerfile.test-infra
  discovery-infra/test_infra/tools/terraform_utils.py
  discovery-infra/test_infra/utils/global_variables/env_variables_utils.py
  requirements.txt
  skipper.env
  terraform_files/baremetal/main.tf
  terraform_files/none/main.tf
  terraform_files/vsphere/main.tf
  terraform_files/vsphere/terraform.tfvars.json
  terraform_files/vsphere/variables-vsphere.tf
Labels: approved, lgtm, size/L

#959 MGMT-6480 remove get_host_requirements
  discovery-infra/test_infra/assisted_service_api.py
Labels: approved, lgtm, size/XS

#962 Set fixed versions on requirements.txt
  requirements.txt
Labels: approved, size/M

#963 Update dependabot.yml
  .github/dependabot.yml
Labels: approved, size/XS

#968 Avoid libvirt error during disks teardown
  discovery-infra/tests/base_test.py
Labels: approved, lgtm, size/XS

#971 Delete test dummy
  discovery-infra/tests/test_e2e_install.py
Labels: approved, lgtm, size/XS

#970 MGMT-7289 - Change basePath in python client
  discovery-infra/test_infra/assisted_service_api.py
Labels: approved, lgtm, size/XS

#973 MGMT-7293 Add networkType as cluster create params
  discovery-infra/test_infra/consts/env_defaults.py
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/helper_classes/config/cluster_config.py
  discovery-infra/test_infra/utils/global_variables/env_variables_utils.py
Labels: approved, lgtm, size/XS

#960 MGMT-7153 support multi-platform test
  discovery-infra/bootstrap_in_place.py
  discovery-infra/download_logs.py
  discovery-infra/test_infra/consts/consts.py
  discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
  discovery-infra/test_infra/controllers/node_controllers/node_controller.py
  discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/helper_classes/config/cluster_config.py
  discovery-infra/test_infra/helper_classes/config/controller_config.py
  discovery-infra/test_infra/helper_classes/config/nodes_config.py
  discovery-infra/test_infra/helper_classes/nodes.py
  discovery-infra/test_infra/utils/global_variables/global_variables.py
  discovery-infra/test_infra/utils/terraform_util.py
  discovery-infra/test_infra/utils/utils.py
  discovery-infra/tests/base_test.py
  discovery-infra/tests/config/__init__.py
  discovery-infra/tests/config/global_configs.py
  discovery-infra/tests/conftest.py
  discovery-infra/tests/test_e2e_install.py
Labels: approved, lgtm, size/XL

#972 MGMT-7291: Collect degraded clusters
  discovery-infra/download_logs.py
Labels: approved, lgtm, size/XS

#975 NO-ISSUE controller config doesn't contain base_dns_domain anymore
  discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
Labels: approved, lgtm, size/XS

#976 MGMT-7298: retry creating minikube with the registry addon
  scripts/run_minikube.sh
Labels: approved, lgtm, size/XS

#979 Fixing ipv6 tests issues: node.macs is an attribute, and pass reques…
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/helper_classes/config/cluster_config.py
  discovery-infra/test_infra/utils/global_variables/env_variables_utils.py
  discovery-infra/tests/base_test.py
Labels: approved, lgtm, size/S

#980 Fix libvirt error
  discovery-infra/tests/base_test.py
Labels: approved, lgtm, size/XS

#961 MGMT-7153 adding vsphere controller
  discovery-infra/logger.py
  discovery-infra/test_infra/controllers/node_controllers/__init__.py
  discovery-infra/test_infra/controllers/node_controllers/node_controller.py
  discovery-infra/test_infra/controllers/node_controllers/vsphere_controller.py
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/helper_classes/config/vsphere_config.py
  discovery-infra/test_infra/helper_classes/nodes.py
  discovery-infra/test_infra/tools/terraform_utils.py
  discovery-infra/tests/base_test.py
  requirements.txt
Labels: approved, lgtm, size/L

#981 NO-ISSUE - Improve the way of setting the API host address
  discovery-infra/test_infra/assisted_service_api.py
Labels: approved, lgtm, size/XS

#983 NO-ISSUE - Fix API client not supporting https inventory url
  discovery-infra/test_infra/assisted_service_api.py
Labels: approved, lgtm, size/XS

#982 Remove tf plugins
  Dockerfile.test-infra
Labels: approved, lgtm, size/XS

#986 Replace FETCH_BASE with FETCH_NEW
  Makefile
Labels: approved, lgtm, size/XS

#984 Mgmt 7153 vsphere platform configure networking
  discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
  discovery-infra/test_infra/controllers/node_controllers/node_controller.py
  discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
  discovery-infra/test_infra/controllers/node_controllers/vsphere_controller.py
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/helper_classes/cluster_host.py
  discovery-infra/test_infra/helper_classes/nodes.py
  discovery-infra/test_infra/utils/global_variables/global_variables.py
  discovery-infra/test_infra/utils/network_utils.py
  discovery-infra/tests/base_test.py
  discovery-infra/tests/test_kube_api.py
Labels: approved, lgtm, size/L

#989 Revert "Replace FETCH_BASE with FETCH_NEW"
  Makefile
Labels: approved, size/XS

#987 Use default ssh keys for SSH connections
  GUIDE.md
  Makefile
  README.md
  discovery-infra/bootstrap_in_place.py
  discovery-infra/test_infra/consts/__init__.py
  discovery-infra/test_infra/consts/consts.py
  discovery-infra/test_infra/consts/env_defaults.py
  scripts/install_environment.sh
  ssh_key/key
  ssh_key/key.pub
Labels: approved, lgtm, size/M

#990 MGMT-6417- Add pytest deploy_nodes target
  discovery-infra/tests/base_test.py
  discovery-infra/tests/test_targets.py
Labels: approved, lgtm, size/S

#992 Move from log.warn to log.warning
  discovery-infra/download_logs.py
  discovery-infra/log_scrap.py
  discovery-infra/monitoring/process.py
  discovery-infra/test_infra/utils/utils.py
Labels: approved, lgtm, size/S

#993 MGMT-7153-4 cluster.get_cluster_host should recieve a model cluster n…
  discovery-infra/test_infra/helper_classes/cluster.py
Labels: approved, lgtm, size/XS

#999 NO-ISSUE - Rename target tests names
  discovery-infra/tests/test_targets.py
Labels: approved, lgtm, size/XS

#997 Handle libvirt logs do not exist
  discovery-infra/tests/base_test.py
Labels: approved, lgtm, size/S

#1000 MGMT-4492: Removing WITH_AMS_SUBSCRIPTIONS env variable.
  README.md
  scripts/deploy_assisted_service.sh
  skipper.env
Labels: approved, lgtm, size/XS

#1001 NO-ISSUE - Bump default openshift version to 4.8
  discovery-infra/test_infra/consts/consts.py
Labels: approved, lgtm, size/XS

#1002 Add kube-api mark to pytest markers list
  discovery-infra/tests/pytest.ini
Labels: approved, lgtm, size/XS

#1003 NO-ISSUE - Fix single openshift version when running without specific openshift version
  discovery-infra/tests/conftest.py
Labels: approved, lgtm, size/XS

#1004 NO-ISSUE: fix for None platform CI
  discovery-infra/test_infra/helper_classes/cluster.py
Labels: approved, lgtm, size/S
