Repository openshift/assisted-test-infra, pull requests merged in 2021-03, with the labels that each got.

#565 NOISSUE - kube_helpers.py: fixed kubeapi ClusterDeployment patch func…
  discovery-infra/test_infra/helper_classes/kube_helpers.py
Labels: approved, lgtm

#570 MGMT-4340 change default OCP version in test-infra from 4.6 to 4.7
  GUIDE.md
  README.md
  discovery-infra/test_infra/consts.py
  discovery-infra/test_infra/helper_classes/cluster.py
Labels: approved, lgtm

#571 MGMT-2708 - Break installing if cluster has Error status
  discovery-infra/install_cluster.py
  discovery-infra/test_infra/utils.py
Labels: approved, lgtm

#572 Moving wait_and_kill_installer into Cluster for shared use
  discovery-infra/test_infra/helper_classes/cluster.py
Labels: approved, lgtm

#575 NOISSUE - aligned Secret CRD with updated pull secret key
  discovery-infra/test_infra/helper_classes/kube_helpers.py
Labels: approved, lgtm

#576 NOISSUE - kube_helpers.py: added Secret crd type
  discovery-infra/test_infra/helper_classes/kube_helpers.py
Labels: approved, lgtm

#564 MGMT-4091 - change test-infra to work with static network configurati…
  Makefile
  discovery-infra/day2.py
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/assisted_service_api.py
  discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/tools/static_ips.py
  discovery-infra/test_infra/tools/static_network.py
Labels: approved, lgtm

#573 Disable attach_disk teardown
  discovery-infra/tests/base_test.py
Labels: approved, lgtm

#578 NO-ISSUE - Log output from bip installer gather
  discovery-infra/bootstrap_in_place.py
Labels: approved, lgtm

#580 MGMT-4274 Use AUTH_TYPE flag over ENABLE_AUTH
  README.md
  scripts/deploy_assisted_service.sh
  skipper.env
Labels: approved, lgtm

#583 NO-ISSUE: save events of each relevant pod on a separate file
  Dockerfile.test-infra
  scripts/download_logs.sh
Labels: approved, lgtm

#589 NO-ISSUE fix sporadic read error in CI when opening controller tar
  discovery-infra/test_infra/logs_utils.py
Labels: approved, lgtm

#581 MGMT-4079 Set CNV
  discovery-infra/test_infra/helper_classes/cluster.py
Labels: approved, lgtm

#584 When download must-gather logs, raise error in case of failure
  discovery-infra/download_logs.py
Labels: approved, lgtm

#582 Fixing route destitation for ipv6 static network configuration flow
  discovery-infra/test_infra/tools/static_network.py
Labels: approved, lgtm

#592 Mount minikube, oc and kubectl instead of being part of image
  Dockerfile.test-infra
  skipper.yaml
Labels: approved, lgtm

#593 Update config_etc_hosts log to info about the record domain and ip
  discovery-infra/test_infra/utils.py
Labels: approved, lgtm

#595 Remove hourly cron trigger from Jenkinsfile
  Jenkinsfile
Labels: approved, lgtm

#594 Remove --must-gather flag on Jenkinsfile.download_logs
  Jenkinsfile.download_logs
Labels: approved, lgtm

#591 NO-ISSUE increase wait for must-gather in download_logs
  Jenkinsfile.download_logs
  discovery-infra/download_logs.py
Labels: approved, lgtm

#596 not prepending 'http://' to URLs that already include a scheme
  discovery-infra/test_infra/assisted_service_api.py
Labels: approved, lgtm

#432 MGMT-3463 collect full journal logs on error
  discovery-infra/test_infra/logs_utils.py
Labels: approved, lgtm

#602 Revert "MGMT-3463 collect full journal logs on error"
  discovery-infra/test_infra/logs_utils.py
Labels: approved, lgtm

#603 MGMT-4472 - update test infra to use the new REST API for static netw…
  discovery-infra/test_infra/tools/static_network.py
Labels: approved, lgtm

#579 MGMT-4077 Refactor OCS test to new monitoring API
  discovery-infra/test_infra/helper_classes/cluster.py
Labels: approved, lgtm

#606 MGMT-4373 Persistent attach of disks
  discovery-infra/test_infra/controllers/node_controllers/libvirt_controller.py
  discovery-infra/test_infra/controllers/node_controllers/node.py
  discovery-infra/test_infra/controllers/node_controllers/node_controller.py
  discovery-infra/tests/base_test.py
Labels: approved, lgtm

#605 NO-ISSUE Fix Terraform warning about undeclared vars
  terraform_files/baremetal/variables-libvirt.tf
Labels: approved, lgtm

#600 MGMT-3420 None platform additional changes
  Makefile
  discovery-infra/delete_nodes.py
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/controllers/load_balancer_controller.py
  discovery-infra/test_infra/controllers/nat_controller.py
  discovery-infra/test_infra/helper_classes/cluster.py
  scripts/install_environment.sh
  terraform_files/none/main.tf
Labels: approved, lgtm

#604 MGMT-3550 Enable IPv6 in test environments
  Makefile
  skipper.env
Labels: approved, lgtm

#609 NO-ISSUE - Bootstrap-in-place node with more resources
  discovery-infra/bootstrap_in_place.py
Labels: approved, lgtm

#590 MGMT 3854 - e2e test to log info
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/logs_utils.py
  discovery-infra/test_infra/utils.py
Labels: approved, lgtm

#601 MGMT-4079 set olm_operators during cluster creation
  discovery-infra/test_infra/consts.py
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/tests/base_test.py
  discovery-infra/tests/conftest.py
Labels: approved, lgtm

#608 MGMT-4360 - update day2 workflow to allow static network configuration
  Makefile
  discovery-infra/day2.py
  discovery-infra/test_infra/tools/static_network.py
Labels: approved, lgtm

#574 MGMT-4152 log collection script
  Makefile
  discovery-infra/log_scrap.py
  discovery-infra/monitoring/__init__.py
  discovery-infra/monitoring/docker-compose.yml
  discovery-infra/monitoring/process.py
  requirements.txt
  skipper.env
  skipper.yaml
Labels: approved, lgtm

#614 Suppress and log in case of downloading cluster files fails
  discovery-infra/download_logs.py
Labels: approved, lgtm

#599 Add support for writing Day2 API tests
  discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/helper_classes/nodes.py
  discovery-infra/test_infra/tools/terraform_utils.py
  discovery-infra/tests/conftest.py
Labels: approved, lgtm, ok-to-test

#616 MGMT-4624: Added Agent CRD
  discovery-infra/test_infra/helper_classes/kube_helpers.py
Labels: approved, lgtm

#618 Fix detach_all_test_disks during teardown
  discovery-infra/tests/base_test.py
Labels: approved, lgtm

#619 NO-ISSUE Transfer assisted-installer-deployment repo under openshift-assisted org
  Jenkinsfile.download_logs
Labels: approved, lgtm

#607 MGMT-3335 - Add None Platform support
  Makefile
  discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/tests/conftest.py
Labels: approved, lgtm

#622 Add colors to the log level column in events file
  discovery-infra/events.html
Labels: approved, lgtm

#621 NO-ISSUE: split kube helpers file
  discovery-infra/test_infra/helper_classes/kube_helpers/__init__.py
  discovery-infra/test_infra/helper_classes/kube_helpers/agent.py
  discovery-infra/test_infra/helper_classes/kube_helpers/base_resource.py
  discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py
  discovery-infra/test_infra/helper_classes/kube_helpers/common.py
  discovery-infra/test_infra/helper_classes/kube_helpers/secret.py
Labels: approved, lgtm

#620 NO-ISSUE: run CI in kube-api mode for e2e tests
  Jenkinsfile
Labels: approved, lgtm

#624 MGMT-4683 Fix Jenkinsfile skipper directory
  Jenkinsfile.download_logs
Labels: approved

#623 Added call to create_testgrid_tickets.py to the download_logs job
  Jenkinsfile.download_logs
Labels: approved, lgtm

#628 Fix OLM_OPERATORS env var to support multiple values space-separated
  discovery-infra/tests/conftest.py
  skipper.env
Labels: approved, lgtm

#630 NO-ISSUE: Added KubeAPIContext
  discovery-infra/test_infra/helper_classes/kube_helpers/__init__.py
  discovery-infra/test_infra/helper_classes/kube_helpers/agent.py
  discovery-infra/test_infra/helper_classes/kube_helpers/base_resource.py
  discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py
  discovery-infra/test_infra/helper_classes/kube_helpers/common.py
  discovery-infra/test_infra/helper_classes/kube_helpers/secret.py
  discovery-infra/tests/base_test.py
Labels: approved, lgtm

#631 MGMT-3335 - Add START_LOAD_BALANCER env var for starting the load bal…
  Makefile
Labels: approved, lgtm

#633 MGMT-4604 Fix scality ephemeral storage error
  scripts/run_minikube.sh
Labels: approved, lgtm

#634 NO-JIRA Add ori-amizur to OWNERS file
  OWNERS
Labels: approved, lgtm

#636 MGMT-3334 Wait for operators to finish
  discovery-infra/install_cluster.py
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/assisted_service_api.py
  discovery-infra/test_infra/consts.py
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/utils.py
  discovery-infra/tests/conftest.py
Labels: approved, lgtm

#627 MGMT-4342: Added InstallEnv CRD infra
  discovery-infra/test_infra/helper_classes/kube_helpers/__init__.py
  discovery-infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py
  discovery-infra/test_infra/helper_classes/kube_helpers/common.py
  discovery-infra/test_infra/helper_classes/kube_helpers/global_vars.py
  discovery-infra/test_infra/helper_classes/kube_helpers/installenv.py
Labels: approved, lgtm

#643 Run minikube tunnel when starting minikube
  scripts/run_minikube.sh
Labels: approved, lgtm

#638 NOISSUE: Updated skipper to v1.29.2
  scripts/install_environment.sh
  skipper.yaml
Labels: approved, lgtm

#644 NOISSUE: kube-api get kubeconfig path from env
  discovery-infra/test_infra/helper_classes/kube_helpers/common.py
Labels: approved, lgtm

#646 NO-ISSUE Change user password to full param
  Jenkinsfile.download_logs
Labels: approved, lgtm

#637 MGMT-4761 Clear all nat iptables rules when tearing down tests using user-managed-networking
  Makefile
  discovery-infra/delete_nodes.py
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/controllers/nat_controller.py
  discovery-infra/test_infra/helper_classes/cluster.py
Labels: approved, lgtm

#648 Support SHAs for SERVICE_BRANCH and INSTALLER_BRANCH
  Makefile
Labels: approved, lgtm

#652 Set TEST_WORKERS_NUM default to 3 for test_parallel
  Makefile
Labels: approved, lgtm

#653 MGMT-4813: If not provided, use INSTALLER_KUBECONFIG env
  discovery-infra/test_infra/helper_classes/kube_helpers/common.py
  discovery-infra/tests/conftest.py
  skipper.env
Labels: approved, lgtm

#650 Bugfix get cluster operators to avoid agentAuth
  discovery-infra/test_infra/assisted_service_api.py
  discovery-infra/test_infra/utils.py
Labels: approved, lgtm
