Repository openshift/assisted-test-infra, pull requests merged in 2021-12, with the labels that each got.

#1269 Use container command variable
  Makefile
Labels: approved, size/XS, lgtm

#1270 MGMT-8389 - Fix download_logs host ignition failed to download
  discovery-infra/download_logs.py
Labels: approved, size/XS, lgtm

#1271 NO-ISSUE: fix container id evaluation in start/stop load_balancer
  Makefile
Labels: approved, size/XS, lgtm

#1273 remove load-balancer container even if it stopped
  Makefile
Labels: approved, size/XS, lgtm

#1274 add a new parameter for setting assisted-installer-deployment branch
  Jenkinsfile.download_logs
Labels: approved, size/XS, lgtm

#1275 MGMT-8411 - Allow download ISO without ssl verification on test-infra
  discovery-infra/test_infra/consts/env_defaults.py
  discovery-infra/test_infra/helper_classes/config/base_infra_env_config.py
  discovery-infra/test_infra/helper_classes/infra_env.py
  discovery-infra/test_infra/utils/global_variables/env_variables_defaults.py
  discovery-infra/test_infra/utils/utils.py
  discovery-infra/tests/test_day2.py
  skipper.env
Labels: size/S, approved, lgtm

#1277 Use access-token when accessing Jira on Jenkins
  Jenkinsfile.download_logs
Labels: approved, size/XS, lgtm

#1254 MGMT-7920: enable testing TPM disk encryption mode
  Dockerfile.test-infra
  README.md
  discovery-infra/test_infra/consts/consts.py
  discovery-infra/test_infra/consts/env_defaults.py
  discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/helper_classes/config/cluster_config.py
  discovery-infra/test_infra/utils/global_variables/env_variables_defaults.py
  scripts/install_environment.sh
  skipper.env
  terraform_files/baremetal/main.tf
  terraform_files/baremetal/variables-libvirt.tf
  terraform_files/baremetal_host/main.tf
  terraform_files/baremetal_host/variables.tf
  terraform_files/baremetal_infra_env/main.tf
  terraform_files/baremetal_infra_env/variables-libvirt.tf
  terraform_files/none/main.tf
  terraform_files/none/variables-libvirt.tf
Labels: size/L, approved, lgtm

#1285 NO-ISSUE: Retry to download minikube in case of failure
  scripts/install_minikube.sh
Labels: size/S, approved, lgtm

#1284 NO-ISSUE: Install Golang when setting up capi-provider env
  scripts/install_golang.sh
  scripts/setup_capi_provider_agent_env.sh
Labels: size/M, approved, lgtm

#1287 NO-ISSUE: updated setup_capi_provider_agent_env BASE_DIR to build
  discovery-infra/test_infra/helper_classes/hypershift.py
  scripts/setup_capi_provider_agent_env.sh
Labels: size/S, approved, lgtm

#1291 NO-ISSUE - Tip users to run `make lint` on linter errors
  Makefile
Labels: approved, size/XS, lgtm

#1292 MGMT-8300: Apply dual-stack configuration in a single step
  discovery-infra/test_infra/helper_classes/cluster.py
Labels: approved, size/XS, lgtm

#1293 NO-ISSUE: updated the capi test
  discovery-infra/test_infra/helper_classes/hypershift.py
  discovery-infra/tests/test_kube_api.py
Labels: size/S, approved, lgtm

#1296 MGMT-8529 - Raise exception on ISO download failure
  discovery-infra/test_infra/utils/utils.py
Labels: approved, size/XS, lgtm

#1300 added default value to wait_for_nodes ready param
  discovery-infra/test_infra/helper_classes/hypershift.py
Labels: approved, size/XS, lgtm

#1301 Added eranco74 to OWNERS
  OWNERS
Labels: approved, size/XS, lgtm

#1302 MGMT-8564: Rename the UI deployment template
  Makefile
  scripts/deploy_ui.sh
  scripts/test_ui.sh
Labels: approved, size/XS, lgtm

#1305 NO-ISSUE - Fix failing download_logs job due to unbound PYTHONPATH
  scripts/utils.sh
Labels: approved, size/XS, lgtm

#1306 NO-ISSUE - Remove project path dependency from CI
  Makefile
Labels: approved, size/XS, lgtm

#1304 NO-ISSUE - Delete unused github workflow
  .github/workflows/pre-commit.yml
Labels: size/S, approved, lgtm

#1299 MGMT-8549- Fix missing junit files on kube api tests
  Makefile
Labels: approved, size/XS, lgtm

#1310 NO-ISSUE - Fix arkade not found in PATH on some machines. Add /usr/local/bin to PATH.
  Makefile
  scripts/utils.sh
Labels: size/S, approved, lgtm

#1311 NO-ISSUE: wait_for_nodes should pass the ready option to the get_nodes method
  src/assisted_test_infra/test_infra/helper_classes/hypershift.py
Labels: approved, size/XS, lgtm

#1314 NO-ISSUE - Fix redundant quotes on PYTHONPATH and PATH causing jobs to fail
  Makefile
Labels: approved, size/XS, lgtm

#1286 MGMT-8100: e2e test for late unbind
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/agent.py
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/agent_cluster_install.py
  src/consts/consts.py
  src/tests/test_kube_api.py
Labels: size/M, approved, lgtm

#1313 MGMT-8598: fix provided variables for onprem deploy target
  Makefile
  scripts/deploy_assisted_service.sh
  scripts/download_logs.sh
Labels: size/S, approved, lgtm

#1323 MGMT-8660: Fix os image override script
  scripts/override_os_images.py
Labels: approved, size/XS, lgtm

#1282 MGMT-7230: Add ODF operator in the operatorType
  src/consts/consts.py
  src/consts/olm_operators.py
Labels: approved, size/XS, lgtm

#1324 NO-ISSUE: remove dnf update
  scripts/install_environment.sh
Labels: approved, size/XS, lgtm

#1325 Go back to using upstream terraform-libvirt-provider
  terraform_files/baremetal/main.tf
  terraform_files/baremetal_host/main.tf
  terraform_files/baremetal_infra_env/main.tf
  terraform_files/none/main.tf
Labels: size/M, approved, lgtm

#1326 MGMT-8602: Updated capi test to add 2 worker nodes
  src/assisted_test_infra/test_infra/helper_classes/hypershift.py
  src/tests/test_kube_api.py
Labels: size/M, approved, lgtm

#1327 MGMT-8680: Update assisted-test-infra to default to Openshift org CAPI repo and image
  scripts/setup_capi_provider_agent_env.sh
  skipper.env
Labels: size/S, approved, lgtm

#1330 allow gathering from the new name of assisted-service container
  scripts/download_logs.sh
Labels: approved, size/XS, lgtm

#1315 MGMT-8423: remove hack for disable day2 validation
  README.md
Labels: approved, size/XS, lgtm

#1331 NO-ISSUE: checkout_branch should refer to the branch name in origin
  scripts/setup_capi_provider_agent_env.sh
Labels: size/S, approved, lgtm

#1332 NO-ISSUE: Get minikube logs in case it failed to start properly
  scripts/run_minikube.sh
Labels: approved, size/XS, lgtm

#1333 NO-ISSUE: don't fail the run_minikube script in case of failure to get the logs
  scripts/run_minikube.sh
Labels: approved, size/XS, lgtm

#1339 Fixing none-platform network interfaces
  terraform_files/baremetal/main.tf
  terraform_files/baremetal_host/main.tf
  terraform_files/baremetal_host/variables.tf
  terraform_files/baremetal_infra_env/main.tf
  terraform_files/none/main.tf
  terraform_files/none/variables-libvirt.tf
Labels: size/L, approved, lgtm

#1340 MGMT-8705: Collect capi-provider-agent logs
  Makefile
  scripts/download_logs.sh
Labels: size/M, approved, lgtm

#1329 MGMT-7555 - Fix `make destroy_nodes` isn't working
  Makefile
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/delete_nodes.py
  src/deprecated_utils.py
  src/service_client/client_factory.py
  src/virsh_cleanup.py
  src/virsh_cleanup/__init__.py
  src/virsh_cleanup/__main__.py
  src/virsh_cleanup/virsh_cleanup.py
Labels: size/L, approved, lgtm
