Repository openshift/assisted-test-infra, pull requests merged in 2021-08, with the labels that each got.

#985 Create post-install script for IBM Cloud machines
  scripts/ibmcloud_post_install.sh
  scripts/install_environment.sh
Labels: approved, lgtm, size/M

#1008 Update CVO event message
  discovery-infra/test_infra/consts/consts.py
Labels: approved, lgtm, size/XS

#1014 NO-ISSUE: Update chmod command to the new script location
  scripts/ibmcloud_post_install.sh
Labels: approved, lgtm, size/S

#988 Supporting modifying the configuration objects by custom fixtures
  discovery-infra/test_infra/utils/utils.py
  discovery-infra/tests/base_test.py
  discovery-infra/tests/test_e2e_install.py
Labels: approved, lgtm, size/M

#1016 Revert "Bump junit-report from 0.1.24 to 0.1.32 (#1013)"
  requirements.txt
Labels: approved, lgtm, size/XS

#1017 Update deploy_nodes makefile target to use the new pytest workflow
  Makefile
Labels: approved, size/XS, lgtm

#1025 NO-ISSUE: Removed some minikube configurations.
  scripts/run_minikube.sh
Labels: approved, size/XS, lgtm

#1026 NO-ISSUE: adjust wait for controller interval
  discovery-infra/tests/base_test.py
Labels: approved, size/XS, lgtm

#1027 Update agent api calls to use v2_* according to swagger
  discovery-infra/test_infra/assisted_service_api.py
Labels: size/S, approved, lgtm

#1029 MGMT-7474 - Add download_logs junit report
  Makefile
  discovery-infra/download_logs.py
  scripts/download_logs.sh
  skipper.env
Labels: size/M, approved, lgtm

#1031 MGMT-6739 - Remove duplicate variables from configurations objects
  discovery-infra/test_infra/controllers/node_controllers/node_controller.py
  discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/helper_classes/config/cluster_config.py
  discovery-infra/test_infra/helper_classes/config/controller_config.py
  discovery-infra/test_infra/helper_classes/nodes.py
  discovery-infra/tests/base_test.py
  discovery-infra/tests/test_kube_api.py
Labels: size/M, approved, lgtm

#1032 NO-ISSUE - Fix download_logs report classname is __main__
  requirements.txt
Labels: approved, lgtm

#1033 MGMT-6897: Set multiple networks fields
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/tests/base_test.py
Labels: size/S, approved, lgtm

#1035 MGMT-7571: Attach download logs directory with python logs
  discovery-infra/download_logs.py
  discovery-infra/logger.py
Labels: size/M, approved, lgtm

#1040 Add CI env var to skipper.env
  skipper.env
Labels: approved, size/XS, lgtm

#1039 MGMT-7577: Retry must-gather collection also when hosts are in Done state
  discovery-infra/download_logs.py
Labels: approved, size/XS, lgtm

#1018 Added INSTALLATION_TIMEOUT to skipper.env
  skipper.env
Labels: approved, size/XS, lgtm

#1041 NO-ISSUE - Fix missing nodes prevent creating cluster on some cases
  discovery-infra/tests/base_test.py
Labels: approved, size/XS, lgtm

#1043 MGMT-7590 - Replace the old deploy_nodes_with_install Makefile target with a new logic using pytest
  Makefile
  skipper.env
Labels: size/S, approved, lgtm

#1045 MGMT-7597: Remove ronniel1, and razregev from OWNERS
  OWNERS
Labels: approved, size/XS, lgtm

#1046 NO-ISSUE: raise an error for only relevant error codes
  discovery-infra/test_infra/assisted_service_api.py
Labels: approved, size/XS, lgtm

#1048 NO-ISSUE: catch also HTTPError when metrics endpoint is not accessible
  discovery-infra/download_logs.py
Labels: approved, size/XS, lgtm

#1047 Fixing destroy_nodes , none platform deploy_node and adding console to none platform vms
  discovery-infra/delete_nodes.py
  discovery-infra/tests/base_test.py
  scripts/install_environment.sh
  terraform_files/none/consolemodel.xsl
  terraform_files/none/main.tf
Labels: size/M, approved, lgtm

#1056 Add lranjbar to OWNERS file
  OWNERS
Labels: approved, size/XS, lgtm

#1055 NO-ISSUE: Fix pip not upgrading correctly in image build
  Dockerfile.test-infra
Labels: approved, size/XS, lgtm

#1054 Adding wait for specific host stage
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/utils/utils.py
Labels: size/M, approved, lgtm

#1061 NO-ISSUE: fix keyword argument of Controller c'tor
  discovery-infra/download_logs.py
Labels: approved, size/XS, lgtm

#1063 Merge Jenkinsfile.download_logs create tickets commands under a single stage
  Jenkinsfile.download_logs
Labels: size/S, approved, lgtm

#1062 Update rhcos-live-iso version to 4.8.2 and add retry
  discovery-infra/bootstrap_in_place.py
Labels: approved, size/XS, lgtm

#1065 NO-ISSUE: Removed --retry-all-errors due to old curl version in the CI
  discovery-infra/bootstrap_in_place.py
Labels: approved, size/XS, lgtm

#1049 Support dynamic OCP default version
  discovery-infra/start_discovery.py
  discovery-infra/test_infra/assisted_service_api.py
  discovery-infra/test_infra/consts/consts.py
  discovery-infra/test_infra/consts/env_defaults.py
  discovery-infra/test_infra/utils/global_variables/env_variables_utils.py
  discovery-infra/test_infra/utils/global_variables/global_variables.py
  discovery-infra/test_infra/utils/utils.py
  discovery-infra/tests/config/__init__.py
  discovery-infra/tests/config/env_config.py
  discovery-infra/tests/config/global_configs.py
  discovery-infra/tests/conftest.py
  discovery-infra/tests/test_e2e_install.py
  discovery-infra/tests/test_kube_api.py
  scripts/install_environment.sh
Labels: size/L, approved, lgtm

#1064 Adding status_info validation for wrong boot order and reboot timeout
  discovery-infra/test_infra/consts/consts.py
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/utils/utils.py
Labels: size/M, approved, lgtm

#991 Add custom manifest new format file
  discovery-infra/download_logs.py
Labels: approved, size/XS, lgtm

#1072 Fix broken set_cluster_name method
  discovery-infra/test_infra/helper_classes/cluster.py
Labels: approved, size/XS, lgtm

#1066 NO-ISSUE: vsphere controller warnings
  discovery-infra/test_infra/controllers/node_controllers/vsphere_controller.py
Labels: approved, size/XS, lgtm
