Repository openshift/assisted-test-infra, pull requests merged in 2021-10, with the labels that each got.

#1005 NO-ISSUE - Fix logs failing while trying to download custom_manifests.yaml file
  discovery-infra/download_logs.py
  discovery-infra/logger.py
Labels: size/M, approved, lgtm

#1138 NO-ISSUE: remove reduntant consts
  discovery-infra/test_infra/consts/consts.py
Labels: approved, size/XS, lgtm

#1137 NO-ISSUE - Update linter max line length to be 120
  .flake8
Labels: approved, size/XS

#1139 MGMT-7928: Use infrenv api to generate and download image
  discovery-infra/test_infra/assisted_service_api.py
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/helper_classes/config/base_infra_env_config.py
  discovery-infra/test_infra/helper_classes/infra_env.py
  discovery-infra/tests/base_test.py
Labels: size/L, approved, lgtm

#1154 Pass set cluster proxy config when generating infraenv, to fix ipv6 flow
  discovery-infra/test_infra/helper_classes/cluster.py
  discovery-infra/test_infra/helper_classes/config/base_entity_config.py
  discovery-infra/test_infra/helper_classes/config/base_infra_env_config.py
  discovery-infra/test_infra/helper_classes/infra_env.py
Labels: size/M, approved, lgtm

#1171 NO-ISSUE: fix default python version used
  Dockerfile.test-infra
Labels: approved, size/XS, lgtm

#1176 MGMT-4990 - Add linter for creating uniform styling conventions
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  Makefile
  isort.cfg
Labels: size/M, approved, lgtm

#1181 Fix logs test
  discovery-infra/test_infra/utils/logs_utils.py
Labels: approved, size/XS, lgtm

#1182 NO-ISSUE: trying to retry curl request for arkade installation code
  scripts/install_minikube.sh
Labels: approved, size/XS, lgtm

#1197 MGMT-8058: Add logic to detect if running in Openshift CI
  Makefile
Labels: size/S, approved, lgtm

#1194 MGMT-8087 - Show service logs failures on PROW spyglass
  discovery-infra/download_logs.py
  discovery-infra/junit_log_parser.py
  discovery-infra/logger.py
  scripts/download_logs.sh
Labels: size/L, approved, lgtm

#1198 NO-ISSUE: use an external image for dynamic load balancing
  Makefile
  scripts/install_environment.sh
Labels: size/S, approved, lgtm
