Repository openshift/assisted-test-infra, pull requests merged in 2022-07, with the labels that each got.

#1728 NO-ISSUE: Deploy assisted-image-service from prow
  skipper.env
Labels: approved, size/XS, lgtm

#1731 additional parameter(timeout) for method wait_for_specific_host_status and new host event parameter DISCONNECTED
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/consts/consts.py
Labels: ok-to-test, approved, size/XS, lgtm

#1738 NO-ISSUE: allow cross network traffic
  scripts/install_environment.sh
Labels: size/S, approved, lgtm

#1739 Delete tfstate file during destroy nodes
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
Labels: approved, size/XS, lgtm

#1743 NO-ISSUE - Clear previous tests images and logs only if `TEST_TEARDOWN!=false`
  Makefile
Labels: size/S, approved, lgtm

#1742 NO-ISSUE - Remove `_deploy_nodes` deprecated targets
  Makefile
Labels: size/S, approved, lgtm

#1732 MGMT-10946: fix memory usage based on OCP requirements
  src/consts/consts.py
  src/consts/resources.py
  src/tests/base_kubeapi_test.py
  src/tests/test_bootstrap_in_place.py
  src/update_assisted_service_cm.py
Labels: size/M, approved, lgtm

#1747 NO-ISSUE: remove reject rules from LIBVIRT_FWI chain instead of flushing the chain
  scripts/install_environment.sh
  scripts/setup_capi_env.sh
Labels: approved, size/XS, lgtm

#1745 MGMT-11110 - Remove unused default tfvars files from terraform template
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/tools/terraform_utils.py
  src/assisted_test_infra/test_infra/utils/terraform_util.py
  src/assisted_test_infra/test_infra/utils/utils.py
  src/consts/consts.py
  src/tests/base_test.py
  terraform_files/baremetal/terraform.tfvars.json
  terraform_files/baremetal/variables-libvirt.tf
  terraform_files/baremetal_infra_env/terraform.tfvars.json
  terraform_files/baremetal_infra_env/variables-libvirt.tf
  terraform_files/none/terraform.tfvars.json
  terraform_files/none/variables-libvirt.tf
  terraform_files/vsphere-ci-machine/terraform.tfvars.json
  terraform_files/vsphere/terraform.tfvars.json
Labels: size/L, approved, lgtm

#1754 Document vsphere special env variables
  README.md
  terraform_files/vsphere/variables-vsphere.tf
Labels: size/S, approved, lgtm

#1756 Allow usage of AlmaLinux OS in assisted-test-infra
  GUIDE.md
  README.md
  scripts/create_full_environment.sh
Labels: size/S, approved, lgtm

#1757 NO-ISSUE - Remove flake8 select plugin limitations. Fix PEP8 violations.
  .flake8
  requirements-dev.txt
  src/assisted_test_infra/download_logs/download_logs.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
  src/assisted_test_infra/test_infra/helper_classes/hypershift.py
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/agent.py
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/agent_cluster_install.py
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/cluster_image_set.py
  src/assisted_test_infra/test_infra/utils/operators_utils.py
Labels: size/M, approved, lgtm

#1748 MGMT-11119: CI workaround: Get swtpm from source
  scripts/install_environment.sh
Labels: size/M, approved, lgtm

#1758 NO-ISSUE - Add makefile target for deleting all exist clusters
  Makefile
  src/tests/test_targets.py
Labels: size/S, approved, lgtm

#1760 Do not pull images from Dockerfile.*.ocp files
  scripts/pull_dockerfile_images.sh
Labels: approved, size/XS, lgtm

#1761 NO-ISSUE - Allow KeyboardInterrupt during download logs
  src/assisted_test_infra/download_logs/__main__.py
  src/assisted_test_infra/download_logs/download_logs.py
  src/tests/base_test.py
Labels: size/S, approved, lgtm

#1764 NO-ISSUE - Prevent from using the same assisted-service image while using DEBUG_SERVICE flag
  scripts/deploy_assisted_service.sh
Labels: approved, size/XS, lgtm

#1744 MGMT-11109 - Prepare nodes only after having an infra_env
  src/assisted_test_infra/test_infra/controllers/node_controllers/node_controller.py
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/cluster_host.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_entity_config.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_infra_env_config.py
  src/assisted_test_infra/test_infra/helper_classes/config/cluster_config.py
  src/assisted_test_infra/test_infra/helper_classes/day2_cluster.py
  src/assisted_test_infra/test_infra/helper_classes/entity.py
  src/assisted_test_infra/test_infra/helper_classes/infra_env.py
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/infraenv.py
  src/assisted_test_infra/test_infra/helper_classes/nodes.py
  src/assisted_test_infra/test_infra/utils/utils.py
  src/service_client/assisted_service_api.py
  src/tests/base_kubeapi_test.py
  src/tests/base_test.py
  src/tests/config/global_configs.py
  src/tests/test_day2.py
  src/tests/test_kube_api.py
Labels: size/L, approved, lgtm

#1765 NO-ISSUE: provide baseDomain when creating hypershift hostedcluster
  src/assisted_test_infra/test_infra/helper_classes/hypershift.py
Labels: approved, size/XS, lgtm

#1767 Support podman-remote
  Dockerfile.assisted-test-infra
  Makefile
  scripts/install_environment.sh
  scripts/run_minikube.sh
  scripts/test_ui.sh
  scripts/utils.sh
  skipper.yaml
  src/assisted_test_infra/test_infra/controllers/ipxe_controller/ipxe_controller.py
  src/assisted_test_infra/test_infra/controllers/tang_controller/tang_controller.py
  src/assisted_test_infra/test_infra/utils/utils.py
  src/consts/consts.py
  src/tests/test_bootstrap_in_place.py
Labels: size/L, approved, lgtm

#1774 Fix EPEL installation for RHEL and CentOS
  scripts/install_environment.sh
Labels: size/S, approved, lgtm

#1775 Fix swtpm installation not being idempotent
  scripts/install_environment.sh
Labels: size/S, approved, lgtm

#1777 fixing podman installation script
  scripts/deploy_assisted_service.sh
  scripts/install_environment.sh
  scripts/utils.sh
Labels: size/S, approved, lgtm

#1778 NO-ISSUE: `download_logs.py` should include cluster infra-envs in `metadata.json`
  src/assisted_test_infra/download_logs/download_logs.py
Labels: size/S, approved, lgtm

#1776 Fix podman verification code
  scripts/install_environment.sh
Labels: size/S, approved, lgtm
