Repository openshift/assisted-test-infra, pull requests merged in 2022-10, with the labels that each got.

#1867 MGMT-12197: Make test-infra default to OVNKubernetes when openshift version is at least 4.12
  src/triggers/default_triggers.py
Labels: approved, size/XS, lgtm

#1839 MGMT-11706: Add test for the upgrade agent feature
  skipper.env
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/tests/test_upgrade_agent.py
Labels: size/L, approved, lgtm

#1860 MGMT-11274: Add Packer and Terraform files to run AI test machine
  packer_files/nutanix_centos_template/build.pkr.hcl
  packer_files/nutanix_centos_template/centos-config/ks.cfg
  packer_files/nutanix_centos_template/sources.pkr.hcl
  packer_files/nutanix_centos_template/variables.pkr.hcl
  packer_files/nutanix_centos_template/vars.json
  terraform_files/nutanix-ci-machine/main.tf
  terraform_files/nutanix-ci-machine/output.tf
  terraform_files/nutanix-ci-machine/variables-nutanix.tf
Labels: size/L, approved, lgtm

#1875 packer: update SSH key in nutanix VM
  packer_files/nutanix_centos_template/centos-config/ks.cfg
Labels: approved, size/XS, lgtm

#1876 nutanix machine: enable nested virt
  terraform_files/nutanix-ci-machine/main.tf
Labels: approved, size/XS, lgtm

#1878 nutanix packer: eject cdrom
  packer_files/nutanix_centos_template/centos-config/ks.cfg
Labels: approved, size/XS, lgtm

#1880 nutanix: don't allocation VIPs if DHCP allocation is not set
  src/assisted_test_infra/test_infra/controllers/node_controllers/nutanix_controller.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_nutanix_config.py
Labels: size/S, approved, lgtm

#1864 NO-ISSUE: Fix late-binding job
  Makefile
  src/tests/base_kubeapi_test.py
  src/tests/test_kube_api.py
Labels: size/S, approved, lgtm

#1881 requirements.txt: bump nutanix-api to 0.0.18
  requirements.txt
Labels: approved, size/XS, lgtm

#1882 MGMT-11856: Removing pullSecret from install-config.yaml
  src/assisted_test_infra/download_logs/download_logs.py
Labels: size/S, approved, lgtm

#1887 remove dedundant boto3 dependency
  requirements.txt
Labels: approved, size/XS, lgtm

#1826 [release-ocm-2.5] NO-ISSUE - Prevent tests from being skipped when test parameterized is empty
  Makefile
  requirements.txt
Labels: approved, size/XS, lgtm

#1889 NO-ISSUE: Upgrade Python 3.11 that is now officially available
  Dockerfile.assisted-test-infra
Labels: approved, size/XS, lgtm
