Repository openshift/assisted-test-infra, pull requests merged in 2022-06, with the labels that each got.

#1670 NO-ISSUE: collect the pod yaml of all the pods running in the same namespace as the capi provider agent
  scripts/download_logs.sh
Labels: approved, size/XS, lgtm

#1678 NO-ISSUE: Fixing capi test by adding label worker to minikube
  scripts/setup_capi_env.sh
  src/assisted_test_infra/test_infra/helper_classes/hypershift.py
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/secret.py
  src/tests/test_kube_api.py
Labels: size/M, approved, lgtm

#1681 Update etc hosts file append a mapping to the api and ingress vips
  src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
  src/assisted_test_infra/test_infra/utils/utils.py
  src/consts/resources.py
Labels: size/M, approved, lgtm

#1682 NO-ISSUE: added 20 minutes WAIT_FOR_HYPERSHIFT_CONTROL_PLANE_TIMEOUT
  src/assisted_test_infra/test_infra/helper_classes/hypershift.py
Labels: approved, size/XS, lgtm

#1686 Revert "Update etc hosts file append a mapping to the api and ingress vips"
  src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
  src/assisted_test_infra/test_infra/utils/utils.py
  src/consts/resources.py
Labels: size/M, approved, lgtm

#1680 bump terraform to v1.2.2
  Dockerfile.assisted-test-infra
Labels: approved, size/XS, lgtm

#1653 Adding support for tang server for encryption tests
  scripts/install_environment.sh
  src/assisted_test_infra/test_infra/controllers/__init__.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/assisted_test_infra/test_infra/controllers/tang_controller/__init__.py
  src/assisted_test_infra/test_infra/controllers/tang_controller/tang_controller.py
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/config/cluster_config.py
  src/consts/consts.py
  src/consts/resources.py
  src/tests/base_test.py
Labels: size/L, approved, lgtm

#1692 NO-ISSUE: Don't assume all resources have a status
  src/assisted_test_infra/test_infra/utils/oc_utils.py
Labels: approved, size/XS, lgtm

#1693 Change the default disk size from 120GB to 100GB
  src/consts/consts.py
  src/consts/resources.py
  src/triggers/default_triggers.py
Labels: approved, size/XS, lgtm

#1694 MGMT-9378 - Bug fixes to make day-2 Assisted REST flow support SNO
  src/assisted_test_infra/test_infra/helper_classes/day2_cluster.py
  terraform_files/baremetal/main.tf
Labels: size/S, approved, lgtm

#1684 MGMT-10717: set OCP-4.10 as the default ASSISTED_OPENSHIFT_INSTALL_RELEASE_IMAGE
  src/tests/test_kube_api.py
Labels: approved, size/XS, lgtm

#1696 NO-ISSUE: it takes time to hypershift to create namespace and we should add secret only after it was created
  src/tests/test_kube_api.py
Labels: approved, size/XS, lgtm

#1691 Add api and ingress vips mapping to the skipper container /etc/host file
  src/assisted_test_infra/test_infra/controllers/node_controllers/node_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/utils/utils.py
  src/consts/resources.py
  src/tests/test_kube_api.py
  terraform_files/baremetal/main.tf
  terraform_files/baremetal/variables-libvirt.tf
  terraform_files/baremetal_infra_env/main.tf
  terraform_files/baremetal_infra_env/variables-libvirt.tf
  terraform_files/none/main.tf
  terraform_files/none/variables-libvirt.tf
Labels: size/L, approved, lgtm

#1695 MGMT-10830 - Create base class for test-infra containerized controllers
  src/assisted_test_infra/test_infra/controllers/containerized_controller.py
  src/assisted_test_infra/test_infra/controllers/ipxe_controller/ipxe_controller.py
  src/assisted_test_infra/test_infra/controllers/proxy_controller/proxy_controller.py
  src/assisted_test_infra/test_infra/controllers/tang_controller/tang_controller.py
  src/tests/base_test.py
Labels: size/L, approved, lgtm

#1698 NO-ISSUE - Add function to modify cluster network type
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
Labels: ok-to-test, approved, size/XS, lgtm

#1702 NO-ISSUE: Clean dnsmasq files
  src/tests/base_test.py
Labels: approved, size/XS, lgtm

#1708 NO-ISSUE: Remove Fedora support, add warning about this repo
  GUIDE.md
  README.md
  scripts/create_full_environment.sh
Labels: size/S, approved, lgtm

#1712 MGMT-10849: Install Insights rules from private RHT repository
  Jenkinsfile.download_logs
Labels: approved, size/XS, lgtm

#1714 Use pip3 instead of pip in Jenkins job
  Jenkinsfile.download_logs
Labels: approved, size/XS, lgtm

#1715 Remove "download_jobs" Jenkinsfile after move to deployment repo
  Jenkinsfile.download_logs
Labels: size/M, approved, lgtm

#1716 adding some more approvers to the list
  OWNERS
Labels: approved, size/XS, lgtm

#1707 [release-ocm-2.5] Change the default disk size from 120GB to 100GB (#1693)
  src/consts/consts.py
  src/consts/resources.py
  src/triggers/default_triggers.py
Labels: size/S, approved, lgtm

#1711 Fixing debugging the service from test-infra by setting DEBUG_SERVICE…
  skipper.env
Labels: approved, size/XS, lgtm

#1717 Fix disk size calculation when formatting disks.
  src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
Labels: size/S, approved, lgtm

#1719 NO-ISSUE - Fix missing constructor arguments on proxy controller.
  src/assisted_test_infra/test_infra/controllers/proxy_controller/proxy_controller.py
Labels: approved, size/XS, lgtm

#1726 MGMT-10965: collect the pods and cluster nodes yamls
  scripts/download_logs.sh
Labels: approved, size/XS, lgtm

#1725 Remove redundant dependency
  requirements.txt
Labels: approved, size/XS, lgtm

#1727 MGMT-9427: Add scale down the the CAPI e2e test
  src/tests/test_kube_api.py
Labels: size/S, approved, lgtm

#1729 MGMT-9909: Use centos stream 9 in Dockerfile
  Dockerfile.assisted-test-infra
Labels: size/S, approved, lgtm
