Repository openshift/assisted-test-infra, pull requests merged in 2022-04, with the labels that each got.

#1577 MGMT-9852 - Fix image-pulling script
  scripts/pull_dockerfile_images.sh
Labels: size/S, approved, lgtm

#1576 MGMT-9213: add ingress_dns option to terraform_controller
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/assisted_test_infra/test_infra/helper_classes/config/nodes_config.py
  src/tests/base_kubeapi_test.py
  src/tests/global_variables/env_variables_defaults.py
Labels: size/S, approved, lgtm

#1580 NO-ISSUE - Fix cluster events random suite/test names
  requirements.txt
  src/service_client/assisted_service_api.py
Labels: approved, size/XS, lgtm

#1581 NO-ISSUE - Fix fetching pull-request when running `bring_assisted_service` twice
  Makefile
Labels: approved, size/XS, lgtm

#1595 NO-ISSUE - Remove pull-always flag from PULL_PARAMS
  Makefile
  scripts/pull_dockerfile_images.sh
Labels: approved, size/XS, lgtm

#1596 Allocating all the storage to the root filesystem
  packer_files/vsphere_centos_template/centos-config/centos8-ks.cfg
  packer_files/vsphere_centos_template/variables.pkr.hcl
Labels: approved, size/XS, lgtm

#1601 Pre-existing vSphere folders should not be created
  terraform_files/vsphere/main.tf
Labels: approved, size/XS, lgtm

#1600 NO-ISSUE: Use unix socket in libvirt_uri
  terraform_files/baremetal/terraform.tfvars.json
  terraform_files/baremetal_infra_env/terraform.tfvars.json
  terraform_files/none/terraform.tfvars.json
Labels: approved, size/XS, lgtm

#1602 NO-ISSUE: [release-ocm-2.4]: Change catalog image to one that's actually being updated
  Makefile
Labels: approved, size/XS, lgtm

#1605 vsphere vm resource should be depended to the vsphere folder resource
  terraform_files/vsphere/main.tf
Labels: approved, size/XS, lgtm

#1603 MGMT-9909: Use centos stream 9 in Dockerfile
  Dockerfile.assisted-test-infra
Labels: size/S, approved, lgtm

#1607 Revert "MGMT-9909: Use centos stream 9 in Dockerfile"
  Dockerfile.assisted-test-infra
Labels: size/S, approved, lgtm

#1523 MGMT-9555 - Add more complex triggers conditions comparison methods
  src/triggers/default_triggers.py
  src/triggers/env_trigger.py
  src/triggers/olm_operators_trigger.py
Labels: size/M, approved, lgtm

#1606 Handle forward-compatibility with 'setup' target
  Makefile
Labels: approved, size/XS, lgtm

#1608 Support passing vips IPs as env variables
  skipper.env
  src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/tests/global_variables/env_variables_defaults.py
Labels: size/S, approved, lgtm

#1610 Gather release-image.service log
  src/assisted_test_infra/download_logs/resources/man_sosreport.sh
Labels: approved, size/XS, lgtm

#1612 NO-ISSUE - Add WORKERS_COUNT and MASTERS_COUNT to skipper.env
  skipper.env
Labels: approved, size/XS, lgtm

#1611 MGMT-9840 - assisted-test-infra doesn't rebase assisted-service in PRs
  Makefile
Labels: approved, size/XS, lgtm

#1614 Revert "MGMT-9840 - assisted-test-infra doesn't rebase assisted-service in PRs"
  Makefile
Labels: approved, size/XS, lgtm

#1619 assisted_service_api: get_api_vip should work when API VIP is not set
  src/service_client/assisted_service_api.py
Labels: approved, size/XS, lgtm

#1620 Adding a cluster method to set encryption params
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
Labels: approved, size/XS, lgtm

#1621 NO-ISSUE: get_api_vip: allow unset user_managed_networking
  src/service_client/assisted_service_api.py
Labels: approved, size/XS, lgtm

#1622 NO-ISSUE - Add type hint annotations for set_disk_encryption
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
Labels: size/S, approved, lgtm

#1548 MGMT-10081: Log install progress
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/utils/operators_utils.py
Labels: size/S, approved, lgtm

#1618 NO-ISSUE: Remove cluster ID suffix from cluster_event junit tests
  requirements.txt
  src/service_client/assisted_service_api.py
Labels: approved, size/XS, lgtm

#1624 NO-ISSUE - junit: don't add cluster_id to class names
  requirements.txt
  src/service_client/assisted_service_api.py
Labels: approved, size/XS, lgtm

#1578 MGMT-9350: Add iPXE boot flow
  README.md
  scripts/install_environment.sh
  skipper.env
  src/assisted_test_infra/test_infra/controllers/__init__.py
  src/assisted_test_infra/test_infra/controllers/ipxe_controller/__init__.py
  src/assisted_test_infra/test_infra/controllers/ipxe_controller/ipxe_controller.py
  src/assisted_test_infra/test_infra/controllers/ipxe_controller/server/Dockerfile
  src/assisted_test_infra/test_infra/controllers/ipxe_controller/server/local_ipxe_server.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/assisted_test_infra/test_infra/helper_classes/config/cluster_config.py
  src/assisted_test_infra/test_infra/helper_classes/config/controller_config.py
  src/assisted_test_infra/test_infra/utils/utils.py
  src/consts/consts.py
  src/service_client/assisted_service_api.py
  src/tests/base_test.py
  src/tests/global_variables/env_variables_defaults.py
  src/triggers/default_triggers.py
  terraform_files/baremetal/main.tf
  terraform_files/baremetal/terraform.tfvars.json
  terraform_files/baremetal/variables-libvirt.tf
  terraform_files/baremetal_host/main.tf
  terraform_files/baremetal_host/variables.tf
Labels: size/L, approved, lgtm

#1616 Fix errors when test-infra tries to access data/
  Makefile
  scripts/deploy_assisted_service.sh
Labels: approved, size/XS, lgtm

#1617 MGMT-9840 - Move bring_assisted_service Makefile target to bash script
  Makefile
  scripts/bring_assisted_service.sh
  scripts/install_environment.sh
Labels: size/M, approved, lgtm

#1632 NO-ISSUE - Assert if no PULL_SECRET provided
  src/tests/conftest.py
Labels: approved, size/XS, lgtm

#1633 NO-ISSUE: Set global git user & email address when running in CI
  scripts/bring_assisted_service.sh
Labels: size/S, approved, lgtm
