Repository openshift/assisted-test-infra, pull requests merged in 2022-09, with the labels that each got.

#1817 NO-ISSUE - Use baremetal platform on SNO
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/triggers/default_triggers.py
Labels: size/S, approved, lgtm

#1824 NO-ISSUE - Prevent tests from being skipped when test parameterized is empty
  Makefile
  requirements.txt
Labels: approved, size/XS, lgtm

#1822 NO-ISSUE: fix must-gather log collection in case of hypershift cluster
  src/assisted_test_infra/download_logs/download_logs.py
Labels: approved, size/XS, lgtm

#1815 NO-ISSUE: Add missing sudo in install_environment.sh
  scripts/install_environment.sh
Labels: approved, size/XS, lgtm

#1825 [release-ocm-2.6] NO-ISSUE - Prevent tests from being skipped when test parameterized is empty
  Makefile
  requirements.txt
Labels: approved, size/XS, lgtm

#1829 MGMT-11586 - Add 4.12 to available openshift versions
  src/consts/consts.py
Labels: approved, size/XS, lgtm

#1832 NO-ISSUE: Update skipper to 1.34.0
  scripts/install_environment.sh
Labels: approved, size/XS, lgtm

#1834 Expose UMN as a setting
  skipper.env
  src/tests/global_variables/env_variables_defaults.py
Labels: approved, size/XS, lgtm

#1835 MGMT-11981: FIx teardown on vsphere nodes
  src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
Labels: approved, size/XS, lgtm

#1827 NO-ISSUE - Upgrade to python3.10
  Dockerfile.assisted-test-infra
  scripts/override_os_images.py
  scripts/override_release_images.py
  scripts/set_boot_order.by
  src/assisted_test_infra/test_infra/controllers/ipxe_controller/server/local_ipxe_server.py
  src/update_assisted_service_cm.py
Labels: size/S, approved, lgtm

#1833 MGMT-11938 - Remove default platform from test env vars
  .flake8
  requirements-dev.txt
  skipper.env
  src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/node_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/nutanix_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/config/__init__.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_cluster_config.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_day2_cluster_config.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_entity_config.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_infra_env_config.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_nodes_config.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_nutanix_config.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_terraform_config.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_vsphere_config.py
  src/assisted_test_infra/test_infra/helper_classes/day2_cluster.py
  src/assisted_test_infra/test_infra/helper_classes/nodes.py
  src/assisted_test_infra/test_infra/utils/kubeapi_utils.py
  src/consts/consts.py
  src/tests/base_kubeapi_test.py
  src/tests/base_test.py
  src/tests/global_variables/env_variables_defaults.py
  src/tests/test_bootstrap_in_place.py
  src/tests/test_kube_api.py
  src/tests/test_targets.py
  src/triggers/default_triggers.py
Labels: size/L, approved, lgtm

#1823 Add support for cluster tags
  skipper.env
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_cluster_config.py
  src/tests/global_variables/env_variables_defaults.py
Labels: size/S, approved, lgtm

#1843 NO-ISSUE: Remove michaellevy101 from owners
  OWNERS
Labels: approved, size/XS, lgtm

#1845 fix virt-format command missing
  Dockerfile.assisted-test-infra
Labels: approved, size/XS, lgtm

#1846 NO-ISSUE: fix describe_cluster_operators
  src/assisted_test_infra/download_logs/download_logs.py
Labels: approved, size/XS, lgtm

#1847 MGMT-12026: do not reset trigger values
  src/assisted_test_infra/test_infra/utils/env_var.py
Labels: size/S, approved, lgtm

#1683 MGMT-9914: Integration of the ODF LVM operator with assisted installer
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/consts/consts.py
  src/consts/olm_operators.py
  src/triggers/default_triggers.py
Labels: size/S, approved, lgtm

#1848 NO-ISSUE: ensure dest folder exists in download_kubeconfig
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/agent_cluster_install.py
Labels: approved, size/XS, lgtm

#1849 NO-ISSUE: download kubeconfig in BaseKubeAPI test
  src/tests/base_kubeapi_test.py
  src/tests/test_kube_api.py
Labels: approved, size/XS, lgtm

#1828 MGMT-11706: Run e2e tests with the upgrade agent feature enabled
  src/update_assisted_service_cm.py
Labels: approved, size/XS, lgtm

#1852 MGMT-12096: Fix errors accessing load-balancer http conf file
  Makefile
Labels: approved, size/XS, lgtm

#1814 MGMT-11143: Add e2e test for agent reclaim
  scripts/deploy_assisted_service.sh
  skipper.env
  src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/agent.py
  src/tests/base_kubeapi_test.py
  src/tests/global_variables/env_variables_defaults.py
  src/tests/test_kube_api.py
  src/update_assisted_service_cm.py
Labels: size/L, approved, lgtm

#1855 NO-ISSUE: colloect the configmaps from the HCP as part of collecting capi_logs
  scripts/download_logs.sh
Labels: approved, size/XS, lgtm

#1856 MGMT-11926: vsphere: create machines with HW 15
  terraform_files/vsphere/main.tf
Labels: approved, size/XS, lgtm

#1857 NO-ISSUE: Change log folder time format to use dashes rather than colons
  src/assisted_test_infra/download_logs/download_logs.py
Labels: approved, size/XS, lgtm

#1866 MGMT-11968: Use lock and tmp file when altering iptables rules
  scripts/install_environment.sh
Labels: approved, size/XS, lgtm
