Repository openshift/assisted-test-infra, pull requests merged in 2022-12, with the labels that each got.

#1940 deploy_assisted: don't overwrite OS_IMAGES
  scripts/deploy_assisted_service.sh
Labels: approved, size/XS, lgtm

#1915 MGMT-8357: Support kind hub-cluster
  Makefile
  README.md
  scripts/create_full_environment.sh
  scripts/deploy_assisted_service.sh
  scripts/deploy_ui.sh
  scripts/hub-cluster/create.sh
  scripts/hub-cluster/delete.sh
  scripts/hub-cluster/kind/kind-config.yaml
  scripts/hub-cluster/kind/kind.sh
  scripts/hub-cluster/minikube.sh
  scripts/install_k8s_clients.sh
  scripts/run_minikube.sh
  src/assisted_test_infra/test_infra/utils/utils.py
Labels: size/L, approved, lgtm

#1942 Allow 'onprem' deploy-target in hub-cluster setup
  Makefile
  scripts/hub-cluster/create.sh
  scripts/hub-cluster/delete.sh
Labels: size/S, approved, lgtm

#1944 Improve capi logs gather
  scripts/download_logs.sh
Labels: size/S, approved, lgtm

#1946 fix download-logs.sh script syntax
  scripts/download_logs.sh
Labels: approved, size/XS, lgtm

#1948 MGMT-12881: fix REBOOT_TIMEOUT message string to match the message in assisted-service
  src/consts/consts.py
Labels: approved, size/XS, lgtm

#1955 NO-ISSUE: Update to terraform 1.3.6
  .gitignore
  Dockerfile.assisted-test-infra
  terraform_files/baremetal/main.tf
  terraform_files/baremetal/variables-libvirt.tf
  terraform_files/baremetal_host/main.tf
  terraform_files/baremetal_host/variables.tf
  terraform_files/baremetal_infra_env/main.tf
  terraform_files/baremetal_infra_env/variables-libvirt.tf
  terraform_files/none/main.tf
  terraform_files/none/variables-libvirt.tf
  terraform_files/nutanix-ci-machine/main.tf
  terraform_files/nutanix-ci-machine/output.tf
  terraform_files/nutanix-ci-machine/variables-nutanix.tf
  terraform_files/nutanix/main.tf
  terraform_files/nutanix/variables_nutanix.tf
  terraform_files/nutanix/virtual_machines.tf
  terraform_files/vsphere-ci-machine/main.tf
  terraform_files/vsphere-ci-machine/variables-vsphere.tf
  terraform_files/vsphere/main.tf
  terraform_files/vsphere/variables-vsphere.tf
Labels: size/XL, approved, lgtm

#1954 Current iptables fixture tears down nodes in order modify iptables.
  src/assisted_test_infra/test_infra/helper_classes/nodes.py
Labels: ok-to-test, approved, size/XS, lgtm

#1957 MGMT-12881: fix REBOOT_TIMEOUT message string to match the message in assisted-service
  src/consts/consts.py
Labels: approved, size/XS, lgtm

#1956 Fix none platform domain name - unable to resolve redhat.com
  terraform_files/none/main.tf
Labels: ok-to-test, approved, size/XS, lgtm

#1949 MGMT-12439: Deploy heterogeneous infrastructure
  Dockerfile.assisted-test-infra
  ansible_files/ansible.cfg
  ansible_files/equinix_generic_destroy_infra_playbook.yml
  ansible_files/equinix_heterogeneous_create_infra_playbook.yml
  ansible_files/roles/common/setup_ipip_tunnel/tasks/main.yml
  ansible_files/roles/equinix/export_primary_device_connection_details/defaults/main.yml
  ansible_files/roles/equinix/export_primary_device_connection_details/tasks/main.yml
  ansible_files/roles/equinix/export_primary_device_connection_details/templates/ci-machine-config.sh.j2
  ansible_files/roles/equinix/generic_destroy_infra/tasks/main.yml
  ansible_files/roles/equinix/heterogeneous_create_infra/defaults/main.yaml
  ansible_files/roles/equinix/heterogeneous_create_infra/tasks/main.yml
  ansible_files/roles/equinix/heterogeneous_create_infra/templates/terraform.tfvars.j2
  ansible_files/vars/ci.yml
  ansible_files/vars/ci_equinix_infrastucture.yml
  ansible_files/vars/standalone_equinix_sample.yml
  requirements.txt
  terraform_files/equinix-ci-machine/main.tf
  terraform_files/equinix-ci-machine/output.tf
  terraform_files/equinix-ci-machine/variables_equinix.tf
Labels: size/L, approved, lgtm

#1962 Iptables rules added without destination port due to iptables versions
  skipper.yaml
Labels: needs-ok-to-test, approved, size/XS, lgtm

#1958 MGMT-12440: Configure IPIP tunnel with heterogeneous setup
  ansible_files/equinix_heterogeneous_create_infra_playbook.yml
  ansible_files/roles/common/setup_ipip_tunnel/defaults/main.yml
  ansible_files/roles/common/setup_ipip_tunnel/tasks/main.yml
Labels: size/M, approved, lgtm

#1964 MGMT-13038: Git fails to trust git repository because of mismatch with files
  Dockerfile.assisted-test-infra
Labels: approved, size/XS, lgtm

#1966 MGMT-12441: Install libvirtd on the ARM machine
  ansible_files/equinix_heterogeneous_create_infra_playbook.yml
  ansible_files/roles/common/setup_libvirtd/handlers/main.yml
  ansible_files/roles/common/setup_libvirtd/tasks/main.yml
  ansible_files/roles/common/setup_ssh_key_pair/defaults/main.yml
  ansible_files/roles/common/setup_ssh_key_pair/tasks/main.yml
  ansible_files/roles/common/setup_ssh_key_pair/templates/config.j2
Labels: size/M, approved, lgtm

#1963 Allow overriding pytest flags
  Makefile
  skipper.env
Labels: approved, size/XS, lgtm

#1973 Cannot remove container as it is running issue
  src/assisted_test_infra/test_infra/utils/utils.py
Labels: ok-to-test, approved, size/XS, lgtm

#1975 Extending SNO installation timeout to 70 mins
  src/tests/test_bootstrap_in_place.py
Labels: approved, size/XS, lgtm

#1883 Bump terraform-provider-libvirt to v0.7.1
  terraform_files/baremetal/main.tf
  terraform_files/baremetal_host/main.tf
  terraform_files/baremetal_infra_env/main.tf
  terraform_files/none/main.tf
Labels: approved, size/XS, lgtm

#1976 remove redundant xsl files and use just one
  terraform_files/baremetal/consolemodel.xsl
  terraform_files/baremetal_host/main.tf
  terraform_files/baremetal_infra_env/consolemodel.xsl
  terraform_files/none/consolemodel.xsl
Labels: size/M, approved, lgtm
