Repository openshift/assisted-test-infra, pull requests merged in 2022-11, with the labels that each got.

#1885 MGMT-12345: Fix vsphere CI jobs failures due to Internal Server Error (500)
  Makefile
  packer_files/vsphere_centos_template/build.pkr.hcl
  packer_files/vsphere_centos_template/sources.pkr.hcl
  packer_files/vsphere_centos_template/variables.pkr.hcl
  packer_files/vsphere_centos_template/vars.json
  src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_vsphere_config.py
  src/assisted_test_infra/test_infra/tools/terraform_utils.py
  src/tests/global_variables/env_variables_defaults.py
  terraform_files/vsphere-ci-machine/main.tf
  terraform_files/vsphere-ci-machine/variables-vsphere.tf
  terraform_files/vsphere/main.tf
  terraform_files/vsphere/variables-vsphere.tf
Labels: size/M, approved, lgtm

#1884 MGMT-11926: bump vsphere machine specs
  terraform_files/vsphere-ci-machine/variables-vsphere.tf
Labels: approved, size/XS, lgtm

#1890 MGMT-12381: Remove VIP DHCP allocation defaults from test-infra
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/consts/env_defaults.py
  src/tests/global_variables/env_variables_defaults.py
  src/triggers/default_triggers.py
Labels: size/M, approved, lgtm

#1900 sanitize tar archives due to CVE
  src/assisted_test_infra/test_infra/utils/logs_utils.py
Labels: size/M, approved, lgtm

#1903 NO-ISSUE: Update requirements.txt
  requirements.txt
Labels: approved, size/XS, lgtm

#1902 NO-ISSUE: update statusRebootTimeout message
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/consts/consts.py
Labels: approved, size/XS, lgtm

#1865 MGMT-11566: Default to minimal ISO for tests
  scripts/deploy_assisted_service.sh
  skipper.env
  src/consts/env_defaults.py
Labels: approved, size/XS, lgtm

#1899 Nutanix: use 1.7.1 provider
  terraform_files/nutanix/main.tf
Labels: approved, size/XS, lgtm

#1911 MGMT-12333: Add discovery kernel arguments support
  README.md
  skipper.env
  src/assisted_test_infra/test_infra/helper_classes/config/base_infra_env_config.py
  src/assisted_test_infra/test_infra/helper_classes/infra_env.py
  src/tests/global_variables/env_variables_defaults.py
Labels: size/M, approved, lgtm

#1912 OCPBUGSM-46219: OCPBUGSM-46220: Update golang version to 1.18.1
  Dockerfile.assisted-test-infra
Labels: approved, size/XS, lgtm

#1909 vsphere: upload iso to test folder
  terraform_files/vsphere/main.tf
Labels: approved, size/XS, lgtm

#1913 MGMT-12545: Rename "discovery kernel arguments" to "kernel arguments" in infra-env context
  src/assisted_test_infra/test_infra/helper_classes/infra_env.py
Labels: approved, size/XS, lgtm

#1916 MGMT-8707: Revert swtpm installation from source
  scripts/install_environment.sh
Labels: size/M, approved, lgtm

#1919 Fix network interface getting removed intermediately
  src/assisted_test_infra/test_infra/tools/assets.py
Labels: size/S, approved, lgtm

#1920 Minimize use of 'rm %s' actions
  scripts/create_full_environment.sh
  scripts/install_binaries.sh
  scripts/install_environment.sh
  skipper.yaml
  src/assisted_test_infra/test_infra/utils/utils.py
  src/tests/base_test.py
Labels: size/M, approved, lgtm

#1921 Remove redundant none-platform code
  scripts/utils.sh
Labels: size/S, approved, lgtm

#1926 Remove redundant wget dependency
  Dockerfile.assisted-test-infra
Labels: approved, size/XS, lgtm

#1925 Using the new base python image
  Dockerfile.assisted-test-infra
Labels: approved, size/XS, lgtm

#1928 MGMT-12670: Set terraform parameters only on `create_nodes` and `destroy_nodes`
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/tests/test_bootstrap_in_place.py
Labels: size/M, approved, lgtm

#1934 Add return to get_disks
  src/assisted_test_infra/test_infra/controllers/node_controllers/node.py
Labels: ok-to-test, approved, size/XS, lgtm
