Repository openshift/assisted-test-infra, pull requests merged in 2022-02, with the labels that each got.

#1426 [release-ocm-2.4] MGMT-9102: Change the base image the same as in master
  .ci-operator.yaml
  Dockerfile.assisted-test-infra
  Makefile
  discovery-infra/test_infra/consts/consts.py
  discovery-infra/tests/conftest.py
  scripts/install_environment.sh
Labels: size/M, approved, lgtm

#1429 MGMT-7105: adding govc to the test-infra docker file
  Dockerfile.assisted-test-infra
Labels: approved, size/XS, lgtm

#1409 NO-ISSUE - Remove static-ip from networking job
  src/tests/test_e2e_install.py
Labels: approved, size/XS, lgtm

#1427 MGMT-8103: day2 test - migrate to v2 API
  src/day2.py
  src/service_client/assisted_service_api.py
Labels: size/M, approved, lgtm

#1431 [release-ocm-2.4 ] MGMT-9102: Backport kube-api test
  discovery-infra/test_infra/consts/consts.py
  discovery-infra/test_infra/helper_classes/kube_helpers/agent.py
  discovery-infra/test_infra/helper_classes/kube_helpers/common.py
  discovery-infra/test_infra/utils/entity_name.py
  discovery-infra/test_infra/utils/kubeapi_utils.py
  discovery-infra/tests/base_kubeapi_test.py
  discovery-infra/tests/base_test.py
  discovery-infra/tests/test_kube_api.py
  scripts/install_environment.sh
Labels: size/XL, approved, lgtm

#1430 Supporting arbitrary user ids
  Dockerfile.assisted-test-infra
Labels: approved, size/XS, lgtm

#1434 [release-ocm-2.4] MGMT-9102: Fix kubeapi makefile target
  Makefile
Labels: approved, size/XS, lgtm

#1435 Fixing a conflict with the packer executable
  Dockerfile.assisted-test-infra
Labels: approved, size/XS, lgtm

#1436 MGMT-9102: fix kubeapi client default value
  Makefile
  discovery-infra/test_infra/assisted_service_api.py
Labels: approved, size/XS, lgtm

#1432 Remove OCP deploy mode, which isn't really in use
  Makefile
  README.md
  scripts/deploy_assisted_service.sh
  scripts/deploy_controller.sh
  scripts/deploy_prometheus_ui.sh
  scripts/deploy_ui.sh
  scripts/ocp.sh
  src/ocp.py
Labels: size/L, approved, lgtm

#1440 [release-ocm-2.4] NO-ISSUE - Change parallel kube api job to be single threaded
  Makefile
Labels: approved, size/XS, lgtm

#1438 NO-ISSUE - Change pytest default workers count to 3
  Makefile
Labels: approved, size/XS, lgtm

#1443 Upgrading the packer vsphere plugin, fixing source name, updating iso…
  packer_files/vsphere_centos_template/build.pkr.hcl
  packer_files/vsphere_centos_template/sources.pkr.hcl
  packer_files/vsphere_centos_template/variables.pkr.hcl
Labels: size/S, approved, lgtm

#1441 Fix image_type param in infra_env and adding minimal iso event
  src/assisted_test_infra/test_infra/helper_classes/infra_env.py
  src/consts/consts.py
Labels: approved, size/XS, lgtm

#1444 MGMT-9178: single-node CI should use OVNKubernetes as the network type
  src/tests/test_bootstrap_in_place.py
Labels: approved, size/XS, lgtm

#1454 Support cluster & infra-env & hosts events
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/consts/consts.py
Labels: size/M, approved, lgtm

#1421 [release-ocm-2.4] MGMT-9102: Backport - Add logic to detect if running in Openshift CI assisted-service PR
  Makefile
Labels: size/S, approved, lgtm

#1453 Bump junit-report v0.2.5
  requirements.txt
Labels: approved, size/XS, lgtm

#1450 MGMT-8257: refactored day2 logic into test_day2
  src/assisted_test_infra/test_infra/__init__.py
  src/assisted_test_infra/test_infra/helper_classes/config/__init__.py
  src/assisted_test_infra/test_infra/helper_classes/config/day2_cluster_config.py
  src/assisted_test_infra/test_infra/helper_classes/day2_cluster.py
  src/day2.py
  src/tests/base_test.py
  src/tests/config/global_configs.py
  src/tests/global_variables/env_variables_defaults.py
  src/tests/test_day2.py
Labels: size/XL, approved, lgtm

#1442 Refactor makefile targets
  GUIDE.md
  Jenkinsfile
  Makefile
  README.md
  ansible-bm-install/collections/ansible_collections/okd/assisted_installer/roles/setup_repository/tasks/main.yml
Labels: size/L, approved, lgtm

#1451 MGMT-9183: capi test fail while waiting for machine controller to setowner ref on agentMachine
  src/assisted_test_infra/test_infra/helper_classes/hypershift.py
  src/tests/test_kube_api.py
Labels: size/M, approved, lgtm

#1458 NO-ISSUE: Handle exception during hypershift_cluster_client.list_node
  src/assisted_test_infra/test_infra/helper_classes/hypershift.py
Labels: approved, size/XS, lgtm

#1460 Remove set of `bootstrap_in_place` in kubeapi test
  src/tests/test_kube_api.py
Labels: approved, size/XS, lgtm

#1459 add get_preflight_requirements to cluster
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
Labels: ok-to-test, approved, size/XS, lgtm

#1462 MGMT-9273: allow installation on rocky linux
  create_full_environment.sh
  scripts/install_environment.sh
Labels: size/S, approved, lgtm

#1461 NO-ISSUE - Fix cluster and infra_env object cleanup
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/infra_env.py
  src/tests/base_test.py
Labels: size/S, approved, lgtm

#1466 NO-ISSUE: Fix make all target
  Makefile
Labels: approved, size/XS, lgtm

#1468 VSphere Centos8 packer improvement
  packer_files/vsphere_centos_template/centos-config/centos8-ks.cfg
  packer_files/vsphere_centos_template/sources.pkr.hcl
  packer_files/vsphere_centos_template/variables.pkr.hcl
Labels: size/M, approved, lgtm

#1456 Download infra-env events log
  src/assisted_test_infra/download_logs/download_logs.py
  src/service_client/assisted_service_api.py
Labels: size/S, approved, lgtm

#1393 MGMT-8992 - Separate environment variables from defaults values
  Makefile
  skipper.env
  src/assisted_test_infra/test_infra/helper_classes/config/__init__.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_config.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_entity_config.py
  src/assisted_test_infra/test_infra/helper_classes/config/controller_config.py
  src/assisted_test_infra/test_infra/utils/__init__.py
  src/assisted_test_infra/test_infra/utils/env_var.py
  src/consts/consts.py
  src/consts/env_defaults.py
  src/consts/olm_operators.py
  src/consts/resources.py
  src/deprecated_utils.py
  src/install_cluster.py
  src/start_discovery.py
  src/tests/base_kubeapi_test.py
  src/tests/base_test.py
  src/tests/config/global_configs.py
  src/tests/conftest.py
  src/tests/global_variables/__init__.py
  src/tests/global_variables/default_variables.py
  src/tests/global_variables/env_variables_defaults.py
  src/tests/global_variables/triggers.py
  src/tests/test_bootstrap_in_place.py
  src/tests/test_e2e_install.py
  src/tests/test_kube_api.py
  src/triggers/__init__.py
  src/triggers/default_triggers.py
  src/triggers/env_trigger.py
  src/triggers/olm_operators_trigger.py
Labels: size/XXL, approved, lgtm

#1474 NO-ISSUE - Fix OVNKubernetes job failure
  src/assisted_test_infra/test_infra/helper_classes/config/base_config.py
  src/triggers/default_triggers.py
Labels: approved, size/XS, lgtm

#1475 NO-ISSUE: allow usage of Rocky Linux OS
  create_full_environment.sh
  requirements.txt
  scripts/install_environment.sh
Labels: size/S, approved, lgtm

#1408 MGMT-9268: Fix kube-api conformance tests are failing
  src/tests/base_kubeapi_test.py
  src/tests/test_kube_api.py
Labels: approved, size/XS, lgtm

#1452 NO-ISSUE - Separate download_logs logs from test_infra logs
  scripts/download_logs.sh
  skipper.env
  src/assisted_test_infra/download_logs/download_logs.py
  src/service_client/__init__.py
  src/service_client/logger.py
  src/tests/test_bootstrap_in_place.py
Labels: size/M, approved, lgtm

#1485 add update_static_network_config to infra_env
  src/assisted_test_infra/test_infra/helper_classes/infra_env.py
Labels: approved, size/XS, lgtm

#1486 NO-ISSUE - Fix missing default version on specific openshift version
  src/tests/conftest.py
Labels: approved, size/XS, lgtm

#1487 NO-ISSUE - Update `arkade` domain
  scripts/install_minikube.sh
Labels: approved, size/XS, lgtm

#1489 NO-ISSUE: fix arkade DNS to the updated one
  scripts/install_minikube.sh
Labels: approved, size/XS, lgtm
