Repository openshift/assisted-test-infra, pull requests merged in 2022-03, with the labels that each got.

#1445 [release-ocm-2.4] MGMT-9197 - Fix kubeapi test
  Makefile
  discovery-infra/test_infra/utils/global_variables/global_variables.py
  discovery-infra/test_infra/utils/utils.py
  discovery-infra/tests/base_kubeapi_test.py
  discovery-infra/tests/test_kube_api.py
Labels: size/M, approved, lgtm

#1490 Terraform failed: Removing job_name from the vm name. Adding ansible …
  Dockerfile.assisted-test-infra
  terraform_files/vsphere-ci-machine/main.tf
  terraform_files/vsphere-ci-machine/variables-vsphere.tf
Labels: size/S, approved, lgtm

#1488 NO-ISSUE - Remove arkade dependency
  scripts/install_minikube.sh
Labels: size/M, approved, lgtm

#1499 NO-ISSUE: Support AGENT_TIMEOUT_START param
  README.md
  skipper.env
  src/update_assisted_service_cm.py
Labels: ok-to-test, approved, size/XS, lgtm

#1501 NO-ISSUE: Improve .flake8 rules and documentation
  .flake8
Labels: approved, size/XS, lgtm

#1482 NO-ISSUE - Remove KUBE_API duplicate environment variable
  Makefile
  scripts/download_logs.sh
  skipper.env
  src/tests/global_variables/env_variables_defaults.py
Labels: approved, size/XS, lgtm

#1497 NO-ISSUE - Go back to ocpmetal service index
  Makefile
Labels: approved, size/XS, lgtm

#1500 NO-ISSUE: Bootstrap-in-place test flow should use RHCOS images fitting the OCP version tested
  src/assisted_test_infra/test_infra/utils/release_image_utils.py
  src/deprecated_utils.py
  src/tests/test_bootstrap_in_place.py
Labels: size/L, approved, lgtm

#1504 MGMT-9486: Remove the reoute CRD so that hypershift evaluate CapabilityRoute to true
  scripts/setup_capi_env.sh
Labels: approved, size/XS, lgtm

#1503 Adding IP address output parameter - used to ssh to the machine
  terraform_files/vsphere-ci-machine/main.tf
  terraform_files/vsphere-ci-machine/output.tf
Labels: approved, size/XS, lgtm

#1506 MGMT-9471: fix sosreport gathering on BIP test
  src/tests/test_bootstrap_in_place.py
Labels: approved, size/XS, lgtm

#1510 NO-ISSUE: add ADDITIONAL_NTP_SOURCE env var to skipper
  skipper.env
Labels: approved, size/XS, lgtm

#1517 NO-ISSUE: fail earlier in case prepare for installation failed
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
Labels: approved, size/XS, lgtm

#1508 MGMT-9177: Make OVN network type for SNO
  src/triggers/default_triggers.py
Labels: approved, size/XS, lgtm

#1520 MGMT-9545 - Failed to fetch container images needed an e2e-assisted-prod job
  src/assisted_test_infra/test_infra/exceptions.py
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/utils/release_image_utils.py
  src/assisted_test_infra/test_infra/utils/utils.py
  src/assisted_test_infra/test_infra/utils/waiting.py
  src/consts/consts.py
  src/service_client/client_factory.py
  src/service_client/logger.py
  src/tests/test_bootstrap_in_place.py
Labels: size/L, approved, lgtm

#1522 NO-ISSUE - Notify on not implemented kubeapi deploy_nodes_with_install deploy target
  Makefile
Labels: approved, size/XS, lgtm

#1519 MGMT-9470: Use edge-infrastructure index
  Makefile
Labels: approved, size/XS, lgtm

#1526 NO-ISSUE - Add ODF trigger
  src/triggers/default_triggers.py
Labels: approved, size/XS, lgtm

#1498 Use hypershift-operator image for installing hypershift
  Makefile
  scripts/setup_capi_env.sh
Labels: size/M, approved, lgtm

#1529 NO-ISSUE: RHCOS ISO download links sometimes have a 302 redirect, handle it with curl
  src/tests/test_bootstrap_in_place.py
Labels: approved, size/XS, lgtm

#1528 MGMT-9484 Collect HostedControlPlane CR in capi tests gather
  scripts/download_logs.sh
Labels: approved, size/XS, lgtm

#1524 NO-ISSUE: remove deprecated client.update_hosts func
  src/assisted_test_infra/test_infra/utils/utils.py
  src/service_client/assisted_service_api.py
Labels: size/S, approved, lgtm

#1525 MGMT-9568: use client.update_host instead of update_hosts
  src/assisted_test_infra/test_infra/helper_classes/day2_cluster.py
  src/assisted_test_infra/test_infra/utils/utils.py
Labels: size/M, approved, lgtm

#1518 MGMT-9549:Trigger for remote deploy HW specs
  src/consts/consts.py
  src/tests/global_variables/default_variables.py
  src/triggers/default_triggers.py
Labels: size/S, approved, lgtm

#1527 Fixup on PR 1393
  Makefile
  README.md
Labels: size/S, approved, lgtm

#1502 MGMT-8859: The creation of cluster deployment depends on the control plane so the test should wait for thee control plane first
  src/tests/test_kube_api.py
Labels: approved, size/XS, lgtm

#1521 MGMT-9558: Adding the custom fixtures to pytest.ini file.
  src/tests/pytest.ini
Labels: approved, size/XS, lgtm

#1505 NO-ISSUE - Fix vsphere controller not implementing all abstract methods.
  src/assisted_test_infra/test_infra/__init__.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
  src/assisted_test_infra/test_infra/helper_classes/config/__init__.py
  src/assisted_test_infra/test_infra/helper_classes/config/vsphere_config.py
  src/tests/base_test.py
  src/tests/config/__init__.py
  src/tests/config/global_configs.py
Labels: size/M, approved, lgtm

#1533 NO-ISSUE - Remove unused downloaded executable
  scripts/install_minikube.sh
Labels: approved, size/XS, lgtm

#1532 MGMT-9609: Remove unused V1 patch_cluster_discovery_ignition
  src/service_client/assisted_service_api.py
Labels: size/S, approved, lgtm

#1539 NO-ISSUE: Increase libvirt wait for machine IP timeout from 360 to 600
  src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
Labels: approved, size/XS, lgtm

#1484 Add basic CLI for test infra
  Makefile
  requirements.txt
  skipper.env
  src/assisted_test_infra/test_infra/utils/env_var.py
  src/cli/__init__.py
  src/cli/__main__.py
  src/cli/application.py
  src/cli/cli_utils.py
  src/cli/commands/__init__.py
  src/cli/commands/command.py
  src/cli/commands/commands_factory.py
  src/cli/commands/env_command.py
  src/cli/commands/help_command.py
  src/cli/commands/test_command.py
  src/cli/completers.py
  src/cli/key_binding.py
  src/cli/prompt_handler.py
  src/consts/consts.py
  src/service_client/logger.py
  src/tests/config/__init__.py
  src/tests/config/global_configs.py
  src/tests/conftest.py
  src/tests/global_variables/default_variables.py
  src/tests/test_e2e_install.py
Labels: size/XL, approved, lgtm

#1543 NO-ISSUE - Fix typo on skipper.env ENABLE_KUBE_API env var
  skipper.env
Labels: approved, size/XS, lgtm

#1544 Improve IBM provision script to support RHEL
  scripts/ibmcloud_post_install.sh
Labels: approved, size/XS, lgtm

#1545 NO-ISSUE - Add junit test cases to some base fixtures
  src/tests/base_test.py
Labels: approved, size/XS, lgtm

#1554 Upgrading vsphere terraform provider to 2.1.1
  terraform_files/vsphere-ci-machine/main.tf
  terraform_files/vsphere/main.tf
Labels: approved, size/XS, lgtm

#1546 MGMT-9691: Allow overriding hypershift control plane operator image
  scripts/download_logs.sh
  src/assisted_test_infra/test_infra/helper_classes/hypershift.py
  src/tests/test_kube_api.py
Labels: size/S, approved, lgtm

#1555 Setting vsphere cluster on creation
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
Labels: approved, size/XS, lgtm

#1559 MGMT-9765 - Fix assisted-test-infra image build failure during CI
  Dockerfile.assisted-test-infra
Labels: approved, size/XS, lgtm

#1541 NO-ISSUE - Add python client version validation before running test suite
  Makefile
  src/consts/consts.py
  src/service_client/client_validator.py
  src/tests/conftest.py
Labels: size/M, approved, lgtm

#1567 NO-ISSUE - Fix random tests names while parsing assisted logs and events
  src/junit_log_parser.py
Labels: approved, size/XS, lgtm

#1568 NO-ISSUE - Update openshift default version to 4.10
  src/assisted_test_infra/test_infra/utils/utils.py
  src/tests/global_variables/env_variables_defaults.py
Labels: approved, size/XS, lgtm

#1566 MGMT-9213: Add SPOKE_NAMESPACE to skipper.env
  skipper.env
  src/tests/base_kubeapi_test.py
  src/tests/test_kube_api.py
Labels: size/M, approved, lgtm

#1570 MGMT-9822 - Fix test-infra test failure when trigger is applied twice to the same variable
  src/assisted_test_infra/test_infra/utils/env_var.py
  src/tests/global_variables/default_variables.py
Labels: size/S, approved, lgtm

#1572 MGMT-9770: Fix issue with Hashicorp RPM during test-infra image build
  Dockerfile.assisted-test-infra
Labels: approved, size/XS, lgtm

#1573 Enable HW virtualization and increase the ci machine size
  packer_files/vsphere_centos_template/variables.pkr.hcl
  terraform_files/vsphere-ci-machine/main.tf
  terraform_files/vsphere-ci-machine/variables-vsphere.tf
Labels: approved, size/XS, lgtm

#1574 MGMT-9852 - Fix image build failed during CI job
  create_full_environment.sh
  scripts/pull_dockerfile_images.sh
Labels: size/S, approved, lgtm
