Repository openshift/assisted-test-infra, pull requests merged in 2022-05, with the labels that each got.

#1637 debugging assisted service from beaker machine fixing - broke by http…
  scripts/deploy_assisted_service.sh
Labels: approved, size/XS, lgtm

#1636 [release-ocm-2.5] NO-ISSUE: Change catalog image to target ocm-2.5
  Makefile
Labels: approved, size/XS, lgtm

#1635 MGMT-10112 - Add info about how to add a new e2e test
  GUIDE.md
  README.md
Labels: size/M, approved, lgtm

#1638 NO-ISSUE: Collect nodepool CR when collecting CAPI resources
  scripts/download_logs.sh
Labels: approved, size/XS, lgtm

#1647 MGMT-9682: fix disk sizes used in various places
  src/consts/consts.py
  src/consts/olm_operators.py
  src/consts/resources.py
  terraform_files/baremetal_host/variables.tf
Labels: size/S, approved, lgtm

#1652 Log hosts' statuses while waiting for the cluster status update
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/utils/utils.py
  src/assisted_test_infra/test_infra/utils/waiting.py
Labels: size/M, approved, lgtm

#1639 MGMT-8938: Add support for bootstrap-in-place day-2 worker flow
  Makefile
  src/assisted_test_infra/resources/bootstrap_in_place/install-config.yaml
  src/assisted_test_infra/resources/bootstrap_in_place/sno-worker-install.sh
  src/assisted_test_infra/resources/bootstrap_in_place/sno-worker-live.ign.j2
  src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_entity_config.py
  src/assisted_test_infra/test_infra/helper_classes/config/nodes_config.py
  src/assisted_test_infra/test_infra/utils/oc_utils.py
  src/tests/test_bootstrap_in_place.py
  terraform_files/baremetal/main.tf
  terraform_files/baremetal/terraform.tfvars.json
  terraform_files/baremetal/variables-libvirt.tf
  terraform_files/baremetal_infra_env/main.tf
  terraform_files/baremetal_infra_env/terraform.tfvars.json
  terraform_files/baremetal_infra_env/variables-libvirt.tf
  terraform_files/none/main.tf
  terraform_files/none/terraform.tfvars.json
  terraform_files/none/variables-libvirt.tf
Labels: size/XL, approved, lgtm

#1646 MGMT-9179 - Single node bootstrap-in-place flow should use OVNKubernetes
  src/assisted_test_infra/resources/bootstrap_in_place/install-config.yaml
Labels: approved, size/XS, lgtm

#1659 revert libvirt downgrade on Rocky Linux
  scripts/install_environment.sh
Labels: size/S, approved, lgtm

#1661 [release-ocm-2.4] revert libvirt downgrade on Rocky Linux
  scripts/install_environment.sh
Labels: size/S, approved, lgtm

#1663 Always pulling referenced service image
  Makefile
  create_full_environment.sh
Labels: approved, size/XS, lgtm

#1667 NO-ISSUE - Add 4.11 to available openshift versions
  src/consts/consts.py
  src/tests/global_variables/env_variables_defaults.py
Labels: approved, size/XS, lgtm

#1634 [release-ocm-2.4] NO-ISSUE: Fix late binding job
  discovery-infra/tests/test_kube_api.py
Labels: size/S, approved, lgtm
