Repository openshift/assisted-test-infra, pull requests merged in 2022-08, with the labels that each got.

#1783 install podman from 4.0 stream on RHEL 8 machines
  scripts/install_environment.sh
Labels: size/M, approved, lgtm

#1785 MGMT-11449: govc installation from GitHub gets rate-limiter failures
  Dockerfile.assisted-test-infra
Labels: approved, size/XS, lgtm

#1784 MGMT-11491: kubeAPI flow should work with no default OCP version
  src/assisted_test_infra/test_infra/utils/utils.py
Labels: approved, size/XS, lgtm

#1790 MGMT-11580 - Make OCP 4.11 default on test-infra
  src/consts/consts.py
Labels: approved, size/XS, lgtm

#1786 MGMT-11415: add platform support to kubeapi test
  .dockerignore
  src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/agent_cluster_install.py
  src/assisted_test_infra/test_infra/tools/terraform_utils.py
  src/assisted_test_infra/test_infra/utils/kubeapi_utils.py
  src/consts/consts.py
  src/tests/base_kubeapi_test.py
  src/tests/test_kube_api.py
Labels: size/M, approved, lgtm

#1798 Set hypershift operator image only when the HYPERSHIFT_OPERATOR_IMAGE env was provided
  src/tests/test_kube_api.py
Labels: approved, size/XS, lgtm

#1799 NO-ISSUE: remove minikube from dockerignore
  .dockerignore
Labels: approved, size/XS, lgtm

#1759 MGMT-11319 - Remove redundant `destroy_nodes` when preparing nodes
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/tests/test_day2.py
Labels: approved, size/XS, lgtm

#1797 MGMT-11337: Define wildcard DNS for ingress DNSes
  src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/node_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/tests/base_test.py
  src/tests/test_kube_api.py
  terraform_files/baremetal/main.tf
  terraform_files/baremetal_host/main.tf
  terraform_files/baremetal_infra_env/main.tf
  terraform_files/none/main.tf
Labels: size/L, approved, lgtm

#1809 NO-ISSUE - Align `CONTAINER_RUNTIME_COMMAND` with `CONTAINER_COMMAND`
  Makefile
Labels: approved, size/XS, lgtm

#1789 MGMT-11321: Add nutanix support to test infra infrastructure
  Dockerfile.assisted-test-infra
  requirements.txt
  skipper.env
  src/assisted_test_infra/test_infra/__init__.py
  src/assisted_test_infra/test_infra/controllers/__init__.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/nutanix_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/config/__init__.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_nutanix_config.py
  src/assisted_test_infra/test_infra/helper_classes/config/vsphere_config.py
  src/assisted_test_infra/test_infra/helper_classes/nodes.py
  src/assisted_test_infra/test_infra/tools/terraform_utils.py
  src/consts/consts.py
  src/consts/resources.py
  src/tests/base_test.py
  src/tests/config/global_configs.py
  src/tests/global_variables/env_variables_defaults.py
  src/triggers/default_triggers.py
  terraform_files/nutanix/main.tf
  terraform_files/nutanix/variables_nutanix.tf
  terraform_files/nutanix/virtual_machines.tf
Labels: size/XL, approved, lgtm

#1808 MGMT-8890: Add support for cpu_architectures in release images
  src/assisted_test_infra/test_infra/utils/utils.py
Labels: approved, size/XS, lgtm

#1810 NO-ISSUE - Install openvpn as dependency for nutanix CI
  scripts/install_environment.sh
Labels: approved, size/XS, lgtm

#1807 Fix default value for getting vips
  src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/node_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/nutanix_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
Labels: size/S, approved, lgtm

#1811 MGMT-11852 - Update platform to none on sno installation
  Makefile
  src/triggers/default_triggers.py
Labels: approved, size/XS, lgtm
