Repository openshift/assisted-test-infra, pull requests merged in 2022-01, with the labels that each got.

#1341 Use skipper interactive env-var
  Jenkinsfile
  Jenkinsfile.download_all_logs
  Jenkinsfile.download_logs
  Jenkinsfile.test
  Makefile
  scripts/deploy_assisted_service.sh
  scripts/deploy_ui.sh
Labels: size/M, approved, lgtm

#1344 install go on py39 Dockerfile
  Dockerfile.assisted-test-infra
Labels: approved, size/XS, lgtm

#1328 MGMT-8769- Fail olm test on operator failure.
  src/assisted_test_infra/test_infra/helper_classes/config/base_config.py
  src/assisted_test_infra/test_infra/utils/operators_utils.py
  src/consts/olm_operators.py
  src/tests/base_test.py
  src/tests/test_e2e_install.py
Labels: size/L, approved, lgtm

#1343 NO-ISSUE: Fix collect_kube_api_resources to get all CRs in the array
  scripts/download_logs.sh
Labels: size/S, approved, lgtm

#1346 Use interactive mode when running skipper externally
  scripts/deploy_assisted_service.sh
Labels: approved, size/XS, lgtm

#1347 MGMT-8666 - Fix onprem logs destination in prow
  scripts/download_logs.sh
  src/junit_log_parser.py
Labels: size/S, approved, lgtm

#1348 Use Python 3.9 image for local environments
  Dockerfile.assisted-test-infra
  Dockerfile.test-infra
  Makefile
  requirements-39.txt
  requirements.txt
  skipper.env
Labels: size/M, approved, lgtm

#1349 Assign pip packages maintainers when bumping dependencies
  .github/dependabot.yml
Labels: approved, size/XS, lgtm

#1345 fix SNO installations always picking OCP 4.8
  src/tests/global_variables/triggers.py
Labels: approved, size/XS, lgtm

#1351 NO-ISSUE - Fix type checking on python 3.9
  src/assisted_test_infra/test_infra/helper_classes/config/base_config.py
Labels: approved, size/XS, lgtm

#1353 MGMT-8520 - Clear infraenv unused resources on test teardown
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/infra_env.py
  src/tests/base_test.py
Labels: size/M, approved, lgtm

#1342 MGMT-8470 - Use logger.log instead of logging library
  src/assisted_test_infra/test_infra/controllers/iptables.py
  src/assisted_test_infra/test_infra/controllers/nat_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/node.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/ssh.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/assisted_test_infra/test_infra/controllers/proxy_controller/proxy_controller.py
  src/assisted_test_infra/test_infra/helper_classes/hypershift.py
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/agent.py
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/agent_cluster_install.py
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/cluster_image_set.py
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/common.py
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/infraenv.py
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/nmstate_config.py
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/secret.py
  src/assisted_test_infra/test_infra/helper_classes/nodes.py
  src/assisted_test_infra/test_infra/tools/assets.py
  src/assisted_test_infra/test_infra/tools/concurrently.py
  src/assisted_test_infra/test_infra/tools/terraform_utils.py
  src/assisted_test_infra/test_infra/utils/kubeapi_utils.py
  src/assisted_test_infra/test_infra/utils/logs_utils.py
  src/assisted_test_infra/test_infra/utils/terraform_util.py
  src/assisted_test_infra/test_infra/utils/utils.py
  src/tests/base_test.py
  src/tests/conftest.py
  src/tests/test_kube_api.py
Labels: size/L, approved, lgtm

#1354 Revert/skipper interactive var
  Jenkinsfile
  Jenkinsfile.download_all_logs
  Jenkinsfile.download_logs
  Jenkinsfile.test
  Makefile
  scripts/deploy_assisted_service.sh
  scripts/deploy_ui.sh
Labels: size/M, approved, lgtm

#1352 NO-ISSUE: download manifests
  src/assisted_test_infra/download_logs/download_logs.py
  src/service_client/assisted_service_api.py
Labels: size/S, approved, lgtm

#1357 install assisted-service-build dependencies before using makefile
  scripts/deploy_assisted_service.sh
Labels: approved, size/XS, lgtm

#1358 Mgmt 8845 Setup capi env should wait for HyperShift to be ready
  scripts/setup_capi_provider_agent_env.sh
Labels: size/S, approved, lgtm

#1359 remove overriding ocp version when on ipv6
  src/tests/global_variables/triggers.py
Labels: approved, size/XS, lgtm

#1360 NO-ISSUE: add agent logs to sosreport
  src/assisted_test_infra/download_logs/resources/man_sosreport.sh
Labels: approved, size/XS, lgtm

#1356 MGMT-8363 - Join flaky tests results on prow spyglass
  src/junit_log_parser.py
Labels: size/S, approved, lgtm

#1367 NO-ISSUE: wrong documentation
  src/tests/base_test.py
Labels: size/S, approved, lgtm

#1368 MGMT-8888: Add agent-namespace param to the e2e test
  Makefile
  scripts/setup_capi_env.sh
  skipper.env
  src/assisted_test_infra/test_infra/helper_classes/hypershift.py
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/infraenv.py
  src/tests/test_kube_api.py
Labels: size/S, approved, lgtm

#1369 remove creating tickets based on failed CI tests
  Jenkinsfile.download_logs
Labels: approved, size/XS, lgtm

#1370 Unbound variable
  scripts/setup_capi_env.sh
  src/assisted_test_infra/test_infra/helper_classes/hypershift.py
Labels: approved, size/XS, lgtm

#1371 MGMT-8900: Update e2e test to use capi-provider-agent image from env
  src/assisted_test_infra/test_infra/helper_classes/hypershift.py
  src/tests/test_kube_api.py
Labels: size/S, approved, lgtm

#1374 NO-ISSUE: Handle case where download_log.sh fail to find the capi-provider namespace
  scripts/download_logs.sh
Labels: approved, size/XS, lgtm

#1376 MGMT-8670 - Fix deploy_nodes with CLUSTER_ID creates a new InfraEnv.
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/entity.py
  src/assisted_test_infra/test_infra/helper_classes/infra_env.py
  src/service_client/assisted_service_api.py
Labels: size/M, approved, lgtm

#1377 MGMT-7230: Add resource requirement for ODF operator
  src/consts/olm_operators.py
Labels: size/S, approved, lgtm

#1378 NO-ISSUE: Added few CRs to the CAPI_PROVIDER_CRS list in download_logs.sh
  scripts/download_logs.sh
Labels: approved, size/XS, lgtm

#1375 MGMT-8753: download logs for kube-api and hypershift flow
  scripts/download_logs.sh
  src/assisted_test_infra/download_logs/__main__.py
  src/assisted_test_infra/download_logs/download_logs.py
  src/assisted_test_infra/test_infra/helper_classes/hypershift.py
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/agent_cluster_install.py
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/cluster_deployment.py
  src/assisted_test_infra/test_infra/utils/utils.py
  src/consts/kube_api.py
  src/tests/test_kube_api.py
Labels: size/L, approved, lgtm

#1385 Remove redundant Jenkinsfiles
  Jenkinsfile.download_all_logs
  Jenkinsfile.test
Labels: size/L, approved, lgtm

#1387 MGMT-8967 - Change kubeapi test Makefile target return code
  Makefile
Labels: approved, size/XS, lgtm

#1379 NO-ISSUE - Reorganize test_kube_api.py file and remove duplicated code
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/infraenv.py
  src/tests/base_kubeapi_test.py
  src/tests/base_test.py
  src/tests/test_kube_api.py
Labels: size/XXL, approved, lgtm

#1386 MGMT-8972 - Wrap kube_api test with JunitTestSuite for creating junit xml reports
  Makefile
  src/start_discovery.py
Labels: approved, size/XS, lgtm

#1388 MGMT-8132: move bootstrap-in-place to new tests framework
  Makefile
  src/bootstrap_in_place.py
  src/start_discovery.py
  src/tests/base_test.py
  src/tests/test_bootstrap_in_place.py
Labels: size/L, approved, lgtm

#1394 MGMT-8998: Updated default HYPERSHIFT_IMAGE to quay.io/hypershift/hypershift-operator:latest
  scripts/setup_capi_env.sh
Labels: approved, size/XS, lgtm

#1389 MGMT-8105 - Make kube_api target work with the new workflow
  Makefile
  skipper.env
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/common.py
  src/assisted_test_infra/test_infra/utils/entity_name.py
  src/assisted_test_infra/test_infra/utils/utils.py
  src/consts/env_defaults.py
  src/tests/base_kubeapi_test.py
  src/tests/base_test.py
  src/tests/global_variables/env_variables_defaults.py
  src/tests/test_e2e_install.py
  src/tests/test_kube_api.py
Labels: size/L, approved, lgtm

#1391 NO-ISSUE - Add colors to logging
  src/service_client/logger.py
Labels: size/M, approved, lgtm

#1373 MGMT-8716: uses new way of configuring podman deployment
  scripts/deploy_assisted_service.sh
Labels: size/S, approved, lgtm

#1398 MGMT-9016: Adding port forwarding to assisted image service
  scripts/deploy_assisted_service.sh
  skipper.env
  src/update_assisted_service_cm.py
Labels: size/S, approved, lgtm

#1395 Revert "MGMT-7351 - Move deployment scripts from assisted-service into test-infra scripts"
  Makefile
  scripts/deploy_assisted_service.sh
  scripts/operator/README.md
  scripts/operator/common.sh
  scripts/operator/deploy.sh
  scripts/operator/destroy.sh
  scripts/operator/gather.sh
  scripts/operator/libvirt_disks.sh
  scripts/operator/mirror_utils.sh
  scripts/operator/set_ca_bundle.py
  scripts/operator/setup_assisted_operator.sh
  scripts/operator/setup_hive.sh
  scripts/operator/setup_lso.sh
  scripts/operator/upgrade/README.md
  scripts/operator/upgrade/after_upgrade.sh
  scripts/operator/upgrade/before_upgrade.sh
  scripts/operator/upgrade/upgrade.sh
  scripts/operator/utils.sh
  scripts/operator/ztp/add-remote-nodes-playbook.yaml
  scripts/operator/ztp/add_day2_remote_nodes.sh
  scripts/operator/ztp/agentClusterInstall.j2
  scripts/operator/ztp/assisted-installer-crds-playbook.yaml
  scripts/operator/ztp/baremetalHost.j2
  scripts/operator/ztp/clusterDeployment.j2
  scripts/operator/ztp/clusterImageSet.j2
  scripts/operator/ztp/deploy_spoke_cluster.sh
  scripts/operator/ztp/infraEnv.j2
Labels: size/XXL, approved, lgtm

#1404 MGMT-9037: Use a cheaper packet plan for baremetalds-sno-workflow
  src/tests/test_bootstrap_in_place.py
Labels: ok-to-test, approved, size/XS, lgtm

#1407 MGMT-7105: adding packer binary to the test-infra image
  Dockerfile.assisted-test-infra
Labels: approved, size/XS, lgtm

#1410 NO-ISSUE: use stream8 distribution as centos 8 is EOL
  Dockerfile.assisted-test-infra
Labels: approved, size/XS, lgtm
