Repository openshift/assisted-test-infra, pull requests merged in 2023-05, with the labels that each got.

#2138 MGMT-14411: Fix for OCM 2.8 test failures
  Makefile
Labels: approved, size/XS, lgtm, jira/valid-reference

#2137 MGMT-14518: Fix vSphere and Nutanix teardown
  src/tests/test_targets.py
Labels: size/M, approved, lgtm, jira/valid-reference

#2147 NO-ISSUE: ensure ADDITIONAL_MANIFEST_DIR exists
  Makefile
Labels: approved, size/XS, lgtm, jira/valid-reference

#2145 MGMT-14563: Make deploy_nodes target to deploy nodes without networking
  Makefile
  README.md
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/day2_cluster.py
  src/assisted_test_infra/test_infra/helper_classes/entity.py
  src/tests/test_targets.py
Labels: size/M, approved, lgtm, jira/valid-reference

#2151 MGMT-14602: Add MCE operator support
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/utils/operators_utils.py
  src/consts/olm_operators.py
  src/triggers/default_triggers.py
  src/triggers/env_trigger.py
  src/triggers/olm_operators_trigger.py
Labels: size/L, approved, lgtm, jira/valid-reference

#2153 MGMT-14355: Make OCP 4.13 default on test-infra
  src/consts/consts.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2157 MGMT-14369: Add 4.14 as valid version on test-infra
  src/consts/consts.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2146 MGMT-14568: Ensure test-infra image is built before trying to deploy
  Makefile
Labels: approved, size/XS, lgtm, jira/valid-reference

#2158 Revert "MGMT-14568: Ensure test-infra image is built before trying to…
  Makefile
Labels: approved, size/XS, lgtm, jira/valid-reference

#2150 Add support for ip6tables to handle ipv6 rules
  skipper.yaml
  src/assisted_test_infra/test_infra/controllers/iptables.py
Labels: ok-to-test, size/S, approved, lgtm

#2160 NO-ISSUE: Update vsphere and nutanix packer machine RAM to 16GiB
  README.md
  packer_files/nutanix_centos_template/variables.pkr.hcl
  packer_files/vsphere_centos_template/variables.pkr.hcl
  terraform_files/nutanix-ci-machine/variables-nutanix.tf
  terraform_files/vsphere/variables-vsphere.tf
Labels: size/S, approved, lgtm, jira/valid-reference

#2161 MGMT-14660: Fail on pending input during installation instead of waiting for timeout
  src/assisted_test_infra/test_infra/exceptions.py
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/utils/waiting.py
  src/tests/test_e2e_install.py
Labels: size/M, approved, lgtm, jira/valid-reference

#2162 NO-ISSUE: Remove extra disk from mce test
  src/consts/olm_operators.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2163 No issue remove extra disk from SNO MCE test
  src/consts/olm_operators.py
Labels: approved, size/XS, lgtm

#2164 MGMT-14674: Add operators status log when waiting for operators to finish
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/utils/operators_utils.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2165 MGMT-14518: Fix kubeapi vSphere and Nutanix teardown
  Makefile
  scripts/override_os_images.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/tests/test_targets.py
Labels: size/M, approved, lgtm, jira/valid-reference

#2169 Add timeout on wait_for_hosts_stage
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
Labels: approved, size/XS, lgtm

#2171 Update old image used by upgrade agent test
  src/tests/test_upgrade_agent.py
Labels: approved, size/XS, lgtm

#2174 MGMT-14518: Fix kubeapi vSphere and Nutanix teardown
  Makefile
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/tests/test_targets.py
Labels: size/M, approved, lgtm, jira/valid-reference

#2179 MGMT-14737: Add base terraform controller for both vsphere and nutanix.
  src/assisted_test_infra/test_infra/controllers/node_controllers/__init__.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/node_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/nutanix_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/tf_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
  src/tests/global_variables/env_variables_defaults.py
Labels: size/L, approved, lgtm, jira/valid-reference
