Repository openshift/assisted-test-infra, pull requests merged in 2023-07, with the labels that each got.

#2216 Add support to update iso file for set_boot_order
  src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/node.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/node_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/nutanix_controller.py
Labels: ok-to-test, size/S, approved, lgtm

#2217 MGMT-15131: Raise more indicative exception on operator deployment failure
  src/assisted_test_infra/test_infra/utils/operators_utils.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2220 NO-ISSUE: Add info to the raised exception instead of exception chaining
  src/assisted_test_infra/test_infra/utils/operators_utils.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2221 Fix paramiko incorrectly auto-detects private key method
  src/assisted_test_infra/test_infra/controllers/node_controllers/ssh.py
Labels: approved, size/XS, lgtm

#2225 Group dependabot updates in one PR
  .github/dependabot.yml
Labels: approved, size/XS, lgtm

#2200 MGMT-14945: Setup CCM manifests for OCI
  ansible_files/roles/oci/setup_oci_for_test_infra/tasks/custom_manifests.yml
  ansible_files/roles/oci/setup_oci_for_test_infra/tasks/main.yml
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/assisted-additional-config.j2
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/oci-ccm-00-namespace.yaml.j2
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/oci-ccm-01-service-account.yaml.j2
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/oci-ccm-02-cluster-role.yaml.j2
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/oci-ccm-03-cluster-role-binding.yaml.j2
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/oci-ccm-04-cloud-controller-manager-config.yaml.j2
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/oci-ccm-05-daemon-set.yaml.j2
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/oci-kubelet-providerid.bu.j2
  ansible_files/roles/oci/setup_oci_for_test_infra/vars/main.yml
Labels: size/L, approved, lgtm, jira/valid-reference

#2232 Add MCE validation time out
  src/consts/consts.py
Labels: approved, size/XS, lgtm

#2228 NO-ISSUE: Delete terraform folder after cleaning all resources, add logs to destroy_available_terraform.
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/tools/terraform_utils.py
  src/tests/test_targets.py
Labels: size/S, approved, lgtm, jira/valid-reference

#2205 NO-ISSUE: Update nutanix terraform version
  terraform_files/nutanix/main.tf
Labels: approved, size/XS, lgtm, jira/valid-reference

#2234 NO-ISSUE: Fix issue that prevent deploying nodes on platform different from cluster platform
  src/tests/base_test.py
  src/tests/test_targets.py
Labels: size/M, approved, lgtm, jira/valid-reference

#2236 MCE operator event
  src/consts/consts.py
Labels: approved, size/XS, lgtm

#2233 MGMT-15312: Create policy for OCI CCM in terraform
  terraform_files/oci/03_compute.tf
  terraform_files/oci/variables.tf
Labels: size/M, approved, lgtm, jira/valid-reference

#2159 MGMT-14651: Add the option to create multiple disks on vSphere platform installation
  terraform_files/vsphere/main.tf
  terraform_files/vsphere/variables-vsphere.tf
Labels: size/M, approved, lgtm, jira/valid-reference
