Repository openshift/assisted-test-infra, pull requests merged in 2023-08, with the labels that each got.

#2240 Fix must-gather extension to '*.tar.gz'
  src/assisted_test_infra/download_logs/download_logs.py
Labels: approved, size/XS, lgtm

#2245 MGMT-15571: Allow to re-apply terraform files in case of failure
  skipper.env
  src/assisted_test_infra/test_infra/tools/terraform_utils.py
  src/consts/consts.py
  src/consts/env_defaults.py
Labels: size/S, approved, lgtm, jira/valid-reference

#2235 Fix assets.py listAllNetworks
  src/assisted_test_infra/test_infra/tools/assets.py
Labels: ok-to-test, size/S, approved, lgtm

#2248 NO-ISSUE: Use a regex to select OS image in OCI
  terraform_files/oci-ci-machine/00_main.tf
  terraform_files/oci-ci-machine/03_compute.tf
  terraform_files/oci-ci-machine/variables.tf
  terraform_files/oci/00_main.tf
Labels: size/M, approved, lgtm, jira/valid-reference
