Repository openshift/assisted-test-infra, pull requests merged in 2023-11, with the labels that each got.

#2300 MGMT-16153: update utc call
  .gitignore
  src/tests/test_upgrade_agent.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2301 MGMT-16078: Add 4.15 as valid version
  src/consts/consts.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2303 NO-ISSUE: Upgrade to terraform 1.6.3
  Dockerfile.assisted-test-infra
Labels: approved, size/XS, lgtm, jira/valid-reference

#2294 MGMT-15088: Add multi VIP support
  src/assisted_test_infra/test_infra/controllers/node_controllers/nutanix_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/tf_controller.py
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_cluster_config.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_nodes_config.py
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/agent_cluster_install.py
  src/service_client/assisted_service_api.py
  src/tests/base_test.py
  src/tests/test_kube_api.py
  terraform_files/baremetal/main.tf
  terraform_files/baremetal/variables-libvirt.tf
  terraform_files/none/variables-libvirt.tf
Labels: size/L, approved, lgtm, jira/valid-reference

#2306 Fix api_vip for update_oc_config function
  src/tests/base_test.py
Labels: ok-to-test, size/S, approved, lgtm

#2309 MULTIARCH-3980: Add new env vars for s390x support
  skipper.env
  src/tests/global_variables/env_variables_defaults.py
Labels: ok-to-test, size/S, approved, lgtm, jira/valid-reference

#2308 Allow to change iptables rules without changing nodes state
  src/consts/consts.py
  src/tests/base_test.py
Labels: ok-to-test, size/S, approved, lgtm

#2310 MGMT-16244: Fix Day2 multi vips test
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/tests/base_test.py
Labels: size/S, approved, lgtm, jira/valid-reference

#2313 NO-ISSUE: adding wait for arm instance
  ansible_files/roles/equinix/heterogeneous_create_infra/defaults/main.yaml
  ansible_files/roles/equinix/heterogeneous_create_infra/tasks/main.yml
  ansible_files/roles/equinix/heterogeneous_create_infra/tasks/wait_for_instance.yaml
  scripts/install_environment.sh
Labels: size/S, approved, lgtm, jira/valid-reference

#2315 MGMT-16287: Remove_api_vip and ingress_vip
  src/assisted_test_infra/test_infra/controllers/node_controllers/nutanix_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/tf_controller.py
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_cluster_config.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_nodes_config.py
  src/assisted_test_infra/test_infra/helper_classes/day2_cluster.py
  src/assisted_test_infra/test_infra/tools/terraform_utils.py
Labels: size/M, approved, lgtm, jira/valid-reference

#2320 [release-ocm-2.9] NO-ISSUE: Upgrade pip ocm 2.9
  scripts/install_environment.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#2324 MGMT-16319: Create OCI cluster nodes with iSCSI boot volume
  skipper.env
  src/assisted_test_infra/test_infra/helper_classes/config/base_oci_config.py
  src/tests/global_variables/env_variables_defaults.py
  terraform_files/oci/02_custom_image.tf
  terraform_files/oci/variables.tf
Labels: size/M, approved, lgtm, jira/valid-reference

#2325 NO-ISSUE: add avishayt as approver
  OWNERS
Labels: approved, size/XS, lgtm, jira/valid-reference
