Repository openshift/assisted-test-infra, pull requests merged in 2023-12, with the labels that each got.

#2323 MGMT-16318: test external platform
  Makefile
  README.md
  skipper.env
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_entity_config.py
  src/consts/consts.py
  src/consts/env_defaults.py
  src/tests/base_test.py
  src/tests/global_variables/env_variables_defaults.py
  src/triggers/default_triggers.py
Labels: size/M, approved, lgtm, jira/valid-reference

#2317 MULTIARCH-3980: Add new Controller (as stub) for zVM
  src/assisted_test_infra/test_infra/controllers/node_controllers/__init__.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/zvm_controller.py
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/tests/base_test.py
Labels: size/L, ok-to-test, approved, lgtm, jira/valid-reference

#2329 NO-ISSUE: add the ability to update installer args
  README.md
  skipper.env
  src/assisted_test_infra/test_infra/helper_classes/base_cluster.py
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_infra_env_config.py
  src/assisted_test_infra/test_infra/helper_classes/infra_env.py
  src/tests/global_variables/env_variables_defaults.py
Labels: size/S, approved, lgtm, jira/valid-reference

#2332 MGMT-15695: check tf_platform to know if LB is required
  src/assisted_test_infra/test_infra/controllers/node_controllers/node_controller.py
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2334 MGMT-16319: enable serial console in OCI to ease debugging
  README.md
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/assisted-additional-config.j2
Labels: approved, size/XS, lgtm, jira/valid-reference

#2333 Add function name caller to test-infra logs
  src/service_client/logger.py
Labels: needs-ok-to-test, approved, size/XS, lgtm

#2335 MGMT-15695: Use oci external integration
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/assisted-additional-config.j2
Labels: approved, size/XS, lgtm, jira/valid-reference

#2338 Fix thread id in test-infra.log file
  src/service_client/logger.py
Labels: needs-ok-to-test, approved, size/XS, lgtm

#2341 MGMT-16399: Use plural vips in test environment variables
  skipper.env
  src/tests/global_variables/env_variables_defaults.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2344 MGMT-16332: add multi-disk for none platform deployment
  terraform_files/none/main.tf
  terraform_files/none/variables-libvirt.tf
Labels: size/S, approved, lgtm, jira/valid-reference

#2345 Add set_ingress_and_api_vips function to cluster
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
Labels: needs-ok-to-test, approved, size/XS, lgtm

#2347 MGMT-15772: Moving Equinix to use Metros
  terraform_files/equinix-ci-machine/main.tf
  terraform_files/equinix-ci-machine/variables_equinix.tf
Labels: approved, size/XS, lgtm, jira/valid-reference
