Repository openshift/assisted-test-infra, pull requests merged in 2023-09, with the labels that each got.

#2253 MGMT-14094: Cleanup dangling resources in OCI
  ansible_files/oci_generic_cleanup_playbook.yml
  ansible_files/roles/oci/cleanup_resources/defaults/main.yml
  ansible_files/roles/oci/cleanup_resources/tasks/main.yml
Labels: size/L, approved, lgtm, jira/valid-reference

#2257 MGMT-14094: Fix oci cleanup
  ansible_files/ansible.cfg
  ansible_files/oci_generic_cleanup_playbook.yml
  ansible_files/roles/oci/cleanup_resources/defaults/main.yml
Labels: size/S, approved, lgtm, jira/valid-reference

#2260 MGMT-15703: Update vsphere ci machine base image and update packer version
  Dockerfile.assisted-test-infra
  packer_files/vsphere_centos_template/variables.pkr.hcl
Labels: approved, size/XS, lgtm, jira/valid-reference

#2270 MGMT-14094: Cleanup network load balancers in OCI
  ansible_files/roles/oci/cleanup_resources/tasks/main.yml
Labels: approved, size/XS, lgtm, jira/valid-reference

#2271 MGMT-15707: Add s390x trigger
  src/consts/consts.py
  src/triggers/default_triggers.py
Labels: ok-to-test, size/S, approved, lgtm, jira/valid-reference

#2272 MGMT-14094: Manage case when no resources are found in OCI
  ansible_files/roles/oci/cleanup_resources/defaults/main.yml
  ansible_files/roles/oci/cleanup_resources/tasks/cleanup_resources.yml
  ansible_files/roles/oci/cleanup_resources/tasks/main.yml
Labels: size/L, approved, lgtm, jira/valid-reference
