Repository openshift/assisted-test-infra, pull requests merged in 2023-04, with the labels that each got.

#2116 NO-ISSUE: Fix SOS report exception message format
  src/assisted_test_infra/download_logs/download_logs.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2122 Add support for update_install_config
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/service_client/assisted_service_api.py
Labels: ok-to-test, approved, size/XS, lgtm

#2127 NO-ISSUE: Fix readme file
  README.md
Labels: approved, size/XS, jira/valid-reference

#2126 Add SSHException catch when ssh_connection
  src/assisted_test_infra/test_infra/controllers/node_controllers/node.py
Labels: needs-ok-to-test, approved, size/XS, lgtm

#2130 Don't crash on non-binding infra-envs
  src/service_client/assisted_service_api.py
Labels: approved, size/XS, lgtm

#2025 NO-ISSUE: Fix parsing olm operator env var list
  src/assisted_test_infra/test_infra/utils/operators_utils.py
  src/tests/global_variables/env_variables_defaults.py
Labels: approved, size/XS, lgtm, jira/valid-reference
