Repository openshift/assisted-test-infra, pull requests merged in 2023-01, with the labels that each got.

#1974 MGMT-13089: is_update_needed should return true if the cluster logs_i…
  src/assisted_test_infra/download_logs/download_logs.py
Labels: size/S, approved, lgtm

#1980 Allow injecting additional files in BIP test
  skipper.env
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_cluster_config.py
  src/tests/global_variables/env_variables_defaults.py
  src/tests/test_bootstrap_in_place.py
Labels: size/S, approved, lgtm

#1988 Setting minikube registry addon to use images from quay.io
  scripts/hub-cluster/minikube.sh
Labels: approved, size/XS, lgtm

#1992 MGMT-13300: Add support with 4.13 dev preview images
  src/consts/consts.py
Labels: approved, size/XS, lgtm

#1987 Update inject_bootstrap
  .gitignore
  Makefile
  README.md
  skipper.env
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_cluster_config.py
  src/tests/global_variables/env_variables_defaults.py
  src/tests/test_bootstrap_in_place.py
Labels: size/M, approved, lgtm

#2002 MGMT-13346: Validate that users are not running directly from /root
  Makefile
  README.md
Labels: approved, size/XS, lgtm

#1998 MGMT-12976: Make OCP 4.12 default on test-infra
  src/consts/consts.py
Labels: approved, size/XS, lgtm

#2000 Revert "Bump terraform-provider-libvirt to v0.7.1"
  terraform_files/baremetal/main.tf
  terraform_files/baremetal_host/main.tf
  terraform_files/baremetal_infra_env/main.tf
  terraform_files/none/main.tf
Labels: approved, size/XS, lgtm

#2001 Fix podman container names on gather
  scripts/download_logs.sh
Labels: approved, size/XS, lgtm

#1999 MGMT-13341: Use assisted service client wheel
  Dockerfile.assisted-test-infra
Labels: approved, size/XS, lgtm

#1989 MGMT-13210: only pull relevant OS images
  scripts/deploy_assisted_service.sh
  scripts/override_os_images.py
  scripts/override_release_images.py
  src/assisted_test_infra/test_infra/utils/release_image_utils.py
  src/assisted_test_infra/test_infra/utils/utils.py
  src/service_client/logger.py
Labels: size/L, approved, lgtm

#2006 MGMT-12477: Validate that cluster platform is exists in `supported_platforms` API call result
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/service_client/assisted_service_api.py
  src/tests/base_test.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2007 MGMT-12996: fix os-override when no OCP version specified
  scripts/override_os_images.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#1983 MGMT-11111: refactor day2 cluster code
  src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/node_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/assisted_test_infra/test_infra/helper_classes/base_cluster.py
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/day2_cluster.py
  src/assisted_test_infra/test_infra/helper_classes/nodes.py
  src/tests/base_test.py
  src/tests/test_day2.py
Labels: size/XL, approved, lgtm, jira/valid-reference

#2008 MGMT-13438: Fix NetworkType trigger overrides parametrized values
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/tests/global_variables/env_variables_defaults.py
  src/triggers/default_triggers.py
Labels: size/S, approved, lgtm, jira/valid-reference

#1981 BIP: support injecting additional manifests
  Makefile
  skipper.env
  src/tests/test_bootstrap_in_place.py
Labels: size/S, approved, lgtm

#1943 MGMT-11712: Gather logs using sos report on nodes
  src/assisted_test_infra/download_logs/download_logs.py
  src/assisted_test_infra/download_logs/resources/man_sosreport.sh
  src/assisted_test_infra/test_infra/controllers/node_controllers/nutanix_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
Labels: size/L, approved, lgtm, jira/valid-reference

#2016 [release-ocm-2.7] Backport fix_uid.sh script
  Dockerfile.assisted-test-infra
Labels: approved, size/XS, lgtm

#2018 [release-ocm-2.7] Update default tag for index and service
  Makefile
Labels: approved, size/XS, lgtm
