Repository openshift/assisted-test-infra, pull requests merged in 2023-02, with the labels that each got.

#2027 Makefile: _destroy_terraform should actually run terraform
  Makefile
Labels: approved, size/XS, lgtm

#2023 Use sudo for installation of kind
  scripts/hub-cluster/kind/kind.sh
Labels: ok-to-test, approved, size/XS, lgtm

#2024 Use sudo when installing oc client
  scripts/install_k8s_clients.sh
Labels: ok-to-test, approved, size/XS, lgtm

#2028 MGMT-13247: Support alternative libvirt URI
  src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_terraform_config.py
  src/assisted_test_infra/test_infra/tools/assets.py
  src/consts/consts.py
Labels: size/M, approved, lgtm, jira/valid-reference

#2036 NO-ISSUE: update libvirt hook to be lighter
  scripts/install_environment.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#2026 Add waiter for ssh to nodes
  src/assisted_test_infra/test_infra/helper_classes/nodes.py
Labels: ok-to-test, size/S, approved, lgtm

#2009 MGMT-13379: dedicated terraform stack for day2 cluster
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/assisted_test_infra/test_infra/helper_classes/base_cluster.py
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_day2_cluster_config.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_nodes_config.py
  src/assisted_test_infra/test_infra/helper_classes/day2_cluster.py
  src/tests/base_test.py
  terraform_files/baremetal/main.tf
  terraform_files/baremetal/variables-libvirt.tf
Labels: size/XL, approved, lgtm, jira/valid-reference

#2037 MGMT-12442: Support alternative cpu architectures
  README.md
  skipper.env
  src/assisted_test_infra/test_infra/helper_classes/base_cluster.py
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_day2_cluster_config.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_entity_config.py
  src/assisted_test_infra/test_infra/helper_classes/day2_cluster.py
  src/assisted_test_infra/test_infra/helper_classes/infra_env.py
  src/tests/global_variables/env_variables_defaults.py
Labels: size/M, approved, lgtm, jira/valid-reference

#2038 MGMT-12442: Sync iso images between heterogeneous hosts
  ansible_files/ansible.cfg
  ansible_files/equinix_heterogeneous_create_infra_playbook.yml
  ansible_files/roles/common/setup_sftp_share/defaults/main.yml
  ansible_files/roles/common/setup_sftp_share/tasks/main.yml
  ansible_files/roles/common/setup_sftp_share/templates/rclone.service.j2
  ansible_files/roles/common/setup_ssh_key_pair/defaults/main.yml
  ansible_files/roles/common/setup_ssh_key_pair/tasks/main.yml
  ansible_files/roles/common/setup_ssh_key_pair/templates/config.j2
Labels: size/L, approved, lgtm, jira/valid-reference

#2045 MGMT-13642: bump python-libvirt library to handle build failure
  requirements.txt
Labels: approved, size/XS, lgtm, jira/valid-reference

#2042 MGMT-13247: Export day2 configuration
  ansible_files/equinix_heterogeneous_create_infra_playbook.yml
  ansible_files/roles/common/setup_ipip_tunnel/tasks/main.yml
  ansible_files/roles/common/setup_ssh_key_pair/defaults/main.yml
  ansible_files/roles/common/setup_ssh_key_pair/tasks/main.yml
  ansible_files/roles/test-infra/export-heterogeneous-day2-configuration/defaults/main.yml
  ansible_files/roles/test-infra/export-heterogeneous-day2-configuration/tasks/main.yml
  ansible_files/roles/test-infra/export-heterogeneous-day2-configuration/templates/assisted-additional-config.j2
Labels: size/L, approved, lgtm, jira/valid-reference

#2047 [release-ocm-2.6] MGMT-13642: bump python-libvirt library to handle build failure (#2045)
  requirements.txt
Labels: approved, size/XS, lgtm, jira/valid-reference

#2044 MGMT-13247: day2 controller can target another libvirt node
  skipper.env
  src/assisted_test_infra/test_infra/helper_classes/config/base_day2_cluster_config.py
  src/tests/base_test.py
  src/tests/global_variables/env_variables_defaults.py
Labels: size/M, approved, lgtm, jira/valid-reference

#2048 NO-ISSUE: Best effort deletion of iptables rules
  scripts/install_environment.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#2043 MGMT-12442: Setup libvirt hook on ARM machine
  ansible_files/roles/common/setup_libvirtd/files/allow-cross-network-traffic.sh
  ansible_files/roles/common/setup_libvirtd/handlers/main.yml
  ansible_files/roles/common/setup_libvirtd/tasks/main.yml
  scripts/install_environment.sh
Labels: size/M, approved, lgtm, jira/valid-reference

#2031 Add test which destroys targets via terraform
  Makefile
  src/assisted_test_infra/test_infra/controllers/node_controllers/nutanix_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
  src/assisted_test_infra/test_infra/tools/terraform_utils.py
  src/tests/base_test.py
  src/tests/test_targets.py
Labels: size/M, approved, lgtm

#2057 Fix ssh waiter - catch SSHException
  src/assisted_test_infra/test_infra/helper_classes/nodes.py
Labels: needs-ok-to-test, approved, size/XS, lgtm

#2058 NO-ISSUE: remove setup_capi_env
  Makefile
  scripts/setup_capi_env.sh
Labels: size/M, approved, lgtm, jira/valid-reference

#2059 packer: update vspher params
  packer_files/vsphere_centos_template/sources.pkr.hcl
Labels: approved, size/XS, lgtm

#2060 MGMT-12442: Make service URL cutomizable
  ansible_files/equinix_heterogeneous_create_infra_playbook.yml
  ansible_files/roles/test-infra/export-heterogeneous-day2-configuration/templates/assisted-additional-config.j2
  scripts/deploy_assisted_service.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#2046 scripts: allow overriding base images via OS_IMAGE env var
  scripts/override_os_images.py
Labels: size/S, approved, lgtm

#2062 MGMT-12442: Fix DHCP limit range XSLT
  terraform_files/limit_ip_dhcp_range.xsl
Labels: approved, size/XS, lgtm, jira/valid-reference

#2063 NO-ISSUE: Removing old Makefile target
  Makefile
Labels: approved, size/XS, lgtm, jira/valid-reference

#2061 MGMT-12442: Use SCSI drives instead of IDE
  src/tests/test_bootstrap_in_place.py
  terraform_files/baremetal_host/consolemodel.xsl
  terraform_files/baremetal_host/libvirt_domain_custom.xsl
  terraform_files/baremetal_host/main.tf
Labels: size/M, approved, lgtm, jira/valid-reference

#2054 MGMT-12442: Use arm plan to run heterogeneous test
  ansible_files/equinix_heterogeneous_create_infra_playbook.yml
  ansible_files/roles/common/setup_ipip_tunnel/tasks/main.yml
  ansible_files/roles/equinix/export_primary_device_connection_details/files/fix-uid.sh
  ansible_files/roles/equinix/export_primary_device_connection_details/files/packet-conf.sh
  ansible_files/roles/equinix/export_primary_device_connection_details/tasks/main.yml
  ansible_files/roles/equinix/heterogeneous_create_infra/defaults/main.yaml
  ansible_files/roles/test-infra/export-heterogeneous-day2-configuration/templates/assisted-additional-config.j2
  terraform_files/equinix-ci-machine/main.tf
Labels: size/M, approved, lgtm, jira/valid-reference

#2067 MGMT-13792: Setup proxy when downloading logs
  src/assisted_test_infra/download_logs/resources/man_sosreport.sh
Labels: size/S, approved, lgtm, jira/valid-reference

#2070 NO-ISSUE: Add test which destroys targets via terraform
  Makefile
  src/assisted_test_infra/test_infra/controllers/node_controllers/nutanix_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
  src/assisted_test_infra/test_infra/tools/terraform_utils.py
  src/tests/base_test.py
  src/tests/test_targets.py
Labels: size/M, approved, lgtm, jira/valid-reference
