Repository openshift/assisted-test-infra, pull requests merged in 2023-03, with the labels that each got.

#2072 MGMT-13792: fix download_logs for OCP <= 4.10
  src/assisted_test_infra/download_logs/resources/man_sosreport.sh
Labels: size/S, approved, lgtm, jira/valid-reference

#2053 Add minikube controller k8 client wrapper to allow upgrade and scaleup
  src/assisted_test_infra/test_infra/controllers/__init__.py
  src/assisted_test_infra/test_infra/controllers/assisted_installer_infra_controller.py
  src/consts/consts.py
  src/tests/base_test.py
  src/tests/global_variables/env_variables_defaults.py
Labels: size/L, ok-to-test, approved, lgtm

#2017 bootstrap_in_place: fix number of params when running butane
  src/tests/test_bootstrap_in_place.py
Labels: approved, size/XS, lgtm

#2073 MGMT-12454: Dump inventory to get sosreport from ARM machine
  ansible_files/roles/common/setup_libvirtd/tasks/main.yml
  ansible_files/roles/equinix/export_primary_device_connection_details/tasks/main.yml
  ansible_files/roles/equinix/export_primary_device_connection_details/templates/ci-machine-config.sh.j2
  ansible_files/roles/equinix/export_primary_device_connection_details/templates/inventory.j2
Labels: size/S, approved, lgtm, jira/valid-reference

#2081 Allow reading unregistered cluster details
  src/service_client/assisted_service_api.py
Labels: approved, size/XS, lgtm

#2080 Day2 post installation triggers node reboot while addding csr
  src/assisted_test_infra/test_infra/helper_classes/day2_cluster.py
Labels: ok-to-test, approved, size/XS, lgtm

#2082 Revert "Allow reading unregistered cluster details"
  src/service_client/assisted_service_api.py
Labels: approved, size/XS, lgtm

#2083 Allow reading unregistered cluster details
  src/assisted_test_infra/download_logs/download_logs.py
  src/service_client/assisted_service_api.py
Labels: size/S, approved, lgtm

#2091 bump skipper to v2.0.0
  scripts/install_environment.sh
Labels: approved, size/XS, lgtm

#2093 Improve usability of download-logs
  scripts/download_logs.sh
Labels: size/S, approved, lgtm

#2092 MGMT-14001: Generate events.html as standalone file
  src/assisted_test_infra/download_logs/download_logs.py
  src/assisted_test_infra/download_logs/events.html
  src/assisted_test_infra/download_logs/events.html.j2
Labels: size/L, approved, lgtm, jira/valid-reference

#2094 Update skipper.env with AI_BASE_VERSION for agent upgrade versions.
  skipper.env
Labels: needs-ok-to-test, approved, size/XS, lgtm

#2099 Do not download kubeconfig if must-gather wasn't requested
  src/assisted_test_infra/download_logs/download_logs.py
Labels: approved, size/XS, lgtm

#2100 Fix inspection of deleted clusters
  src/assisted_test_infra/download_logs/download_logs.py
Labels: size/S, approved, lgtm

#2102 Add function call to cluster ignore_validation
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
Labels: ok-to-test, size/S, approved, lgtm

#2101 Fix stale references to infra-envs
  src/assisted_test_infra/download_logs/download_logs.py
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/service_client/assisted_service_api.py
Labels: size/S, approved, lgtm

#2103 MGMT-14117: Revert "Improve usability of download-logs"
  scripts/download_logs.sh
Labels: size/S, approved, lgtm, jira/valid-reference

#2089 NO-ISSUE: Fix multiple bugs
  src/assisted_test_infra/test_infra/helper_classes/config/base_cluster_config.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_config.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_infra_env_config.py
  src/tests/config/global_configs.py
  src/tests/test_bootstrap_in_place.py
Labels: size/S, approved, lgtm, jira/valid-reference

#2108 NO-ISSUE: Fix service remote debugger
  scripts/deploy_assisted_service.sh
Labels: approved, size/XS, lgtm, jira/valid-reference
