Repository openshift/assisted-test-infra, pull requests merged in 2023-06, with the labels that each got.

#2183 MGMT-14808: Fallback to local default OCP version in case that there are no service present
  src/assisted_test_infra/test_infra/utils/utils.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2182 Don't use non existing image for agent upgrade test
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/utils/waiting.py
  src/tests/test_upgrade_agent.py
Labels: size/M, approved, lgtm

#2184 MGMT-14819: Allow use Optional type hint in parameterized test
  src/assisted_test_infra/test_infra/helper_classes/config/base_config.py
Labels: size/S, approved, lgtm, jira/valid-reference

#2185 MGMT-14823: Allow installing MetalLB operator using test-infra
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/consts/__init__.py
  src/consts/olm_operators.py
  src/triggers/default_triggers.py
Labels: size/M, approved, lgtm, jira/valid-reference

#2191 MGMT-14737: Add Support with Oracle Linux
  scripts/create_full_environment.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#2129 MGMT-14092: Add ansible and terraform to provison CI machine on OCI
  Dockerfile.assisted-test-infra
  ansible_files/oci_generic_create_ci_machine_playbook.yml
  ansible_files/oci_generic_destroy_ci_machine_playbook.yml
  ansible_files/roles/common/setup_ssh_key_pair/tasks/main.yml
  ansible_files/roles/common/setup_ssh_key_pair/templates/config.j2
  ansible_files/roles/oci/create_infra/tasks/main.yml
  ansible_files/roles/oci/create_infra/templates/terraform.tfvars.j2
  ansible_files/roles/oci/destroy_infra/tasks/main.yml
  ansible_files/roles/oci/export_connection_details/defaults/main.yml
  ansible_files/roles/oci/export_connection_details/files/fix-uid.sh
  ansible_files/roles/oci/export_connection_details/tasks/main.yml
  ansible_files/roles/oci/export_connection_details/templates/ci-machine-config.sh.j2
  ansible_files/roles/oci/export_connection_details/templates/inventory.j2
  ansible_files/roles/oci/setup_oci_for_test_infra/tasks/main.yml
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/assisted-additional-config.j2
  ansible_files/vars/ci_oci_infrastucture.yml
  ansible_files/vars/standalone_oci_sample.yml
  terraform_files/oci-ci-machine/00_main.tf
  terraform_files/oci-ci-machine/01_networking.tf
  terraform_files/oci-ci-machine/02_network_security_groups.tf
  terraform_files/oci-ci-machine/03_compute.tf
  terraform_files/oci-ci-machine/output.tf
  terraform_files/oci-ci-machine/variables.tf
Labels: size/XL, approved, lgtm, jira/valid-reference

#2190 MGMT-14630: removing support for openshift version <= 4.8
  src/consts/consts.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2193 MGMT-14906: Enable ODF Support and Prepare for OCS Removal
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/consts/consts.py
  src/consts/olm_operators.py
  src/triggers/default_triggers.py
Labels: size/S, approved, lgtm, jira/valid-reference

#2192 Increase pending user input timeout to 45 minutes
  src/consts/consts.py
Labels: ok-to-test, approved, size/XS, lgtm

#2199 NO-ISSUE: Fix vsphere kubeapi CI teardown for ocm-2.7
  Makefile
Labels: approved, size/XS, lgtm, jira/valid-reference

#2195 Enabling use all parameter of list events
  src/assisted_test_infra/test_infra/helper_classes/events_handler.py
  src/service_client/assisted_service_api.py
Labels: approved, size/XS, lgtm

#2139 Extend and refactor verify_logs_uploaded
  src/assisted_test_infra/test_infra/utils/logs_utils.py
Labels: size/L, ok-to-test, approved, lgtm

#2201 MGMT-14999: Add virtualization support for OCI nodes
  terraform_files/oci/00_main.tf
  terraform_files/oci/03_compute.tf
  terraform_files/oci/variables.tf
Labels: size/M, approved, lgtm, jira/valid-reference

#2207 MGMT-15018: Add option to mark variable origin
  src/assisted_test_infra/test_infra/helper_classes/config/base_config.py
  src/tests/base_test.py
  src/tests/global_variables/default_variables.py
  src/triggers/env_trigger.py
Labels: size/M, approved, lgtm, jira/valid-reference

#2211 MGMT-14944: Implement custom manifests upload in test infra
  .gitignore
  README.md
  skipper.env
  skipper.yaml
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_cluster_config.py
  src/assisted_test_infra/test_infra/helper_classes/entity.py
  src/assisted_test_infra/test_infra/utils/manifests.py
  src/service_client/assisted_service_api.py
  src/tests/global_variables/env_variables_defaults.py
Labels: size/M, approved, lgtm, jira/valid-reference

#2209 MGMT-14240: Plug OCI platform e2e test into CI
  Dockerfile.assisted-test-infra
  ansible_files/ansible.cfg
  ansible_files/oci_generic_destroy_ci_machine_playbook.yml
  ansible_files/roles/oci/create_infra/tasks/main.yml
  ansible_files/roles/oci/export_connection_details/files/packet-conf.sh
  ansible_files/roles/oci/export_connection_details/tasks/main.yml
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/assisted-additional-config.j2
  scripts/bring_assisted_service.sh
  scripts/hub-cluster/kind/kind.sh
  scripts/hub-cluster/minikube.sh
  scripts/install_k8s_clients.sh
  scripts/utils.sh
  src/assisted_test_infra/test_infra/controllers/node_controllers/oci_controller.py
  src/assisted_test_infra/test_infra/utils/utils.py
  src/triggers/default_triggers.py
  terraform_files/oci-ci-machine/02_network_security_groups.tf
  terraform_files/oci-ci-machine/03_compute.tf
  terraform_files/oci/01_network_security_groups.tf
  terraform_files/oci/03_compute.tf
Labels: size/L, approved, lgtm, jira/valid-reference
