Repository openshift/assisted-test-infra, pull requests merged in 2023-10, with the labels that each got.

#2265 MGMT-15598: Bugfix - list all cluster manifests irrespective of type
  src/service_client/assisted_service_api.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2269 NO-ISSUE: test_kube_api: enable disconnected mode
  skipper.env
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_cluster_config.py
  src/tests/global_variables/env_variables_defaults.py
  src/tests/test_kube_api.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2281 NO-ISSUE: use urlib3 < 2.0
  requirements.txt
Labels: approved, size/XS, lgtm, jira/valid-reference

#2274 NO-ISSUE: Add bonding support to assisted test infra
  README.md
  skipper.env
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_entity_config.py
  src/assisted_test_infra/test_infra/helper_classes/infra_env.py
  src/assisted_test_infra/test_infra/tools/static_network.py
  src/consts/env_defaults.py
  src/tests/base_kubeapi_test.py
  src/tests/global_variables/env_variables_defaults.py
  src/tests/test_kube_api.py
  terraform_files/baremetal/main.tf
  terraform_files/baremetal/variables-libvirt.tf
Labels: size/L, approved, lgtm, jira/valid-reference

#2283 NO-ISSUE: fix oci cleanup
  ansible_files/roles/oci/cleanup_resources/defaults/main.yml
  ansible_files/roles/oci/cleanup_resources/tasks/cleanup_resources.yml
Labels: size/S, approved, lgtm, jira/valid-reference

#2287 MGMT-15945: Pull service and index images from ocm-2.9 tag
  Makefile
Labels: approved, size/XS, lgtm, jira/valid-reference

#2291 NO-ISSUE: add eifrach to owners
  OWNERS
Labels: approved, size/XS, lgtm, jira/valid-reference

#2252 adds custom manifest functions(list,delete,create_single) used in kni…
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/service_client/assisted_service_api.py
Labels: ok-to-test, size/S, approved, lgtm

#2288 NO-ISSUE: Update to python 3.12
  Dockerfile.assisted-test-infra
  src/assisted_test_infra/test_infra/tools/static_network.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2292 NO-ISSUE: Riccardo and I as approvers
  OWNERS
Labels: approved, size/XS, lgtm, jira/valid-reference

#2285 NO-ISSUE: Support passing registry CA to spokes in kube API disconnected mode
  README.md
  skipper.env
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_cluster_config.py
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/infraenv.py
  src/tests/global_variables/env_variables_defaults.py
  src/tests/test_kube_api.py
Labels: size/M, approved, lgtm, jira/valid-reference

#2299 MGMT-16057: Make OCP 4.14 default on test-infra
  src/consts/consts.py
Labels: approved, size/XS, lgtm, jira/valid-reference
