Repository openshift/assisted-test-infra, pull requests merged in 2024-06, with the labels that each got.

#2440 NO-ISSUE: Update vsphere packer plugin and packer base ISO
  packer_files/vsphere_centos_template/build.pkr.hcl
  packer_files/vsphere_centos_template/variables.pkr.hcl
  src/assisted_test_infra/test_infra/controllers/node_controllers/node_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/tf_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
  src/assisted_test_infra/test_infra/helper_classes/entity.py
  src/assisted_test_infra/test_infra/helper_classes/nodes.py
  src/tests/test_targets.py
Labels: size/M, approved, lgtm, jira/valid-reference

#2452 [release-ocm-2.10] NO-ISSUE: fix for missing distutils
  requirements.txt
Labels: approved, size/XS, lgtm, jira/valid-reference

#2450 MGMT-17246: add support for ignoring clusters that already exist on jira
  src/assisted_test_infra/download_logs/__main__.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_nodes_config.py
  src/service_client/assisted_service_api.py
Labels: size/S, approved, lgtm, jira/valid-reference

#2455 Revert "MGMT-17246: add support for ignoring clusters that already exist on jira"
  src/assisted_test_infra/download_logs/__main__.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_nodes_config.py
  src/service_client/assisted_service_api.py
Labels: size/S, approved, lgtm, jira/valid-reference

#2454 [release-ocm-2.8] NO-ISSUE: fix for missing distutils
  requirements.txt
Labels: approved, size/XS, lgtm, jira/valid-reference

#2453 [release-ocm-2.9] NO-ISSUE: fix for missing distutils
  requirements.txt
Labels: approved, size/XS, lgtm, jira/valid-reference

#2457 [release-ocm-2.7] NO-ISSUE: fix for missing distutils
  requirements.txt
  scripts/install_environment.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#2459 NO-ISSUE: Fix for OCM branches
  scripts/install_environment.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#2464 MGMT-17246: Bug fix - change argument name to match command line argument name
  src/assisted_test_infra/download_logs/__main__.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2466 NO-ISSUE: Use centos 9 as default. Upgrade Nutanix packer plugin to latest
  packer_files/nutanix_centos_template/build.pkr.hcl
  packer_files/nutanix_centos_template/centos-config/ks.cfg
  packer_files/nutanix_centos_template/sources.pkr.hcl
Labels: size/S, approved, lgtm, jira/valid-reference

#2465 MGMT-18118: Use Rocky Linux 9 on OCI
  terraform_files/oci-ci-machine/00_main.tf
  terraform_files/oci-ci-machine/03_compute.tf
Labels: size/M, approved, lgtm, jira/valid-reference

#2447 NO-ISSUE: Fix cluster configuration name is not properly set on update cluster
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/infra_env.py
  src/tests/base_test.py
  src/tests/conftest.py
Labels: size/S, approved, lgtm, jira/valid-reference

#2471 NO-ISSUE: Add fallback installation with crb repository as it is included by default in some OS variants and causes an error when specified
  scripts/install_environment.sh
Labels: size/S, approved, lgtm, jira/valid-reference

#2469 NO-ISSUE: fixing minor syntax
  scripts/deploy_assisted_service.sh
  scripts/deploy_prometheus_ui.sh
  scripts/deploy_ui.sh
  scripts/install_environment.sh
  scripts/utils.sh
Labels: size/S, approved, lgtm, jira/valid-reference

#2476 [release-ocm-2.11] MGMT-18062: Update assisted-test-infra Makefile to pull images from ocm-2.11 tag
  Makefile
Labels: approved, size/XS, lgtm, jira/valid-reference

#2417 NO-ISSUE: Add natsort package to requirements.txt
  requirements.txt
Labels: ok-to-test, approved, size/XS, lgtm, jira/valid-reference

#2479 [Snyk] Fix for 25 vulnerabilities
  requirements.txt
Labels: approved, size/XS, lgtm

#2480 NO-ISSUE: pyvmomi version as 8.0.3 is broken
  requirements.txt
Labels: approved, size/XS, lgtm, jira/valid-reference

#2483 MGMT-18077: Set OCP 4.16 as default, add OCP 4.17 option
  src/consts/consts.py
Labels: approved, size/XS, lgtm, jira/valid-reference
