Repository openshift/assisted-test-infra, pull requests merged in 2024-12, with the labels that each got.

#2584 NO-ISSUE: Remove deletion of `control_plane_count` field during cluster creation
  src/service_client/assisted_service_api.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2583 MGMT-19336: Enable assisted-service fetching by specific commit reference
  scripts/bring_assisted_service.sh
Labels: size/M, approved, lgtm, jira/valid-reference

#2579 MGMT-19236: Add Openshift sandboxed containers operator(OSC) support
  src/consts/olm_operators.py
  src/triggers/default_triggers.py
Labels: ok-to-test, size/M, approved, lgtm, jira/valid-reference

#2553 MGMT-19278: Use multi-arch OCP release images with OPENSHIFT_VERSION configuration
  README.md
  scripts/deploy_assisted_service.sh
  scripts/override_images/override_os_images.py
  scripts/override_images/override_release_images.py
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/utils/utils.py
  src/consts/consts.py
  src/tests/global_variables/default_variables.py
  src/tests/global_variables/env_variables_defaults.py
Labels: size/L, approved, lgtm, jira/valid-reference

#2589 NO-ISSUE: Remove redundant line slipped in https://github.com/openshift/assisted-test-infra/pull/2553
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2591 NO-ISSUE: Fix networking test OCP version handling
  src/tests/test_e2e_install.py
Labels: size/S, approved, lgtm, jira/valid-reference

#2590 NO-ISSUE: Set workers hostname in 'none' platform according to their network
  terraform_files/none/main.tf
Labels: approved, size/XS, lgtm, jira/valid-reference

#2595 NO-ISSUE: Fix multi-arch version usage with OPENSHIFT_VERSION
  scripts/override_images/override_release_images.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2593 MGMT-18852: Static IP validation
  .flake8
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/utils/utils.py
  src/consts/__init__.py
  src/consts/consts.py
Labels: size/L, approved, lgtm, jira/valid-reference

#2600 NO-ISSUE: skip validation when is bond
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2599 NO-ISSUE: improve cleanup script
  Makefile
  src/cleanup.py
Labels: size/S, approved, lgtm, jira/valid-reference

#2601 Fix collect log raise exception when network does not exist
  src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
Labels: ok-to-test, approved, size/XS, lgtm

#2602 MGMT-19509: Enable automatic testing of user-managed load balancer in a k8s api flow
  Makefile
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/agent_cluster_install.py
  src/assisted_test_infra/test_infra/utils/k8s_utils.py
  src/consts/consts.py
  src/tests/test_kube_api.py
Labels: size/L, approved, lgtm, jira/valid-reference

#2603 NO-ISSUE: Fix DNS setting in k8s API test
  src/tests/test_kube_api.py
Labels: approved, size/XS, lgtm, jira/valid-reference
