Repository openshift/assisted-test-infra, pull requests merged in 2024-04, with the labels that each got.

#2354 Add colorized file handler same as stream handler
  src/service_client/logger.py
Labels: lifecycle/stale, ok-to-test, size/M, approved, lgtm

#2410 NO-ISSUE: Add env var to use OKD release and os images
  scripts/deploy_assisted_service.sh
  skipper.env
  src/assisted_test_infra/test_infra/utils/utils.py
  src/consts/consts.py
Labels: size/M, approved, lgtm, jira/valid-reference

#2413 NO-ISSUE: Use legit python image for failing ipxe CI test
  src/assisted_test_infra/test_infra/controllers/ipxe_controller/server/Dockerfile
Labels: approved, size/XS, lgtm, jira/valid-reference
