Repository openshift/assisted-test-infra, pull requests merged in 2024-01, with the labels that each got.

#2343 Fix verify_logs_uploaded
  src/assisted_test_infra/test_infra/utils/logs_utils.py
Labels: needs-ok-to-test, approved, size/XS, lgtm

#2351 Revert "MGMT-15772: Moving Equinix to use Metros"
  terraform_files/equinix-ci-machine/main.tf
  terraform_files/equinix-ci-machine/variables_equinix.tf
Labels: approved, size/XS, lgtm, jira/valid-reference

#2352 MGMT-16492: Use combined OCI manifests
  ansible_files/roles/oci/setup_oci_for_test_infra/tasks/custom_manifests.yml
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/machineconfig-ccm.yml.j2
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/machineconfig-csi.yml.j2
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/oci-ccm-00-namespace.yaml.j2
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/oci-ccm-01-service-account.yaml.j2
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/oci-ccm-02-cluster-role.yaml.j2
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/oci-ccm-03-cluster-role-binding.yaml.j2
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/oci-ccm-04-cloud-controller-manager-config.yaml.j2
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/oci-ccm-05-daemon-set.yaml.j2
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/oci-ccm.yml.j2
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/oci-csi.yml.j2
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/oci-kubelet-providerid.bu.j2
  ansible_files/roles/oci/setup_oci_for_test_infra/vars/main.yml
Labels: size/XXL, approved, lgtm, jira/valid-reference

#2355 MGMT-16499: Allow using custom OCP release when we create cluster
  scripts/deploy_assisted_service.sh
  src/assisted_test_infra/test_infra/utils/utils.py
  src/tests/conftest.py
Labels: size/S, approved, lgtm, jira/valid-reference

#2353 MGMT-15510: Initialize terraform controller after cluster registration
  src/assisted_test_infra/test_infra/controllers/node_controllers/node_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/tf_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/vsphere_controller.py
  src/assisted_test_infra/test_infra/helper_classes/entity.py
  src/assisted_test_infra/test_infra/helper_classes/nodes.py
  src/tests/test_targets.py
Labels: size/M, approved, lgtm, jira/valid-reference

#2358 MGMT-16330: disallow SDN network type testing for 4.15 and above
  src/tests/test_e2e_install.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2363 ensure version has semver compatible value
  src/tests/test_e2e_install.py
Labels: size/S, approved, lgtm

#2342 NO-ISSUE: add ability to configure minikube
  README.md
  scripts/hub-cluster/minikube.sh
Labels: size/S, approved, lgtm, jira/valid-reference

#2364 NO-ISSUE: add info for cluster status
  src/assisted_test_infra/test_infra/utils/utils.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2366 NO-ISSUE: Set version 1.24.0 for equinix provider
  terraform_files/equinix-ci-machine/main.tf
Labels: approved, size/XS, lgtm, jira/valid-reference

#2370 MGMT-16276: Add 4.16 ocp version
  src/consts/consts.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2375 Remove flake8 formatting that doesn't seem to work
  .flake8
Labels: approved, size/XS, lgtm
