Repository openshift/assisted-test-infra, pull requests merged in 2024-09, with the labels that each got.

#2524 MGMT-18658: update default rocky image for ARM test issues
  ansible_files/roles/common/setup_sftp_share/tasks/main.yml
  ansible_files/roles/common/setup_ssh_key_pair/tasks/main.yml
  scripts/install_environment.sh
  skipper.yaml
  terraform_files/equinix-ci-machine/variables_equinix.tf
Labels: size/M, approved, lgtm, jira/valid-reference

#2531 MGMT-18852: disable DHCP for static networking
  .gitignore
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  terraform_files/baremetal/main.tf
  terraform_files/baremetal/variables-libvirt.tf
Labels: size/S, approved, lgtm, jira/valid-reference

#2534 MGMT-18618 Fix local rhsso deployment of assisted-installer
  Makefile
  README.md
  skipper.env
  src/update_assisted_service_cm.py
Labels: approved, size/XS, lgtm

#2535 MGMT-18959: Enable OCP 4.18 installation
  src/consts/consts.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2533 MGMT-18905: moving to cloud config terraform
  .gitignore
  packer_files/nutanix_centos_template/build.pkr.hcl
  packer_files/nutanix_centos_template/sources.pkr.hcl
  packer_files/nutanix_centos_template/variables.pkr.hcl
  terraform_files/nutanix-ci-machine/main.tf
  terraform_files/nutanix-ci-machine/variables-nutanix.tf
Labels: size/L, approved, lgtm, jira/valid-reference

#2537 NO-ISSUE: Enable assisted-service image overrides
  README.md
  scripts/deploy_assisted_service.sh
  scripts/override_images/override_os_images.py
  scripts/override_images/override_release_images.py
  scripts/override_os_images.py
  scripts/override_release_images.py
  skipper.env
  src/consts/consts.py
Labels: size/L, approved, lgtm, jira/valid-reference
