Repository openshift/assisted-test-infra, pull requests merged in 2024-03, with the labels that each got.

#2394 NO-ISSUE: Add support for environment variable 'ENABLE_SKIP_MCO_REBOOT'
  scripts/deploy_assisted_service.sh
  skipper.env
  src/update_assisted_service_cm.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2396 Move dynamic-load-balancer image
  Makefile
Labels: approved, size/XS, lgtm

#2397 NO-ISSUE: Add support for assisted-service environment variable "ENABLE_SOFT_TIMEOUTS"
  scripts/deploy_assisted_service.sh
  skipper.env
  src/update_assisted_service_cm.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2401 fix nutanix default disk size
  packer_files/nutanix_centos_template/build.pkr.hcl
  packer_files/nutanix_centos_template/centos-config/ks.cfg
  packer_files/nutanix_centos_template/sources.pkr.hcl
  packer_files/nutanix_centos_template/variables.pkr.hcl
Labels: approved, size/XS, lgtm

#2404 MGMT-15772: change facilities to metro
  terraform_files/equinix-ci-machine/main.tf
  terraform_files/equinix-ci-machine/variables_equinix.tf
Labels: approved, size/XS, lgtm, jira/valid-reference

#2406 MGMT-17080: test mce and storage
  README.md
  src/assisted_test_infra/test_infra/utils/__init__.py
  src/assisted_test_infra/test_infra/utils/k8s_utils.py
  src/tests/test_e2e_install.py
Labels: size/M, approved, lgtm, jira/valid-reference
