Repository openshift/assisted-test-infra, pull requests merged in 2024-02, with the labels that each got.

#2376 NO-ISSUE: Update OCI check to test against stage/prod
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/consts/consts.py
  src/triggers/default_triggers.py
Labels: size/S, approved, lgtm, jira/valid-reference

#2381 Add default model when libvirt add_intrerface
  src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
Labels: needs-ok-to-test, approved, size/XS, lgtm

#2382 NO-ISSUE: Install iptables in the container
  Dockerfile.assisted-test-infra
  skipper.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#2384 MGMT-16493: Open KAS port when installing OCI cluster
  terraform_files/oci-ci-machine/00_main.tf
  terraform_files/oci/00_main.tf
  terraform_files/oci/01_network_security_groups.tf
Labels: size/S, approved, lgtm, jira/valid-reference

#2388 [release-ocm-2.10] MGMT-16877: Pull ocm-2.10 tag
  Makefile
Labels: approved, size/XS, lgtm, jira/valid-reference

#2391 NO-ISSUE: Adjust cleanup in OCI
  ansible_files/roles/oci/cleanup_resources/defaults/main.yml
Labels: approved, size/XS, lgtm, jira/valid-reference

#2390 MGMT-16622: Change 4.15 to the default version as it is GA
  src/consts/consts.py
Labels: approved, size/XS, lgtm, jira/valid-reference
