Repository openshift/assisted-test-infra, pull requests merged in 2024-07, with the labels that each got.

#2487 [Snyk] Security upgrade zipp from 3.15.0 to 3.19.1
  requirements-dev.txt
Labels: approved, size/XS, lgtm

#2488 [Snyk] Security upgrade zipp from 3.15.0 to 3.19.1
  requirements.txt
Labels: approved, size/XS, lgtm

#2486 MGMT-18333: Generate python client instead of using the one from assisted-service image
  .gitignore
  Dockerfile.assisted-test-infra
  Makefile
  README.md
  scripts/bring_assisted_service.sh
  scripts/create_full_environment.sh
Labels: size/M, approved, lgtm, jira/valid-reference

#2498 [release-ocm-2.8] MGMT-18333: Generate python client instead of using the one from assisted-service image
  .gitignore
  Dockerfile.assisted-test-infra
  Makefile
  README.md
  scripts/bring_assisted_service.sh
  scripts/create_full_environment.sh
  scripts/utils.sh
Labels: size/M, approved, lgtm, jira/valid-reference

#2497 [release-ocm-2.9] MGMT-18333: Generate python client instead of using the one from assisted-service image
  .gitignore
  Dockerfile.assisted-test-infra
  Makefile
  README.md
  scripts/bring_assisted_service.sh
  scripts/create_full_environment.sh
Labels: size/M, approved, lgtm, jira/valid-reference

#2490 [MGMT-18102] fix for platform none/external on RHEL9
  scripts/deploy_assisted_service.sh
  scripts/utils.sh
Labels: size/M, approved, lgtm

#2505 NO-ISSUE: testing python workaround
  requirements.txt
  terraform_files/equinix-ci-machine/main.tf
Labels: approved, size/XS, lgtm, jira/valid-reference
