Repository openshift/assisted-test-infra, pull requests merged in 2024-11, with the labels that each got.

#2556 OCI: Add default tag_namespace_name for terraform variables.
  src/assisted_test_infra/test_infra/controllers/node_controllers/oci_api_controller.py
Labels: needs-ok-to-test, approved, size/XS, lgtm

#2562 MGMT-19080: Setup test infra for testing new control_plane_count field in https://github.com/openshift/assisted-service/pull/6917
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/service_client/assisted_service_api.py
Labels: size/S, approved, lgtm, jira/valid-reference

#2561 NO-ISSUE: better handle pull secret or file of pull secret
  Makefile
  skipper.env
  src/assisted_test_infra/test_infra/utils/utils.py
Labels: size/M, approved, lgtm, jira/valid-reference

#2557 MGMT-19248: Add OpenShift AI operator
  src/consts/olm_operators.py
  src/triggers/default_triggers.py
Labels: size/S, approved, lgtm, jira/valid-reference

#2564 Increasing Terraform's timeout.
  Dockerfile.assisted-test-infra
Labels: approved, size/XS, lgtm

#2569 NO-ISSUE: allow test infra to work with older assisted versions where the field is missing
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
Labels: size/L, approved, lgtm, jira/valid-reference

#2558 [MGMT-17556] Allow to modify files inside running container.
  src/assisted_test_infra/test_infra/controllers/containerized_controller.py
  src/assisted_test_infra/test_infra/controllers/ipxe_controller/ipxe_controller.py
Labels: ok-to-test, size/M, approved, lgtm

#2567 MGMT-17556: Add network to clean os boot data
  src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
Labels: ok-to-test, approved, size/XS, lgtm, jira/valid-reference

#2559 MGMT-17556: Add iscsi target controller , allow to boot from iscsi or attach
  Dockerfile.assisted-test-infra
  skipper.yaml
  src/assisted_test_infra/test_infra/controllers/__init__.py
  src/assisted_test_infra/test_infra/controllers/iscsi_target_controller.py
  src/tests/base_test.py
Labels: size/L, ok-to-test, approved, lgtm, jira/valid-reference

#2575 NO-ISSUE: Fix logs gathering for kind deployment in the CI
  scripts/download_logs.sh
Labels: approved, lgtm, jira/valid-reference

#2576 NO-ISSUE: Enable sourcing utils.sh in function calls
  scripts/download_logs.sh
  scripts/utils.sh
Labels: approved, size/XS, lgtm, jira/valid-reference
