Repository openshift/assisted-test-infra, pull requests merged in 2024-10, with the labels that each got.

#2540 MGMT-19026: Add authentication support for refresh token of ocm-cli
  Makefile
  skipper.env
  src/assisted_test_infra/download_logs/__main__.py
  src/manage/manage.py
  src/service_client/assisted_service_api.py
  src/service_client/client_factory.py
  src/tests/global_variables/default_variables.py
  src/tests/global_variables/env_variables_defaults.py
Labels: size/M, approved, lgtm, jira/valid-reference

#2543 NO-ISSUE: Avoid overriding OS_IMAGES in assisted operator deployments
  scripts/deploy_assisted_service.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#2542 MGMT-19039: Prioritize OPENSHIFT_VERSION over OPENSHIFT_INSTALL_RELEASE_IMAGE when overriding images
  scripts/override_images/override_release_images.py
Labels: size/S, approved, lgtm, jira/valid-reference

#2545 MGMT-18956: Set OCP 4.17 as default version
  src/consts/consts.py
Labels: approved, size/XS, lgtm

#2526 MGMT-18603: Add OCI controller implemented with oracle API
  skipper.env
  src/assisted_test_infra/test_infra/controllers/__init__.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/__init__.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/oci_api_controller.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_oci_config.py
  src/tests/base_test.py
  src/tests/global_variables/env_variables_defaults.py
Labels: size/XL, ok-to-test, approved, lgtm, jira/valid-reference

#2552 MGMT-18603: OCI Add wait_callback while applying stack configuration
  src/assisted_test_infra/test_infra/controllers/node_controllers/oci_api_controller.py
Labels: ok-to-test, size/S, approved, lgtm, jira/valid-reference
