Repository openshift/assisted-test-infra, pull requests merged in 2024-08, with the labels that each got.

#2507 NO-ISSUE: Fix name to fetch Rocky in OCI
  terraform_files/oci-ci-machine/03_compute.tf
Labels: approved, size/XS, lgtm, jira/valid-reference

#2509 MGMT-18378: fix for LVMs with worker nodes
  src/consts/olm_operators.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2501 iPXE assets download to container and modify iPxe script
  src/assisted_test_infra/test_infra/controllers/ipxe_controller/ipxe_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
Labels: ok-to-test, size/M, approved, lgtm

#2516 NO-ISSUE: Fix python client generation when more than one client exist
  Makefile
Labels: approved, size/XS, lgtm, jira/valid-reference

#2515 MGMT-18442: Add service account authentication mechanism alongside offline token
  Makefile
  README.md
  requirements.txt
  skipper.env
  src/assisted_test_infra/download_logs/__main__.py
  src/assisted_test_infra/download_logs/download_logs.py
  src/manage/manage.py
  src/service_client/__init__.py
  src/service_client/assisted_service_api.py
  src/service_client/client_factory.py
  src/tests/global_variables/default_variables.py
  src/tests/global_variables/env_variables_defaults.py
  src/update_assisted_service_cm.py
Labels: size/L, approved, lgtm, jira/valid-reference

#2518 MGMT-18626: Add TestClusterScaleUp for baremetal spanned clusters
  Makefile
  src/tests/templates/day2_baremetal.yaml.j2
  src/tests/templates/day2_machine.yaml.j2
  src/tests/test_ctlplane_scaleup.py
Labels: size/L, approved, lgtm, jira/valid-reference

#2473 MGMT-8357: Deploy assisted-service for e2e tests in Kind
  Makefile
  README.md
  scripts/bring_assisted_service.sh
  scripts/create_full_environment.sh
  scripts/deploy_assisted_service.sh
  scripts/deploy_ui.sh
  scripts/hub-cluster/create.sh
  scripts/hub-cluster/delete.sh
  scripts/hub-cluster/kind/kind-config.yaml
  scripts/hub-cluster/kind/kind.sh
  scripts/hub-cluster/minikube.sh
  scripts/utils.sh
  src/assisted_test_infra/test_infra/utils/utils.py
Labels: size/L, approved, lgtm, jira/valid-reference

#2521 NO-ISSUE: Fix UI pod readiness condition in UI deployment script
  scripts/deploy_ui.sh
Labels: approved, size/XS, lgtm, jira/valid-reference
