Repository openshift/assisted-test-infra, pull requests merged in 2024-05, with the labels that each got.

#2424 NO-ISSUE: Fix Nutanix fail to login ssh key
  packer_files/nutanix_centos_template/centos-config/ks.cfg
Labels: approved, size/XS, lgtm, jira/valid-reference

#2426 NO-ISSUE: Update nutanix packer ssh key
  packer_files/nutanix_centos_template/centos-config/ks.cfg
Labels: approved, size/XS, jira/valid-reference

#2428 NO-ISSUE: Update nutanix packer ssh key
  packer_files/nutanix_centos_template/centos-config/ks.cfg
Labels: approved, size/XS, jira/valid-reference

#2429 NO-ISSUE: Revert ssh key nutanix
  packer_files/nutanix_centos_template/centos-config/ks.cfg
Labels: approved, size/XS, lgtm, jira/valid-reference

#2431 NO-ISSUE: Add generic CI SSH key for nutanix packer
  packer_files/nutanix_centos_template/centos-config/ks.cfg
  packer_files/nutanix_centos_template/sources.pkr.hcl
  packer_files/nutanix_centos_template/variables.pkr.hcl
Labels: size/M, approved, lgtm, jira/valid-reference

#2419 MGMT-17250: Support RHEL9
  scripts/create_full_environment.sh
  scripts/install_environment.sh
  scripts/utils.sh
  terraform_files/baremetal_host/main.tf
Labels: size/L, approved, lgtm, jira/valid-reference

#2438 NO-ISSUE: Add my account in OWNERS
  OWNERS
Labels: approved, size/XS, lgtm, jira/valid-reference

#2437 NO-ISSUE: Add my account in OWNERS
  OWNERS
Labels: approved, size/XS, lgtm, jira/valid-reference

#2421 NO-ISSUE: Update `requirements.txt` to match the package naming conventions of the interpreter.
  requirements.txt
Labels: approved, size/XS, lgtm, jira/valid-reference

#2443 NO-ISSUE: Fix missing distutils when trying to `override_release_images`
  requirements.txt
Labels: approved, size/XS, lgtm, jira/valid-reference

#2377 Add status_info for waiting for specific host
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/utils/waiting.py
Labels: lifecycle/stale, ok-to-test, approved, size/XS, lgtm

#2445 NO-ISSUE: Fix failures when there are no nodes on entity initialization
  src/assisted_test_infra/test_infra/helper_classes/entity.py
Labels: approved, size/XS, lgtm, jira/valid-reference
