Repository openshift/assisted-test-infra, pull requests merged in 2025-04, with the labels that each got.

#2662 MGMT-20216: Remove nmstate operator memory and CPU requirements
  src/consts/olm_operators.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2666 MGMT-20256: fix 'wait_for_api_readiness' timeout error
  src/assisted_test_infra/test_infra/__init__.py
  src/assisted_test_infra/test_infra/helper_classes/base_cluster.py
  src/tests/base_kubeapi_test.py
  src/tests/base_test.py
  src/tests/test_kube_api.py
Labels: size/S, approved, lgtm, jira/valid-reference

#2668 MGMT-20334: Fix pull-secret censor
  src/assisted_test_infra/download_logs/download_logs.py
Labels: size/S, approved, lgtm, jira/valid-reference

#2667 MGMT-20218: Add documentation to test-infra - getting started doc to ease the use of new users
  README.md
  docs/assisted-deployment.md
  docs/assisted-service-client.md
  docs/assisted-testing.md
  docs/build-image.md
  docs/getting-started.md
  docs/overview.md
  docs/prerequisites.md
  docs/setup.md
  docs/warning.md
Labels: size/L, approved, lgtm, jira/valid-reference

#2672 MGMT-20322: Add AI bundles env vars
  skipper.env
Labels: approved, size/XS, lgtm, jira/valid-reference

#2670 MGMT-20168: Allow osImageVersion to be set on InfraEnv
  README.md
  src/assisted_test_infra/test_infra/helper_classes/config/base_infra_env_config.py
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/infraenv.py
  src/tests/global_variables/env_variables_defaults.py
  src/tests/test_kube_api.py
Labels: size/S, approved, lgtm, jira/valid-reference

#2675 Add masters_count to oci api
  src/assisted_test_infra/test_infra/controllers/node_controllers/oci_api_controller.py
Labels: ok-to-test, approved, size/XS, lgtm
