Repository openshift/assisted-test-infra, pull requests merged in 2025-06, with the labels that each got.

#2687 [release-ocm-2.14] NO-ISSUE: Update assisted-service image tag to ocm-2.14
  Makefile
Labels: approved, size/XS, lgtm, jira/valid-reference

#2689 NO-ISSUE: Add commit reference to test-infra image
  .dockerignore
  Dockerfile.assisted-test-infra
Labels: approved, size/XS, lgtm, jira/valid-reference

#2688 MGMT-20779: Add AWS cleanup playbook
  ansible_files/aws_ec2_region_cleanup.yml
Labels: size/L, approved, lgtm, jira/valid-reference

#2682 MGMT-20382: Adjust AITRIAGE File Collection
  src/assisted_test_infra/download_logs/download_logs.py
  src/consts/consts.py
Labels: size/M, approved, lgtm, jira/valid-reference

#2695 NO-ISSUE: Add ansible aws module requirements to aws cleanup playbook
  ansible_files/aws_ec2_region_cleanup.yml
Labels: size/S, approved, jira/valid-reference

#2696 MGMT-20915: Add OCP 4.20 version and set OCP 4.19 as default
  src/consts/consts.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2699 NO-ISSUE: Fix OFCIR_URL env var
  ansible_files/vars/ci_ofcir_hetrogeneous_infrastructure.yml
Labels: approved, size/XS, jira/valid-reference
