Repository openshift/assisted-test-infra, pull requests merged in 2025-08, with the labels that each got.

#2706 MGMT-14822: Add MetalLB operator
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_cluster_config.py
  src/consts/__init__.py
  src/tests/global_variables/env_variables_defaults.py
  src/triggers/default_triggers.py
Labels: size/M, approved, lgtm, jira/valid-reference

#2714 NO-ISSUE: Avoid deploying the UI in CI jobs
  scripts/deploy_ui.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#2716 MGMT-20470: Add support for TNA clusters
  README.md
  scripts/deploy_assisted_service.sh
  skipper.env
  src/assisted_test_infra/test_infra/controllers/node_controllers/adapter_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/node.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/node_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_nodes_config.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_terraform_config.py
  src/assisted_test_infra/test_infra/helper_classes/nodes.py
  src/consts/consts.py
  src/consts/env_defaults.py
  src/consts/resources.py
  src/tests/global_variables/env_variables_defaults.py
  src/triggers/default_triggers.py
  terraform_files/baremetal/main.tf
  terraform_files/baremetal/variables-libvirt.tf
Labels: size/L, approved, lgtm, jira/valid-reference

#2719 MGMT-21416: Fix heterogeneous workflow by installing fuse3
  ansible_files/README.md
  ansible_files/roles/setup_sftp_share/tasks/main.yml
Labels: approved, size/XS, lgtm, jira/valid-reference
