Repository openshift/assisted-test-infra, pull requests merged in 2025-03, with the labels that each got.

#2642 MGMT-20006: Add OCP 4.19 version and set 4.18 is default
  src/consts/consts.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2641 Update control plane count from trigger
  src/consts/consts.py
  src/triggers/default_triggers.py
Labels: ok-to-test, size/S, approved, lgtm

#2644 MGMT-19831: Enable automatic testing user-managed load balancer with vSphere
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_cluster_config.py
  src/tests/global_variables/env_variables_defaults.py
Labels: size/S, approved, lgtm, jira/valid-reference

#2646 MGMT-19831: Let test-infra provide the machine network for vSphere umlb dynamically
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2649 NO-ISSUE: Fix running two targets when running make deploy_nodes
  Makefile
  src/tests/test_targets.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2647 MULTIARCH-5357: Add libvirt and install on s390x KVM a five node clus…
  Dockerfile.assisted-test-infra
  Makefile
  README.md
  scripts/install_environment.sh
  skipper.env
  src/assisted_test_infra/test_infra/controllers/node_controllers/__init__.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/kvm_s390x_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/node_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/zvm_controller.py
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/infra_env.py
  src/assisted_test_infra/test_infra/helper_classes/nodes.py
  src/assisted_test_infra/test_infra/tools/assets.py
  src/consts/env_defaults.py
  src/tests/base_test.py
  src/tests/global_variables/env_variables_defaults.py
  src/tests/test_targets.py
  src/triggers/default_triggers.py
Labels: size/XL, ok-to-test, approved, lgtm, jira/valid-reference

#2652 MGMT-20164: Add NHO alongside its remediators
  src/consts/olm_operators.py
Labels: size/S, approved, lgtm, jira/valid-reference

#2653 MGMT-20190: Add Node Maintenance Operator
  src/consts/olm_operators.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2650 Fix ip static validations.
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
Labels: ok-to-test, approved, size/XS, lgtm

#2654 NO-ISSUE: Remove eran ifrach account from OWNERS
  OWNERS
Labels: approved, size/XS, lgtm, jira/valid-reference

#2655 [release-ocm-2.13] NO-ISSUE: Remove eran ifrach account from OWNERS
  OWNERS
Labels: approved, size/XS, lgtm, jira/valid-reference

#2660 [release-ocm-2.9] NO-ISSUE: Update OWNERS
  OWNERS
Labels: approved, size/XS, lgtm, jira/valid-reference

#2663 MGMT-20191: Add Kube Descheduler Operator
  src/consts/olm_operators.py
Labels: approved, size/XS, lgtm, jira/valid-reference
