Repository openshift/assisted-test-infra, pull requests merged in 2025-01, with the labels that each got.

#2604 Increase iSCSI target dataout timeout due to failures in multi nodes
  src/assisted_test_infra/test_infra/controllers/iscsi_target_controller.py
Labels: ok-to-test, approved, size/XS, lgtm

#2608 MGMT-19684: Enable automatic testing of user managed load balancer with hosts in the same subnet but load balancer outside this subnet on baremetal for k8s API flow
  Makefile
  src/assisted_test_infra/test_infra/helper_classes/kube_helpers/agent_cluster_install.py
  src/tests/base_kubeapi_test.py
  src/tests/test_kube_api.py
Labels: size/M, approved, lgtm, jira/valid-reference

#2613 MGMT-19569: validate static IP in bond
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
Labels: size/S, approved, lgtm, jira/valid-reference

#2615 MULTIARCH-5289: download_iso fix issue when downloading iso for s390x
  src/assisted_test_infra/test_infra/controllers/node_controllers/zvm_controller.py
Labels: needs-ok-to-test, size/S, approved, lgtm, jira/valid-reference

#2606 Add baremeral support for reboot from iso images.
  README.md
  requirements.txt
  skipper.env
  src/assisted_test_infra/test_infra/__init__.py
  src/assisted_test_infra/test_infra/controllers/__init__.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/__init__.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/adapter_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/redfish_controller.py
  src/assisted_test_infra/test_infra/helper_classes/config/__init__.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_redfish_config.py
  src/tests/base_test.py
  src/tests/config/global_configs.py
  src/tests/global_variables/env_variables_defaults.py
  src/tests/test_targets.py
Labels: size/XL, ok-to-test, approved, lgtm

#2616 MGMT-19510: Enable automatic testing of user-managed load balancer using test-infra with hosts on different subnets
  src/assisted_test_infra/test_infra/controllers/node_controllers/terraform_controller.py
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_cluster_config.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_entity_config.py
  src/tests/test_kube_api.py
  terraform_files/baremetal/main.tf
  terraform_files/baremetal/variables-libvirt.tf
Labels: size/L, approved, lgtm, jira/valid-reference

#2619 MGMT-19668: Adding nmstate operator to assisted installer
  src/consts/olm_operators.py
  src/triggers/default_triggers.py
Labels: size/S, approved, lgtm, jira/valid-reference

#2622 NO-ISSUE: Fix worker IPs for load balancer are taken only from the primary CIDR
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#2625 Add nopin_timeout to iSCSI installation
  src/assisted_test_infra/test_infra/controllers/iscsi_target_controller.py
Labels: needs-ok-to-test, approved, size/XS, lgtm
