Repository openshift/assisted-test-infra, pull requests merged in 2025-02, with the labels that each got.

#2621 Multiarch-5290_add_download_ipxe_script
  Makefile
  README.md
  skipper.env
  src/assisted_test_infra/test_infra/controllers/node_controllers/zvm_controller.py
  src/assisted_test_infra/test_infra/helper_classes/base_cluster.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_cluster_config.py
  src/assisted_test_infra/test_infra/helper_classes/infra_env.py
  src/service_client/assisted_service_api.py
  src/tests/global_variables/env_variables_defaults.py
  src/tests/test_targets.py
Labels: ok-to-test, size/M, approved, lgtm

#2624 NO-ISSUE: Adjust OCI to work with UI flow
  Makefile
  skipper.env
  src/assisted_test_infra/test_infra/controllers/node_controllers/oci_api_controller.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_cluster_config.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_entity_config.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_infra_env_config.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_oci_config.py
  src/tests/global_variables/env_variables_defaults.py
  src/tests/test_targets.py
Labels: size/L, approved, lgtm, jira/valid-reference

#2628 NO-ISSUE: Bump Terraform Libvirt provider to the latest version
  terraform_files/baremetal/main.tf
  terraform_files/baremetal_host/main.tf
  terraform_files/baremetal_infra_env/main.tf
  terraform_files/none/main.tf
Labels: approved, size/XS, lgtm, jira/valid-reference

#2630 Add more log info for redfish controller
  src/assisted_test_infra/test_infra/controllers/node_controllers/redfish_controller.py
Labels: needs-ok-to-test, approved, size/XS, lgtm

#2633 [release-ocm-2.13] MGMT-19949: Update Assisted Test Infra Default Service Image Tag
  Makefile
Labels: approved, size/XS, lgtm, jira/valid-reference

#2635 NO-ISSUE: Trigger new image promotiom to ocm-2.14 image stream
  README.md
Labels: approved, size/XS, lgtm, jira/valid-reference

#2636 Revert "NO-ISSUE: Trigger new image promotiom to ocm-2.14 image stream"
  README.md
Labels: approved, size/XS, lgtm, jira/valid-reference

#2573 MGMT-19450: Update oci e2e test
  Makefile
  ansible_files/oci_generic_create_ci_machine_playbook.yml
  ansible_files/oci_generic_destroy_ci_machine_playbook.yml
  ansible_files/roles/oci/cleanup_resources/defaults/main.yml
  ansible_files/roles/oci/create_infra/tasks/main.yml
  ansible_files/roles/oci/setup_oci_for_test_infra/defaults/main.yml
  ansible_files/roles/oci/setup_oci_for_test_infra/tasks/custom_manifests.yml
  ansible_files/roles/oci/setup_oci_for_test_infra/tasks/main.yml
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/assisted-additional-config.j2
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/machineconfig-ccm.yml.j2
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/machineconfig-csi.yml.j2
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/oci-ccm.yml.j2
  ansible_files/roles/oci/setup_oci_for_test_infra/templates/oci-csi.yml.j2
  ansible_files/roles/oci/setup_oci_for_test_infra/vars/main.yml
  ansible_files/vars/standalone_oci_sample.yml
  scripts/deploy_assisted_service.sh
  skipper.yaml
  src/assisted_test_infra/test_infra/controllers/__init__.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/__init__.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/node.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/oci_api_controller.py
  src/assisted_test_infra/test_infra/controllers/node_controllers/oci_controller.py
  src/assisted_test_infra/test_infra/helper_classes/base_cluster.py
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/utils/manifests.py
  terraform_files/oci-ci-machine/00_main.tf
  terraform_files/oci-ci-machine/01_networking.tf
  terraform_files/oci-ci-machine/02_compute.tf
  terraform_files/oci-ci-machine/02_network_security_groups.tf
  terraform_files/oci-ci-machine/03_compute.tf
  terraform_files/oci-ci-machine/output.tf
  terraform_files/oci-ci-machine/variables.tf
  terraform_files/oci/00_main.tf
  terraform_files/oci/01_network_security_groups.tf
  terraform_files/oci/02_custom_image.tf
  terraform_files/oci/03_compute.tf
  terraform_files/oci/04_load_balancer.tf
  terraform_files/oci/05_dns.tf
  terraform_files/oci/variables.tf
Labels: size/XXL, approved, lgtm, jira/valid-reference

#2632 Mgmt-19419: replace HighAvailabilityMode with ControlPlaneCount - phase 1
  src/assisted_test_infra/test_infra/helper_classes/cluster.py
  src/assisted_test_infra/test_infra/helper_classes/config/base_entity_config.py
  src/consts/consts.py
  src/consts/env_defaults.py
  src/tests/global_variables/env_variables_defaults.py
  src/triggers/default_triggers.py
Labels: size/M, approved, lgtm, jira/valid-reference

#2639 NO-ISSUE: Adjust OCI to work with UI
  src/tests/test_targets.py
Labels: approved, size/XS, lgtm, jira/valid-reference
